### ISSUE TITLE
RetroPie - WHDLoad-LHA-files no longer launch correctly.

### ISSUE THREAD

**Issue by Retro1968** [BlitterStudio/amiberry#1001]
Raspberry Pi 4, RetroPie 4.8, Amiberry v.5.3 (2022-07-01).

Hello Dimitris,
under RetroPie 4.8 I not only installed WHDLoad files under my Workbench 3.2.1, but also as LHA files that can be launched from the RetroPie menu.
![LHA#1](https://user-images.githubusercontent.com/58906142/181726706-32f0f514-40bf-4227-b7a9-4ac0f1250361.jpg)

This has always worked well up to now, since amiberry 5.3 the game start no longer works; I actually only get as far as the AmigaDOS level.
![LHA#2](https://user-images.githubusercontent.com/58906142/181726776-f271a79b-a3a7-4760-9515-97df22c0b25e.jpg)

Attached are my amiberry.conf and default.uae.
[configs.zip](https://github.com/BlitterStudio/amiberry/files/9218514/configs.zip)

Cheers
Retro1968

**Comment by nemo93** [comment]
@Retro1968 thanks for reporting. This is my exact configuration > launching Amiga packages straight from a frontend. Here I got no issue whatsoever. Please confirm the following lines are set in `emulators.cfg` under the `configs/amiga` dir of your Retropie setup:

```
amiberry = "/opt/retropie/emulators/amiberry/amiberry.sh %ROM%"
default = "amiberry"
```

Next can you try with just those 3 KS as per below to be sure? You seem to have lot more 1.x and 3.x. 
```
ROMName=KS ROM v1.3 (A500,A1000,A2000) rev 34.5 (256k) [315093-02]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick13.rom
ROMType=256
ROMName=KS ROM v2.05 (A600HD) rev 37.350 (512k) [391304-02]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick20.rom
ROMType=256
ROMName=KS ROM v3.1 (A1200) rev 40.68 (512k) [391773-01/391774-01]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick31.rom
ROMType=256
```

You confirm this is happening to any games right? From your list let's focus on Aladdin as this game runs without issue here and it's part of my test bed.

**Comment by Retro1968** [comment]
Meine emulators.cfg scheint in Ordnung zu sein:  [emulators.zip](https://github.com/BlitterStudio/amiberry/files/9225852/emulators.zip)

I installed amiberry 5.3 manually and use the sdl2 version, which I compile with this command: make -j4 PLATFORM=rpi4-sdl2
Does the RetroPieSetup still use the dmx version?

**Comment by Retro1968** [comment]
I was able to solve the problem, after reinstalling amiberry manually, I noticed that the configs/whdboot folder was corrupt... some files had a size of 0 bytes. Now everything works again.  Thx for the help! :-)
