### ISSUE TITLE
Can't get sound from headphone jack on Amiberry on RetroPie

### ISSUE THREAD

**Issue by iss05e** [BlitterStudio/amiberry#1002]
Hello,

I can't seem to get sound out of the headphone jack when running Amiberry on RetroPie.  The default audio output device has been set to "Headphones" through RetroPie and it works fine for the other emulators.  It was also fine on the previous version of Amiberry running on RetroPie.

My version of RetroPie is 4.8, running Amiberry v5.3 updated from binary.

If I start Amiberry, I can see that the default output under Sound is: "SDL2: bcm2835 HDMI 1, bcm2835 HDMI 1". It's as if Amiberry isn't inheriting the sound config from RetroPie.

If I change it to "SDL2: bcm2835 Headphones, bcm2835 Headphones", it doesn't seem to save the setting when I exit.

Is there amywhere else I can set the default sound output to headphones?  I've had a look at the amiberry.conf file, but there doesn't seem to be any setting to force sound through the headphone jack.

Any advice much appreciated.

Regards,
Paul

**Comment by Retro1968** [comment]
I use dvi and the headphonejack and edited the config.txt (is on the sd-cart in the boot partition) like this:

# 1 = Normal DVI mode (no sound), 2 = Normal HDMI mode (sound will be sent if supported and enabled)
hdmi_drive=1

**Comment by iss05e** [comment]
I've solved this now.  From RetroPie, I had to do the following:

- Go to "+START AMIBERRY"
- Go to "Sound" and change to headphones in the drop-down options
- Go to "Configurations"
- Select "Save"

Amiberry then saves a UAE default configuration, with headphone as the default sound output.
