### ISSUE TITLE
Can not use my joystick (Sony Dualshock 3) as a mouse.

### ISSUE THREAD

**Issue by legluondunet** [BlitterStudio/amiberry#1003]
Hello,
Can not use my joystick (Sony Dualshock 3) as a mouse.
I would like to play my Amiga games without needed to connect a keyboard or a mouse, just use a Joystick.
That is possible for a lot of games that do not need more than a mouse (direction and right click, left click) to play.
It would be great if, when user use only a joystick, to not configure anything, Amiberry would automagically recognize it and if no mouse is available, use joystick as a mouse. 
UAE4Arm automagically configures the right pad of the joystick as a mouse (direction), could be a solution for Amiberry too.
This is not only a feature request, it's a Amiberry bug report as I can actually not use my joystick as a mouse in all games I tried, even if I configure correctly Amiberry (see screenshots above).

![screenshot-2022-08-13T14-18-33-183Z](https://user-images.githubusercontent.com/325405/184498674-2e158601-809a-44d2-b301-0ade56d7d8e6.png)
![screenshot-2022-08-13T14-18-44-454Z](https://user-images.githubusercontent.com/325405/184498676-13a21a8f-fe48-4356-b39d-1a350cd1c9aa.png)
![screenshot-2022-08-13T14-18-39-954Z](https://user-images.githubusercontent.com/325405/184498677-962fb530-ccac-4710-b97a-139778633d03.png)

Thank you for your help.
OS: Recalbox on RPI

**Comment by midwan** [comment]
There are a few ways you can use the controller as a mouse:
- Have it at port 1 as it looks like in your screenshot, and enable Mouse Stick (dropdown further down in the panel)
- Have it at port 0, and use the type Mouse, instead of joystick

The analog stick will work as a mouse only when using the Mouse Stick option, while the D-pad will also work as a mouse if you set the type to "Mouse".

**Comment by legluondunet** [comment]
Thank you for your quick answer. 
Effectively, if I set my gamepad in port 0, nothing more to do...I return to my game and I can use my gamepad as a mouse.
DPad is quicker than left analog stick to move and it is very practice to obtain two different speed.
But I have to do this conf  everytime I launch a game...
--> Could it be more automatic? Could Amiberry use automatically my joystick as a mouse when It doesn't see a mouse connected? Without any user interaction?
--> Could Amiberry use gamepad as a mouse for the Amiberry GUI too? Actually use a gamepad to change Amiberry configuration is not easy.
