### ISSUE TITLE
WHDLoad: dh1: / Games don't run if there is a comma in the path name

### ISSUE THREAD

**Issue by celeritydesign** [BlitterStudio/amiberry#1004]
**Description:**
WHDLoad games within a subfolder containing commas in the name, fail to load with "Please insert volume Games" dos error. This is because dh1 has not mounted.

**Steps to reproduce the behavior:**
1. In /home/pi/RetroPie/roms/amiga set up a subfolder with a comma in the name.  (eg: "08 Sport, Games, Pong") 
2. Restart EmulationStation so that /opt/retropie/configs/all/emulationstation/gamelists/amiga/gamelist.xml is all uptodate etc
3. Try and run a game from within your new folder (eg: Jimmy White's Snooker)
4. See error: "Please insert volume Games"
5. Go into Amiberry menu with F12 and open the "Hard drives" tab. You should see an entry for dh1, volume name "Games".  Click the three dots button to edit
6. The path for dh1: will be truncated before the first comma in your path name. So in the example above, it would read "08 Sport" instead of "08 Sport, Games, Pong"

**Current fix:**
1. Rename folder name to remove commas
2. Restart EmulationStation so that /opt/retropie/configs/all/emulationstation/gamelists/amiga/gamelist.xml is all uptodate etc
3. Games within the folder should now run as normal

**System information:** 
RetroPie v4.8
Amiberry v5.3

**Comment by midwan** [comment]
@celeritydesign 
I think this is also true for WinUAE, where the code comes from. Commas are used as delimiters in the config file, to separate the various details regarding an HDD entry (path, device name, etc).

I guess the proper solution would be to enclose the path in quotes, so it's unaffected by any commas in between. I'll have to see how hard that is to change/implement, without breaking too much with the merges from WinUAE...

**Comment by midwan** [comment]
Sorry, this took a while to properly look into.
I was wrong in my initial assumption that this is a generic problem. Manually adding a directory with spaces and commas as a virtual HDD, works fine (in both Amiberry and WinUAE). However, it fails as you saw in the WHDLoad booter.

I'll take a closer look and try to fix this.
