### ISSUE TITLE
Amiberry - taking a screenshot?

### ISSUE THREAD

**Issue by simulant-systems** [BlitterStudio/amiberry#1005]
Hi does Amiberry let you take an in-game screenshot?

I can't seem to find a custom hotkey option I can make for a screenshot on the menu, and using the default Retropie screenshot hotkey, or prtscr etc doesn't work either.

Apologies if this is more of a RetroPie question, but how do you capture a screenshot?

Thanks for your help.

**Comment by nemo93** [comment]
By using savestate from GUI panel that should give you a screenshot. Check inside 'screenshots' from your Amiberry config directory once done. That's a workaround as I don't recall a more direct way to get a screen grab!

**Comment by midwan** [comment]
@simulant-systems 
You are correct, the Screenshot to file (or to clipboard) functions are not yet implemented. 
Screenshots are saved to disk when creating a Savestate, as @nemo93 mentioned above, so that is a temporary work-around for now.

It shouldn't be too hard to implement, so I'll look into this for the next version

**Comment by midwan** [comment]
@simulant-systems 
Implemented with the latest commit in `master`, this will be part of the next binary release also

**Comment by mrandreastoth** [comment]
How are these screenshots taken? I'm hitting PrtSc on my keyboard then checking the screenshot folder but nothing.

**Comment by giantclambake** [comment]
AFAIK screenshots aren't mapped to any keyboard action ~ instead that function is mapped to the Custom control `Screenshot (file)` ....which I just checked on my xbox controller, and it does work as expected.

**Comment by midwan** [comment]
You can either assign it to a button as a custom control or use the default keyboard shortcut (I think it's End + SysRq).
I've only really tested the custom control, as my keyboard here doesn't have the SysReq key :)

**Comment by codewiz** [comment]
> You can either assign it to a button as a custom control or use the default keyboard shortcut (I think it's End + SysRq). I've only really tested the custom control, as my keyboard here doesn't have the SysReq key :)

Is it still possible to assign a screenshot key with the new UI? I couldn't figure out how.

(I can file a fresh bug if reopening this old one isn't good).

**Comment by midwan** [comment]
@codewiz I will add a dedicated screenshot control in the Misc panel with the next release.
