### ISSUE TITLE
Amiberry 5.3 mouse doesnt work

### ISSUE THREAD

**Issue by martingclark** [BlitterStudio/amiberry#1012]
Hi, ive been using amiberry in many tyoes of computers for a while but just tried it on pietpi, the version that comes with it built in, i cant install workbench from adf's as when i boot the install disk or any other for that matter the amigas mouse pointer wont even move, the right and left clicks works, scroll wheel works, but that is all, does anyone have a solution.

**Comment by midwan** [comment]
This is a known issue with the latest version of SDL2 on DietPi currently, see: https://github.com/BlitterStudio/amiberry/issues/995

**Comment by MichaIng** [comment]
@martingclark 
You can now reinstall it to apply the fix:
```sh
dietpi-software reinstall 108
```
