### ISSUE TITLE
Amiberry 5.3 and whdload_db empty lines bug

### ISSUE THREAD

**Issue by tomino1983** [BlitterStudio/amiberry#1013]
**Describe the bug**
I noticed that the hardware settings inside the whdload_db are randomly ignored by Amiberry as well as the custom controls.

In order to fix those settings for each ignored setting it is needed to add one empty line before the setting  so Amiberry is able to read it.

This happens with almost every game and every setting

Here is an example of my customizations:
 
        <hardware>
        PRIMARY_CONTROL=JOYSTICK
        PORT0=JOY
        PORT1=JOY
        CPU=68000
        CLOCK=7
        SCREEN_AUTOHEIGHT=FALSE
        SCREEN_HEIGHT=400
        SCREEN_WIDTH=720
        SCREEN_CENTERH=SMART

        SCREEN_CENTERV=SMART
        </hardware>
        <custom_controls>
        joyport1_amiberry_custom_none_leftshoulder=F1

        joyport1_amiberry_custom_none_rightstick=F2
        </custom_controls>"

As you can notice in order to have the settings "joyport1_amiberry_custom_none_rightstick=F2" and "SCREEN_CENTERV=SMART" correctly red and set in amiberry i had to add an empty line before them

**Expected behavior**
Amiberry/Whdload shouldn't have problem to read the whdload_db correctly without the empty lines

- OS: Pi4 Buster Latest retropi

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
@tomino1983 I'm afraid I can't recreate this exact behavior...
Did you edit the file on a WIndows machine? Perhaps it's a matter of line endings (Windows uses CR/LF, while Linux uses LF only). If that's the case, you could convert the line endings with a tool like Notepad++ and re-save it, to see if that helps.

I am investigating a reported issue with some cases where custom controls are not picked up as expected, but that's not the same as what you mentioned above. And it doesn't seem to matter if I add blank lines or not here, it still reads the basic settings correctly.

Perhaps you can give me more details, or upload your file here to test with? And mention which title you're testing this scenario with.

**Comment by midwan** [comment]
This is now fixed with the above commit in `master` - it will be part of the next binary release as well (5.4)
