### ISSUE TITLE
Audio options (stereo/mono) inside whdload_db

### ISSUE THREAD

**Issue by tomino1983** [BlitterStudio/amiberry#1016]
Hi all,

as per my understadning and testing, the hardware options inside the whdload_db don't consider the audio section of amimberry.

There are some games (I.E. HeroQuest) that need mono audio to correctly play the soundtrack, though it would be useful to set the audio output directly from th whdload_db.

Let me know your thoughs

Thank you

Tommaso

**Comment by nemo93** [comment]
@tomino1983 Hi! Thanks for reporting. First of all let's ensure we're talking about the same game here. I do have [Hero Quest](https://www.whdload.de/games/HeroQuest.html) in my testbed and it works just fine including audio. Are you talking about the same or Hero's Quest from Sierra which is the alternate name for Quest For Glory?

You mention "some" other games as well and I'd be interested if you could share some names. I didn't face a single sound issue thus far and I've done quite extensive testing with roughly ~750 games. I'm not enclined to add audio stuff in the file unless you help finding a good case :)

Thanks

**Comment by tomino1983** [comment]
Hi nemo93, you are right. I can' reproduce the issue anymore, maybe it was my fault on retropi.

THank you and sorry to waste your time

Tommaso
