### ISSUE TITLE
v5.4 missing macOS Apple silicon binaries

### ISSUE THREAD

**Issue by mibosshard** [BlitterStudio/amiberry#1017]
release v5.4 has no more binaries for macOS M1 / Apple silicon. is this intentional or just an oversight? thnx!

kind regards,
michael

**Comment by midwan** [comment]
It's not intentional, but as I don't have the hardware to build it myself, I'm relying on a member of the community to provide that one. Should be available today... :)

**Comment by midwan** [comment]
It's online now: https://github.com/BlitterStudio/amiberry/releases/tag/v5.4

**Comment by mibosshard** [comment]
nice! downloaded it already ;-) thnx a lot! have a nice day...
