### ISSUE TITLE
Save state image thumbnails not rendering correctly

### ISSUE THREAD

**Issue by celeritydesign** [BlitterStudio/amiberry#1018]
Save state images appear broken up into horizontal bands with space between them. This only seems to happen if auto-height is disabled. It’s as though the thumbnail code assumes the screen will be maximum vertical resolution, and if it’s not, it slices the image up to fill the extra space.

**To Reproduce**

1. Disable auto-height and choose a resolution that doesn’t fill the vertical height of the screen.

2. Save state

3. Go back into Save State screen and look at the slot you just saved. It will likely look like eight wide thumbnail strips, with black space between each stripe.

**Expected behavior**
The save state thumbnail should appear as a seamless image without gaps. Ideally it would match the aspect ratio chosen by the user.
Additionally, scanlines should not be shown in this thumbnail (see below)

**Screenshots**
Sorry, I don’t know how to grab a screenshot from Amiberry running on a RasPi (RetroPie)

- OS: Linux (RetroPie)

- Version
- Amiberry 5.3

**Additional context**
This isn’t a major bug by any means, but it would be useful to have clear thumbnails. For example, in a game like UFO: Enemy Unkmown, multiple save states are common and it would be good to see at a glance which battlescape save is which.

Even more minor still, is that if scanlines are enabled, they look terrible when scaled down to a Save State thumbnail.  If it’s possible, I would suggest disabling scanlines in memory prior to saving the thumbnail, so the thumbnail looks as clear as possible.

**Comment by midwan** [comment]
This is interesting, because I cannot recreate it on a quick test I made with Inviyya, using different screen width/height values, and Single/Double line mode. All savestates seemed OK, and the screenshots seemed to respect the actual dispalyed dimensions.

I didn't have a change to test this in RetroPie however, but I'll see if perhaps this only happens there (which would mean, the dispmanx-specific version of Amiberry).

**Comment by midwan** [comment]
Nope, I can't recreate that in RetroPie either I'm afraid.
Perhaps check if a specific option or combination of options is causing this for you?

**Comment by celeritydesign** [comment]
Apologies for the delay in responding, but I have more info now.

To replicate on RetroPie:

- backup /opt/retropie/emulators/amiberry/conf/amiberry.conf
- delete amiberry.conf
- load a WHDLoad game (I've chosen Deathbringer, as the intro animation is amusing)
- go into Display menu and enable Line mode = scanlines
- resume game
- go back into Amiberry menu and save state
- go back into Amiberry menu and view your previous saved state - it should be garbled like the below:
- 
![311431162_2383207931838545_8068552255459932266_n](https://user-images.githubusercontent.com/285563/195180472-a267a13b-f622-49ac-a10f-1403d8b45391.jpg)

Alternative way of replicating:

- backup /opt/retropie/emulators/amiberry/conf/amiberry.conf
- delete all lines in amiberry.conf, then add a single line: default_line_mode=2
- load a WHDLoad game
- go back into Amiberry menu and save state
- go back into Amiberry menu and view your previous saved state - it should be garbled as above.

Don't forget to restore your backed up amiberry.conf :-)

The above are easy ways to replicate this (on my system anyway), but I can confirm that simply having default_line_mode=2 in my much longer normal amiberry.conf causes the issue as well.

Hopefully that helps you replicate the problem.

**Comment by midwan** [comment]
@celeritydesign Thanks for the extra information.
So this is basically only an issue if you use Scanlines in the Line mode options, otherwise it seems to work as expected.

**Comment by celeritydesign** [comment]
Er, sort of :-) 
When I originally tested without wiping my config file, I managed to get "correct" thumblines with scanlines enabled - they just looked a bit ugly due to the way the image had been resized. I haven't managed to work out how I did that though.  In other words, there is a combination of scanlines plus certain screensizes or autoheight or something else that does resolve the problem.

My method of replicating above with a "clean" config file should hopefully work to show you the issue though.

**Comment by midwan** [comment]
@celeritydesign 
OK, thanks for the clarification. I'll follow those steps above, and try to narrow it down further. Once we find out the exact trigger for this, we can work on a solution as well.

**Comment by midwan** [comment]
The issue here wasn't saving the PNG, indeed you can see that the files under `screenshots` look correctly when opened elsewhere. But the problem was scaling the image to display it inside the box in the GUI. It seems the SDL2 function to do a quick (low-quality) scale produces interesting results, if the original image contains scanlines.

I've increased the size of the window there, which seems to improve the result of the scaling as well - and it looks better :)
I couldn't recreate the issue if I wasn't using Scalines, so all other scenarios should be OK.
