### ISSUE TITLE
[CDDA] not always playing

### ISSUE THREAD

**Issue by nemo93** [BlitterStudio/amiberry#1021]
**Describe the bug**

Audio issue with **Flink** on CD32 and **T-Zer0** on Amiga CD. I'll focus on Flink first as it's quite easy to reproduce. First sound issue is right on the Psygnosis logo then upon dying in-game. The SFX or CDDA tracks supposed to play sound like static. Also once you die and restart a level, the CDDA track stops from playing. This is also happening with T-Zer0 where restarting a level will prevent CDDA from playing. Thus far those are the only 2 games with such audio issues.

**To Reproduce**

1. Run Flink (CD32). I've "compressed" the _iso_ in `CHD`.
2. Wait for the Psygnosis logo there will be a strange sound.
3. In main menu CDDA will play fine.
4. Go to first level and die. A weird SFX can be heard and no CDDA on restarting the level.
5. Issue has been reproduced on Amiberry 5.4 and 5.3.

**Expected behavior**
SFX and CDDA to play fine all the time.

**Additional context**
I'm running 5.4 on Retropie 4.8 on Pi4. Buster / 32-bit / DMX. Everything (`.uae`, `.chd`, `.lha`) is therefore launched with the `--autoload` parameter.

**Comment by midwan** [comment]
@nemo93 
With the current Amiberry version, I cannot recreate all of the above.
I can hear the glitchy sound in the Psygnosis logo indeed, but other than that the audio seems to work fine, even if I die/restart/continue. 
Can you confirm, please?

**Comment by nemo93** [comment]
I'm afraid issue still persists here. Should I die once in Flink the CDDA will not resume upon restarting the level. As far as my testing went it's the only CD32 game impacted.

**Comment by midwan** [comment]
@nemo93 
I wonder if it's related to the CHD version you are using. I've tested this on a .cue/bin image, and I couldn't recreate the problem there. Do you have the possibility to also test with such an image perhaps?

**Comment by nemo93** [comment]
Same thing with either .bin/.cue or .iso/.cue. As we're focusing on Flink here I'm pursuing the discussion from #1024 hereafter.

* **gfx issues**: enabling (CPU) JIT will get rid of them. Thus far it's the only game which requires such setting to work as expected. Funnily enough it seems to fix also the weird sound on the Psygnosis logo too.
* **CDDA issue**: I tried various settings without success. CD Audio will stop from playing after your character dies. Interestingly the CDDA will still not play even after you reset Amiberry. In that case music from the main menu won't play too (as well as any other music). _In conclusion, CDDA can be heard only at first launch and until you lose a life_.

**Comment by midwan** [comment]
@nemo93 
I managed to recreate this, but _only_ in RetroPie.
Running it under Manjaro Linux, with the same Amiberry version, seems to work fine. Either this is a problem with 32-bit versions only, or older distros (like RetroPie) only. I'll need to test it on more scenarios to make sure.

**Comment by midwan** [comment]
@nemo93 
I've also tested this on RPI-OS 32-bit, and I can recreate it there also, which means it's probably an issue with the 32-bit versions in general.

**Comment by nemo93** [comment]
@midwan Thanks a lot. Commit c26f39f0c2e293b613b18a27dbf93ee10a688be3 definitely fixes the CD audio issue heard in Flink and T-Zer0. Nice job!
