### ISSUE TITLE
Amiberry left / right problem Dragonrise

### ISSUE THREAD

**Issue by GioMai81** [BlitterStudio/amiberry#1022]
Good morning everyone, I'm new to formu and I have a request.
This week I installed Retropie on Raspberry PI4 B which I plugged into a cabinet I built. I install Amiberry from source but when I use the Amiberry emulator with the left and right Dragonrise controllers they are reversed. The other controls work perfectly. With other emulators using Retroarch no problem. With the mini wifi usb keyboard everything works correctly.
I tried to insert the configuration file "DragonRise inc. Generic USB Joystick .cfg" in a folder that I entered in the configuration paths of the Amiberry to set the commands to my pleasure with the following code:

`input_device = "DragonRise inc.   Generic   USB  Joystick  "
input_driver = "udev"
input_up_axis = "-0"
input_down_axis = "+0"
input_left_axis = "-1"
input_right_axis = "+1"
input_state_slot_increase_axis = "+1"
input_state_slot_decrease_axis = "-1"
input_a_btn = "1"
input_b_btn = "0"
input_select_btn = "6"
input_start_btn = "7"
input_y_btn = "3"
input_x_btn = "2"
input_enable_hotkey_btn = "6"
input_l_btn = "3"
input_r_btn = "4"`

Even in this way, nothing has changed, left and right remain reversed.
I tried to swap the values of the left and right axes but nothing changes.
I tried to change the code as below but nothing has changed:

`input_l_y_minus_axis = "-0"
input_l_y_plus_axis = "+0"
input_l_x_minus_axis = "-1"
input_l_x_plus_axis = "+1"`

and

`input_l_y_minus_axis = "-0"
input_l_y_plus_axis = "+0"
input_l_x_minus_axis = "+1"
input_l_x_plus_axis = "11"`

To check if Amiberry read the file I set:

`input_l_y_minus_axis = "-1"
input_l_y_plus_axis = "+1"
input_l_x_minus_axis = "-0"
input_l_x_plus_axis = "+0"`

In fact, the commands have changed when the file is viewed by the emulator.
I have seen the Amiberry documentation but have not found the solution. Regarding the SDL2 configuration method, in my distribution there is no file "conf / gamecontrollerdb.txt" but only that of the modifiable configuration "controllers / gamecontrollerdb_user.txt" which I tried to change without success:

`03000000790000000600000010010000,DragonRise inc.   Generic   USB  Joystick,platform:Linux,a:b0,b:b1,x:b3,y:b2,start:b6,dpup:+a0,dpdown:-a0,dpleft:-a1,dpright:+a1,`

Also tried so

`03000000790000000600000010010000,DragonRise inc.   Generic   USB  Joystick,platform:Linux,a:b0,b:b1,x:b3,y:b2,start:b6,dpup:-a0,dpdown:+a0,dpleft:-a1,dpright:+a1,`

I tried for tests to disassemble and rotate the stick plate and reconfigure it when starting the emulationstation and retroarch and the problem was no longer on the right and left but it was on UP and DOWN.
So I downgraded to Amiberry version 3.3 (I have one installed on a Raspberry Pi3) and now everything works fine.
In the latest version of Amiberry there must be something that is causing problems with Dragonrise.

My system:
Raspberry Pi 4 Model B
RetroPie 4.8
Mini Keyboard and 2 controller Arcade zero delay usb encoder "Dragonrise"

**Comment by midwan** [comment]
If you are running RetroPie, then the RetroArch configs will take priority (if found) over the built-in controller mappings.
That means that any changes you want to make, should happen in the retroarch mapping file of your controller, which EmulationStation should have created for you on startup.

You don't need to create or move that file elsewhere, for Amiberry to pick it up. It should work with the default paths it's configured to use.

**Comment by GioMai81** [comment]
Thanks for the reply. Initially I did not make any changes or create any additional files. I used the path references of the retroarch files but it gave me the right / left inversion problem. At that point I did what I described above. With version 3.3 I use now leaving retroarch configurations it works fine in games but reverses in Amiberry menu.

**Comment by midwan** [comment]
@GioMai81 
So if I understand this right, the controller mapping works fine with v3.3 but not with v5.4?
If that's the case, could you please post your controller retroarch config file here, so we can try to recreate the problem?
Also please attach the retroarch.cfg file as well.

**Comment by GioMai81** [comment]
With 3.3 it works fine in the game but in the Amiberri menu they are reversed. In the zip file I put the controller configuration file and retroarch.cfg

**Comment by midwan** [comment]
@GioMai81
Can you please enable logging in Amiberry (in the Paths panel, enable the checkbox, then close/start Amiberry again) and provide me with the logfile generated? It would be useful to have that from both 3.3 and 5.4 if possible.
Note that due to permissions in RetroPie, you will either need to make the emulator folder owned by the user or provide a different path for the logfile to be saved. Currently `/opt/retropie/emulators/amiberry` is owned by `root`, so the user `pi` who's running Amiberry will have no rights to create the logfile.

**Comment by midwan** [comment]
@GioMai81 disregard the above request please. I've located the source of the problem, and will push a fix shortly.

**Comment by GioMai81** [comment]
Fantastic! Thank you!
