### ISSUE TITLE
[Feature] Option to remap "Untrap = middle button"

### ISSUE THREAD

**Issue by EMPI-PL** [BlitterStudio/amiberry#1023]
Currently there's an option to untrap the mouse by clicking middle mouse button. This works fine and there's absolutely no problem with this function as long as you actually have "middle button" on your mouse **which is not the case for tank mouse**.

My case is the one which blocks me from using untrap function. If you own and use The A500Mini optical mouse which is a replica of original Commodore's Tank Mouse you'll have just 2-button mouse. Same goes with original Tank Mouse used with some DB9-USB converter.

**Proposed solution**
Add an option to the "right pane" of **Miscellaneous** section to remap untrap function with a keyboard's shortcut combination.
It would be great to potentially have option to use i.e. Shift+Ctrl+_desired key_ or any other.

**Comment by midwan** [comment]
This is already implemented, there's the alternative of using Alt-Tab to free control (the option is also available in the Misc panel of the GUI, so it needs to be enabled first). At least, in the recent versions of Amiberry, I don't remember if it was there on 3.3 which the A500-Mini uses
