### ISSUE TITLE
[CD32] gfx issues

### ISSUE THREAD

**Issue by nemo93** [BlitterStudio/amiberry#1024]
**Describe the bug**

While testing CD32 games further I've hit several gfx issues with various games. I do have only a handful of CD32 games at hands hence I can't test the whole collection. It's likely other games than noted below suffer from similar issues.

* ~~Chaos Engine CD32 (black screen from start yet audio plays fine)~~
* Flink (some gfx issues here and there while in-game)
* Ultimate Body Blows (title on main menu garbled)
* Pinball Illusions (title on main menu garbled)

**To Reproduce**

1. Run the games indicated above.
2. See errors

**Additional context**
I'm running 5.4 on Retropie 4.8 on Pi4. Buster / 32-bit / DMX. Everything (.uae, .chd, .lha) is therefore launched with the --autoload parameter.

**Comment by celeritydesign** [comment]
What gfx issues are you seeing on Flink? The only reason I ask is that the Amiga version has a weird status window at the top (from memory) that looked broken to me, but that’s how it shipped. Essentially one of the background bitplanes shows through the status window, but the others don’t, so you get a disjointed clipping effect.  The Megadrive version doesn’t have the same issue.

**Comment by nemo93** [comment]
> What gfx issues are you seeing on Flink?

Thanks for your input. There are randomly appearing "squares of static" in the playfield (sometimes on enemy sprites). Nothing weird with GUI or status bar.

**Comment by midwan** [comment]
The Chaos Engine issue started after v5.1, and it's because I changed the default config for CD32 titles to use 8MB Fast. I guess it doesn't like that. Using a "normal" CD32 model instead, shows no problems. We'd have to change the `autoload` mechanism to use the normal CD32 config instead of the new 8MB Fast version, to fix it.

The others are different cases and not related to the above however.

**Comment by midwan** [comment]
@nemo93 
With the commit above, it seems that all the games mentioned above (except Chaos Engine) now work as expected. At least I didn't notice any issues in my tests :)
Can you confirm if that's the case for you also, and if so, we can close this case?

I'll handle the Chaos Engine issue separately.

**Comment by midwan** [comment]
Hm, I'm definitely not seeing those artifacts here. I think Flink might be a special case, so let's look at that one separately from the rest?
