### ISSUE TITLE
Amiberry on Pi OS Lite on Pi 3

### ISSUE THREAD

**Issue by cannyboy** [BlitterStudio/amiberry#1025]
**Describe the bug**
Amiberry fails to start on Pi OS Lite on Pi 3.

**To Reproduce**
Installed Raspberry Pi OS Lite (32 bit, 2022-09-22)

ssh-ed into pi from my mac, then:
```
sudo apt update
sudo apt upgrade
sudo apt install libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-image-2.0-0 flac mpg123 libmpeg2-4
wget https://github.com/BlitterStudio/amiberry/releases/download/v5.4/amiberry-v5.4-rpi3-sdl2-32bit-debian.zip
unzip amiberry-v5.4-rpi3-sdl2-32bit-debian.zip
rm amiberry-v5.4-rpi3-sdl2-32bit-debian.zip
sudo reboot

./amiberry

MESA-LOADER: failed to open vc4: /usr/lib/dri/vc4_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: vc4
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast driver
Segmentation fault
```

Do I need to build from source, or should I use an older version of Amiberry?

**Comment by solskogen** [comment]
You'll need to install a newer SDL than the one that are in Raspberry Pi
OS. Unless you know how, I would recommend to install Xorg.

man. 17. okt. 2022, 12:02 skrev cannyboy ***@***.***>:

**Comment by cannyboy** [comment]
OK, for the record, I did as suggested:

`sudo apt install xserver-xorg -y`

... and it appears to work. Thanks.

But doesn't the apt install line above install a newer SDL?

` sudo apt install libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-image-2.0-0 flac mpg123 libmpeg2-4`

**Comment by midwan** [comment]
@cannyboy 
It will install the latest version available _on the distro's repository_ - unfortunately, the RPI-OS one is a bit behind in the library updates, and does not include a version that allows console-based SDL2 graphics. Hence, either you can install a newer SDL2 version yourself, or just use X11 which is easier.
