### ISSUE TITLE
Amiga Diskdrive Sounds to separate output device

### ISSUE THREAD

**Issue by kadibamler** [BlitterStudio/amiberry#1027]
Can you make amiberry to rout the diskette drive emulation sounds to another sound card?

The purpose is to have the Gaming sounds coming from the HDMI Screen or TV, but the noise of the emulated Diskdrive  coming out of the computer case.

I want to put an raspberry into an Amiga500 Case to build my own TheA500 Maxi and would love if the diskette Drive would produce virtual noise from within the Amiga.

**Comment by midwan** [comment]
Although this would be possible, the amount of work required and the subsequent differences from the upstream WinUAE sources, would cause more trouble than it's worth.
I'm afraid I don't see this as a good investment of my time, but if anyone else would like to implement it, they are welcome to it!

**Comment by kadibamler** [comment]
Ok, thanks for evaluating my request.
