### ISSUE TITLE
How to setup Drawbridge drive

### ISSUE THREAD

**Issue by vaccinemedia** [BlitterStudio/amiberry#1030]
**Describe the bug**
I'm trying to setup a Robert Smith Drawbridge drive

**To Reproduce**
Add the drive via USB

**Expected behaviour**
I'm not sure as there is no documentation but after booting an A1200 config with a HD to boot with 3.2 installed nothing happens when I insert a disk.

**Desktop (please complete the following information):**
- OS: RetroPie

**Comment by vaccinemedia** [comment]
OK I can now see how to do this (facepalm) after watching Robert Smith's video on how to set up WinUAE but I think that this needs some documentation at least on the main readme on how to do this as it was not 100% obvious that when on the drives setup that in the options for the floppy drive that "FB xxx" referred to the various "Floppy Bridge" options which you can select from. I didn't have a clue that FB referred to "Floppy Bridge" (and I know now that it seems really obvious after watching the WinUAE video that it does).

Also if in the main Readme it tells the end user what the 4 options actually mean from a performance perspective that would also be awesome i.e. which one should be selected by default or which one should be selected for speed / accuracy etc....

It just needs some documentation that's all as the options were originally staring at me and yet my brain never made the leap from FB to Floppy Bridge for some reason and I assumed it was referring to a different controller I had never heard of ;)

**Comment by vaccinemedia** [comment]
BTW one more thing and that's I'm seriously impressed on how well it works with my Floppy Bridge drive. The board fits nicely into my slim line drive as per Rob's instructions and works really well so hats off to everyone involved in making this happen! I finally have a vary compact version of my old Amiga 1200 which can read old backups from 1995 and run at over 30x the speed of an Amiga 4000 :)

**Comment by midwan** [comment]
@vaccinemedia 
It's true, the documentation should be improved. :)
Don't forget there's also the built-in Help, accessible from the GUI by using the relevant button.
