### ISSUE TITLE
GFX Glitches

### ISSUE THREAD

**Issue by nemo93** [BlitterStudio/amiberry#1033]
**Describe the bug**
Some games do present some graphical artifacts either in menu or in-game. This is 100% reproductible. Currently the following packages are impacted:

* **PinkPanther_v1.0_0236** (does run fine on FS-uae)
* **PuttySquad_v1.3_AGA** (does run fine on FS-uae)
* **SurfNinjas_v1.0_AGA_1291** (does **_not_** run fine on FS-uae)
* **WWFEuropeanRampageTour_v1.1_1298** (does **_not_** run fine on FS-uae)
* **Zool2_v1.0_AGA_0415** (does run fine on FS-uae)

**To Reproduce**

1. Simply run the aforementioned games.
2. Surf Ninjas: you have to go to the far left screen (beach) and get the bat.
3. WWF European Rampage Tour: glitches can be seen only in menus
4. Zool 2: as soon as you enter 1st stage (known bug)

**Screenshots**

![PinkPanther_v1.0_0236](https://user-images.githubusercontent.com/8100500/204258393-bb656091-02e5-41c1-b9af-a7f4803273e2.png)
![SurfNinjas_v1 0_AGA_1291](https://user-images.githubusercontent.com/8100500/204258406-be4ada55-2f70-42dd-9f2a-f75367a8b6ef.png)
![WWFEuropeanRampageTour_v1 1_1298](https://user-images.githubusercontent.com/8100500/204258413-458d2abc-24d0-4ef2-bb56-b751b4a8f6a3.png)
![Zool2_v1 0_AGA_0415](https://user-images.githubusercontent.com/8100500/204258420-8137ad95-37cc-471b-b25c-3c9911295711.png)

**Additional context**
I'm running 5.5 (latest main) with Retropie 4.8 on Pi4. Buster / 32-bit / DMX. Everything (`.uae`, `.chd`, `.lha`) is therefore launched with the `--autoload` parameter.

As far as memory goes, Zool 2 worked in 3.3 yet I'm pretty sure the others never worked properly.

**Comment by midwan** [comment]
@nemo93 
Do these still occur after the latest updates?
There was a rollback of the CIA rewrite changes, since those caused several bugs.

**Comment by nemo93** [comment]
Yes these issues remain on latest. For all games also not working on FSUAE I suspect an issue with packages themselves. Yet for Pink Panther and Zool2 it should be with Amiberry (I recall you told me issue was expected for Zool2?). 

I can merge this ticket with #958 if you'd like? Anyhow keeping track of those issues would be nice as it would prevent me to open a similar one in the future ;-)

**Comment by midwan** [comment]
@nemo93 
PinkPanther seems to work fine if Cycle-Exact is used

**Comment by midwan** [comment]
@nemo93 
Zool2 AGA works fine in `dev`, which means it's a bug in one of the areas changed between `master` and `dev`. Currently, those are: blitter, custom chipset, drawing (we exclude CIA). Not sure if that will be fixed before the upcoming release of 5.5, however.

**Comment by nemo93** [comment]
PinkPanther does indeed work fine with Cycle Exact 🤦‍♂️ I'll fix that. No rush to fix Zool2 given how stable and heavily-tested 5.5 has been thus far. I'd say let's keep it for 5.6 or 6.0 :-) Thanks for the assistance as always.

**Comment by nemo93** [comment]
With latest commits (in fact since 5.5) PinkPanther main screen bug is back. I've re-edited the OP accordingly.

**Comment by nemo93** [comment]
Pinball Mania package has been updated and this fixed the main menu bug. Removed from OP.

**Comment by nemo93** [comment]
Adding Putty Squad to OP (see #1053 for reference).

**Comment by midwan** [comment]
From the games mentioned above, only WWF still seems to have gfx artifacts after the commit above. The rest are all fixed.
Pink Panther no longer requires Cycle Exact mode to work properly, either - @nemo93 you can remove that from the XML.

**Comment by nemo93** [comment]
Done. Thanks. WWF should be a WHD issue.
