### ISSUE TITLE
Amiberry 5.4 binary for macOS M1 will not start

### ISSUE THREAD

**Issue by intrepidsilence** [BlitterStudio/amiberry#1035]
**Describe the bug**
Provided Amiberry 5.4 binary for macOS M1 will not start on M1Max. Yes it has permission to run (xattr).

**To Reproduce**
1. Download Amiberry binary from GitHub for M1 macOS
2. Give .app Full Disk Access in Settings
3. Right click .app and select Open
4. Select Open Anyway in requestor
5. App dies
6. Try to run again, dies again

**Expected behavior**
App should start

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.0.1

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
As I mentioned in #1034 also, I don't have the hardware to test or debug this, unfortunately.

@solskogen do you have any time to look into this perhaps?

**Comment by solskogen** [comment]
How did you download the app? For some strange reason, if you download the app using a browser it won't start. You have to use wget or some other means. I've just tried 5.4 on my Mac mini M1 on Ventura, and it starts up fine. 
You *could* try compiling amiberry yourself, and see if that helps.

**Comment by intrepidsilence** [comment]
If you look over at #1034 you will see that I did exactly that and it is running when I compile it. I will try to download via wget as well and see if it works. If this is expected it should probably be listed as a known issue with instructions in the README.

**Comment by intrepidsilence** [comment]
The FAQ talks about running xattr to fix the issue, which did not work for me. The unsigned-code problem can also be bypassed by right-clicking the app and selecting Open, which also did not work.

**Comment by solskogen** [comment]
Hmf, that used to work. Perhaps the wget workaround doesn't work either?

**Comment by intrepidsilence** [comment]
Not, sure. Will try later and update.

**Comment by intrepidsilence** [comment]
The wget method does not work either.

**Comment by erikbernsen** [comment]
I have an M1 and it works. What do you mean the app dies? Any message?

**Comment by solskogen** [comment]
Can you try with the latest version?

**Comment by intrepidsilence** [comment]
5.5 worked fine. 5.5.1 not yet available.

**Comment by solskogen** [comment]
5.5.1 only contains changes for RetroPie, nothing else. I think we can close this one. Agree?

**Comment by intrepidsilence** [comment]
Yes, and thanks for getting this solved.
