### ISSUE TITLE
Cannot run on Debian 11, due to very "high" GLIBC version..

### ISSUE THREAD

**Issue by tbone2k-git** [BlitterStudio/amiberry#1039]
Hi folks! o)

I am some kind of dev, but my linux experience is limited. I tried running the Ubuntu binaries on my current version of Debian 11 bullseye (stable) and it seems to be not possible, because required libraries are too old? Since Debian 11 is the current release, I kind of wonder if there is something we - I mean you o) - could do about it? o) Choosing a different GLIBC target or something?

```
[~/amiberry] 21:16:58 #root:
>./amiberry 
./amiberry: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found (required by ./amiberry)
./amiberry: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by ./amiberry)
./amiberry: /lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.29' not found (required by ./amiberry)
./amiberry: /lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.30' not found (required by ./amiberry)

[~/amiberry] 21:17:12 #root:
>dpkg -l | grep -i "gnu c library"
ii  libc-bin                          2.31-13+deb11u5                 amd64        GNU C Library: Binaries
ii  libc-dev-bin                      2.31-13+deb11u5                 amd64        GNU C Library: Development binaries
ii  libc-l10n                         2.31-13+deb11u5                 all          GNU C Library: localization files
ii  libc6:amd64                       2.31-13+deb11u5                 amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                   2.31-13+deb11u5                 amd64        GNU C Library: Development Libraries and Header Files
ii  locales                           2.31-13+deb11u5                 all          GNU C Library: National Language (locale) data [support]
```

I also tried to compile for myself, but as always when I try to compile, it won't work. o(
The last time I used C compiler was, when I had to insert floppy disks for the includes, so it's been a while. o)
```
[~/amiberry] 21:42:42 #root:
>make PLATFORM=x86-64
make -C external/libguisan
make[1]: Entering directory '/root/amiberry/external/libguisan'
g++  -pipe -Wno-shift-overflow -Wno-narrowing -O3  -std=gnu++17 -MD -MT guisan -MF guisan -I/usr/include/SDL2 -D_REENTRANT -Iexternal/libguisan/include -Isrc -Isrc/osdep -Isrc/threaddep -Isrc/include -Isrc/archivers -Isrc/floppybridge -DAMIBERRY -D_FILE_OFFSET_BITS=64 -DUSE_RENDER_THREAD -I./include -I/usr/include/SDL2 -D_REENTRANT -MD -MT src/actionevent.o -MF src/actionevent.d  -c -o src/actionevent.o src/actionevent.cpp
make[1]: g++: No such file or directory
make[1]: *** [<builtin>: src/actionevent.o] Error 127
make[1]: Leaving directory '/root/amiberry/external/libguisan'
make: *** [Makefile:659: guisan] Error 2
```

Thank you! o)

**Comment by midwan** [comment]
The pre-built binary for x86-64 is compiled on `Ubuntu:latest`, so it might have a different version of GLIBC (I didn't check).
However, it should be easy enough to compile it yourself, if you install the requirements (check the readme on this repo, it includes the exact commands to get and install them).

I am working on a new `flatpak` version, to eliminate all these pains and be able to get updates automatically through there as well. I just got it working today, but it will need some more work and refinement, before it's published to Flathub eventually. After that, you'll be able to install it on your distro of choice through the "App store".

**Comment by solskogen** [comment]
You'll have to install gcc and g++ with apt. And read the README.md in docs/ for the additional dependencies to install.

**Comment by tbone2k-git** [comment]
@midwan
For people with limited linux/compiling experience, maybe you can still set a lower GLIBC target somehow? It would increase usefulness of already provided binaries for download and there might be more people out there who like downloading binaries and be ready to go? o) I work on 2GB internal SSD thin clients, disk space is a thing also when it comes to downloading a lot of dependencies and compiler packages (in my linux thin clients at least.. o).

Long story short, I was successful now! o)

I got confused with the multiple thin clients I have here, one had all the dev-dependencies installed, the other had g++ and gcc.. o) I understand the output of "make" now as well, it complained about "g++" not being there.. and not "g++" complaining about some unmet dependency/file.

So, I got it compiled and it runs.. thank you, awesome advice from you guys! o)
Thanks again, have a nice weekend everyone! o)

ps: Of course you run into new problems (USB Gamepad works fine in Amiberry GUI, but D-Pad not working in-game, I tried remapping and all.. nope, but that's offtopic here.

**Comment by midwan** [comment]
I'll change the Dockerfile to use a Debian image for building, instead of Ubuntu. This will also bring it in-sync with the ARM builds, since those are built on Debian as well.

This means that the next release will have binaries generated on Debian, for all 3 platforms (x86-64, ARM, ARM64).

**Comment by tbone2k-git** [comment]
Awesome, thank you! o)
