### ISSUE TITLE
Compiling Amiberry with latest master, cannot show setup menu

### ISSUE THREAD

**Issue by FabrizioRadica** [BlitterStudio/amiberry#1040]
Hi, Compiling latest master on DietPi 6.33 (make clean / make -j4 platform=rpi4), no longer runs the setup menu.
When press I F12, back on dietpi login.
Boot and emulations works fine.

**Comment by midwan** [comment]
Sounds like something is crashing when trying to open the GUI.
Please try compiling a DEBUG version, and run it from the console. If it crashes again, it should show some more details about where the crash happened exactly, which will hopefully give us more to work on.

You can compile a debug version by either editing the Makefile and uncommenting the `#DEBUG=1` line, or add `-DDEBUG` in the `make` command options (e.g. `make -j4 PLATFORM=rpi4 -DDEBUG`).

**Comment by FabrizioRadica** [comment]
HI, I've write in console: 

sudo ./amiberry 

and it return:

error: XDG_RUNTIME_DIR not set in the enviroment.
Unable to create window: Could not initialize EGL
(SDL restoring keyboard)

**Comment by midwan** [comment]
It seems like SDL2 fails to open a window. This could happen for a few different reasons...

DietPi has Amiberry available through its own package manager, why did you not use that?

**Comment by FabrizioRadica** [comment]
Upgrading to dietpi from 6.33 to v8.12, Amiberry GUI it works fine. 
so you can close this thread.

P.s but we have another problem and i will show you on another thread.
