### ISSUE TITLE
USB Gamepad Bug

### ISSUE THREAD

**Issue by JamesKoguaro** [BlitterStudio/amiberry#1041]
When using an USB gamepad I experience a strange behaviour:
Pushing to the right i get the result of right and up
Pushing down the result is down ad left
I found this bug in PiMiga 4
I tried to rebuild myself the executable but the bug remains.
I coud track down the misbehaviour in src/inputdevice.cpp
I repleced the lines from 5232 to 5256

                       joydir[joy] = 0;
                        if (left) {
                                if (!allowoppositestick) {
                                        joydir[joy] &= ~DIR_RIGHT;
                                }
                                joydir[joy] |= DIR_LEFT;
                        }
                        if (right) {
                                if (!allowoppositestick) {
                                        joydir[joy] &= ~DIR_LEFT;
                                }
                                joydir[joy] |= DIR_RIGHT;
                        }
                        if (top) {
                                if (!allowoppositestick) {
                                        joydir[joy] &= ~DIR_DOWN;
                                }
                                joydir[joy] |= DIR_UP;
                        }
                        if (bot) {
                                if (!allowoppositestick) {
                                        joydir[joy] &= ~DIR_UP;
                                }
                                joydir[joy] |= DIR_DOWN;
                        }

with the following 

                       if (ie->data == 3 ) { /* event X axe */
                                if (state > 0) {
                                        joydir[joy] |= DIR_RIGHT;
                                        joydir[joy] &= ~DIR_LEFT;
                                }
                                if (state < 0) {
                                        joydir[joy] |= DIR_LEFT;
                                        joydir[joy] &= ~DIR_RIGHT;
                                }
                                if (state == 0) {
                                        joydir[joy] &= ~DIR_RIGHT;
                                        joydir[joy] &= ~DIR_LEFT;
                                }
                        }
                        if (ie->data == 12 ) { /* event Y axe */
                                if (state > 0) {
                                        joydir[joy] |= DIR_DOWN;
                                        joydir[joy] &= ~DIR_UP;
                                }
                                if (state < 0) {
                                        joydir[joy] |= DIR_UP;
                                        joydir[joy] &= ~DIR_DOWN;
                                }
                                if (state == 0) {
                                        joydir[joy] &= ~DIR_UP;
                                        joydir[joy] &= ~DIR_DOWN;
                                }
                        }

With this little change in the code the USB pad in now working correctly.
Hope this can be useful.
Thankyou for the great work.

**Comment by midwan** [comment]
@JamesKoguaro 
Thanks for the contribution. I haven't been able to recreate this problem, however (and neither has anyone else reported something similar). Considering this piece of code is also identical in WinUAE, I suspect something strange might be going on with your controller.

Did you try another controller as well?
Could you try the same controller on WinUAE? Does it happen there?

I'd like to know more about the conditions this problem occurred in, before making any changes to the code.

Or maybe you could report this issue upstream to Toni as well, to see if he has any thoughts.

**Comment by psychorat** [comment]
Hello
I have the same problem with my "Super Joybox 7". Its a Gameport to USB Adapter (indetified as "WiseGroup USB") using it with a Pacman PC Joystick.
I Tried to map the keys but it didnt work and since my "Zero latency arcade USB encoder" (indetified as "DragonRise Inc. Generic USB") works fine I didn't bother too much.
Both devices work fine on Winuae, maybe its the joystick driver or something.
Can't find it right now for further testing (my cat look suspicious) but i will as soon as i can.

**Comment by psychorat** [comment]
In my case the behavior is a bit different

Going from RIGHT to TOP-RIGHT only goes UP.
Going from UP to TOP-RIGHT it goes TOP-RIGHT as it should.

Going from BOTTOM to BOTTOM-LEFT only goes LEFT
Going from LEFT to BOTTOM-LEFT it goes BOTTOM-LEFT as it should

If one direction is triggered at a time (UP or DOWN or LEFT or RIGHT) it works OK

PS. The cat is innocent :)

**Comment by midwan** [comment]
@psychorat 
Thanks, I'll try to recreate this with a few different controllers, to see if I can get the same behaviour.

**Comment by midwan** [comment]
I have an updated version in a separate branch, which might help solve this also. I can't say for sure, since I cannot recreate the problem with any of the controllers I have here.

Could someone test compiling the `1041-usb-gamepad-bug` branch and see if it solves this issue as well?

Other things to expect in that version:
- Significantly reduced input latency
- Probably less CPU usage as well

**Comment by psychorat** [comment]
Hello Midwan
I tested this branch on dietpi debian and the joystick works great now for me :D 
The version was 5.5.2.beta.   I cloned the git with the command  git clone --branch 1041-usb-gamepad-bug http//.....
Thank you for your effort!

**Comment by midwan** [comment]
@psychorat 
Thanks for confirming!
I'll need to test this solution in a few more environments (e.g. RetroArch based, which use their own mapping) to verify that everything works properly, then I can merge it and close this issue if all goes well.
