### ISSUE TITLE
Amiga CD32 language setting is not saved since amiberry version 5.5

### ISSUE THREAD

**Issue by Retro1968** [BlitterStudio/amiberry#1044]
Raspberry Pi 4 with RetroPie 4.8.2 running amiberry 5.5 (compiled with: make -j4 PLATFORM=rpi4-sdl2)

Hello,
I use Amiga CD32 image files under RetroPie 4.8.2 under the "Amiga CD32" tab.

So far I have been able to set the language setting to "German" without any problems. The language setting was then saved in the "cd32.nvr" file in the "/opt/retropie/emulators/amiberry/data/" folder.

Before that, I set the appropriate write permissions with this command:
sudo chown -R pi:pi /opt/retropie/emulators/amiberry/data/

Since amiberry version 5.5, neither a new file "cd32.nvr" is created in this folder nor an existing one (backup copy of the file) is written, so that every setting in German language is not saved.

Why?!? The read-write rights are set!

Best regards and a happy new year 2023!
Retro1968

**Comment by midwan** [comment]
@Retro1968 
With 5.5, there's a separate path for the NVRAM files (which CD32 and CDTV use), configurable in the Paths panel of the GUI. You could still set that to `data` if you want, or use a separate path for it (just make sure the folder exists, and you can write into it).

**Comment by nemo93** [comment]
Amiberry's script for Retropie will be updated to reflect this change (as soon as final 5.5 release will land). The 'nvram' files will be moved under a `nvram` dir created in the `amiberry` folder (next to `conf`, `savestates`, `whdboot`, etc). Any previously created `cd32.nvr` file will be moved under the new directory.

**Comment by Retro1968** [comment]
Thanks for the hints.
After I created the "nvram" folder and set read/write permissions, it worked again. :)

sudo mkdir /opt/retropie/emulators/amiberry/nvram/

sudo chown -R pi:pi /opt/retropie/emulators/amiberry/nvram/
