### ISSUE TITLE
No game is starting anymore unless i have previously saved an .uae configuration game specific

### ISSUE THREAD

**Issue by tomino1983** [BlitterStudio/amiberry#1046]
Hi all,

first of all i've been playing all my amiga .lha games perfectly before the last update. Now if the game i'm lunching has got a .uae profile previously saved by me (beacuse of spefic button mappings), it starts properly, otherwise i see a black screen with mouse cursor on top left corner.
I've tried to rename the uae files to confirm this behaviour and it actually is as i wrote.
I've tried to recreate a default.uae profile thinking that amiberry executable looks for it as it starts but it haven't fixed the issue.

amiberry version i 5.5.1 (latest available)

Could you please help me?

Thank you

Tommaso

**Comment by midwan** [comment]
Please provide more details:
- Which device?
- Which distro (and version if possible)?
- 32-bit or 64-bit installation?
- Please attach current `conf/amiberry.conf` file
- Please attach one example `.uae` config that you used, along with the game title you used it for (just the filename is enough, no need to attach the actual game here)

The `default.uae` file is not needed unless you want it of course. If found, it's loaded automatically, if it's not found then the default settings will apply. If you're running `.lha` games, then normally the WHDLoad booter will change the settings anyway, according to the XML (assuming the game is recognized).

**Comment by tomino1983** [comment]
Hi Dimtry,
I'm sorry I figured it out. The issue is related to the default value of
the launching parameter --model of the CLI.
If i use the launching string explicitly declaring --model A1200
everything start properly. Otherwise i land on the issue, so it seems to me
that the default --model value isn't honored unless you declare it.


   - Which device? RPI4 4GB
   - Which distro (and version if possible)? Distributor ID: Raspbian
   Description:    Raspbian GNU/Linux 10 (buster)
   Release:        10
   Codename:       buster
   - 32-bit or 64-bit installation? 32 bit
   - Please attach current conf/amiberry.conf file? Attached
   - Please attach one example .uae config that you used, along with the
   game title you used it for (just the filename is enough, no need to attach
   the actual game here)? Attached


Thank you

Tommaso


Il sab 21 gen 2023, 16:35 Dimitris Panokostas ***@***.***> ha
scritto:

**Comment by midwan** [comment]
@tomino1983 
I'm glad you figured out what was wrong.
FYI, `--model` does not have a default value, it needs a model specified after it (e.g. `A500, A1200, CD32`)
