### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by quantum8** [BlitterStudio/amiberry#1049]
On MacOS Big sur, intel, when running in a window I can resize the emulator to get the size I want.

However, when pressing F12 to bring the settings window up, upon closing the settings page the emulator window reverts to the size of the settings window and I have to resize it again. No settings need to be changed for this to occur.

The emulator needs to remember the size of the window when no display settings have been changed.

**Comment by midwan** [comment]
This is now implemented in both active branches (`master` and `preview`).

The stored X/Y and Width/Height values of the window will now be re-used when exiting the GUI, if using Windowed mode. To reset those values to their defaults, you can modify any of the Width/Height or Autocrop values in the GUI Display panel.
