### ISSUE TITLE
A500 mini OS Port

### ISSUE THREAD

**Issue by symbios24** [BlitterStudio/amiberry#1050]
Hello there

Is it possible to make a one time/version of amiberry with the exact graphical interface  and the functions of the A500 mini for the Raspberry Pi ??

And even to has the old amiberry 3.3 the a500 mini has.to be an exact port of it,for the people (like me) that dont have the money to purchase it??

Thanks a lot

**Comment by midwan** [comment]
@symbios24 
I'm not sure what you mean exactly here...
There is already a better version available, it's the latest release of Amiberry (currently v5.5.1). :)

If you mean the front-end that RetroGames have built, that is not open source I'm afraid (and I'm not involved in it). But there are other front-ends available (e.g. RetroPie uses EmulationStation) and a custom one could also be built. But that is outside the scope of Amiberry itself, it would be a different project.
