### ISSUE TITLE
Latest dev will not compile executable

### ISSUE THREAD

**Issue by Lex15** [BlitterStudio/amiberry#1052]
Latest dev will not build amiberry executable. Using up to date RpiOS(32bit).

> src/threaddep/threading.cpp: In function ‘void atomic_and(volatile uae_atomic*, uae_u32)’:
src/threaddep/threading.cpp:85:29: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
   85 |  return __sync_and_and_fetch(p, v);
      |         ~~~~~~~~~~~~~~~~~~~~^~~~~~
src/threaddep/threading.cpp: In function ‘void atomic_or(volatile uae_atomic*, uae_u32)’:
src/threaddep/threading.cpp:93:28: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
   93 |  return __sync_or_and_fetch(p, v);
      |         ~~~~~~~~~~~~~~~~~~~^~~~~~
make: *** [<builtin>: src/threaddep/threading.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by solskogen** [comment]
I've got no problem compiling it. On 32bit you must use `make PLATFORM=rpi4-sdl2`

**Comment by solskogen** [comment]
Oh, sorry. @midwan fixed it before I tried.
