### ISSUE TITLE
System Freezes and Black Screen When Attempting WHDLoad

### ISSUE THREAD

**Issue by JSchul72** [BlitterStudio/amiberry#1054]
Pi 4 32 4 gb
Retropie v4.8.2
---Launching Amiberry in 1360x768 video mode w/same selected to load ROMs
---All recommended kickstarter ROMs in BIOS/amiga folder
---Attempting to launch .lha files located in the Retropie/roms/amiga folder
---Amiberry configured for model 1200 with 4Mb fast RAM
---KS ROM 3.1 (A1200) selected as main ROM file
----Removed Amiberry and re-installed from source last night (1 Feb)

Under 'Quickstart' I select an .lha file from the twelve or so I have in the /home/pi/RetroPie/roms/amiga folder under WHDLoad auto-config and click 'Start' and I get a black screen with the cursor frozen in place. F12 does not exit from this, nor does the action button + start combination that typically brings me out of a ROM back to the main Retropie menu. The only way to stop it that I've found is to cut off the power to the Pi and turn it back on. I'm not able to provide any sort of log to ID an error because of this.

I know the configuration can vary from one game to the next to get them to run. I've had mixed success getting games to load from single disks but I have gotten a few to run. This black screen and freeze happens consistently with every WHDload + .lha I've tried, have had no success getting a single one of them to work. 

Attempting to launch the .lhas directly from the main Retropie menu gets the same result: black screen and entire system frozen.

Is there another way I should be configuring or trying to load the .lha games? Any help would be appreciated, thank you.

**Comment by nemo93** [comment]
@JSchul72 I do have the same config as yours (software/hardware). It works nicely here hence something off with your setup. I'm a bit surprised to see you stating _1200 with 4Mb fast RAM_ as it's 8Mb of Fast by default now. Also unsure about the 1360x768 video mode you mentioned.

I'd really recommend you run your games straight from EmulationStation/frontend instead of the 'Quickstart' way you described. That way Retropie will set everything up the best way.

You sure you installed the default from Retropie Setup? Do you have any other `.uae` or file(s) in the `$config/amiga/conf` directory? What game(s) do you try running please? Also do you have any keyboard/gamepad attached to your Pi and if so which model? Last which [KickStart roms](https://github.com/BlitterStudio/amiberry/wiki/Kickstart-ROMs-(BIOS)) are you using exactly (name + CRC)?

**Comment by JSchul72** [comment]
I've installed what, as far as I know, is the default version of Amiberry
from the Retropie setup, from source.

I've tried launching the games straight from the front-end and I have
exactly the same problem---screen goes black, mouse cursor error stuck, no
response from any attempt to stop the ROM from running.

Here's a screenshot of the games I have:

[image: image.png]
Most of these I have tried either from within Amiberry or by launching
directly from the Emulation Station menu---again, same problem every time:
black screen and frozen system.

My controller is a wireless USB XBox 360 clone. I have this and a USB
wireless keyboard and mouse attached. These work with every other emulator
I have in Emulation Station except maybe C64---I know the translation from
console to computer controller is not always perfect.

Here's a screenshot of the the kickstarters in their directory:
[image: image.png]

I was following a tutorial on the website bitsandbytes.co.uk which
recommended the 1200 model with 4MB, that's why I had it set that way.

Thinking maybe the graphics settings could have something to do with the
issue---when loading a ROM directly from the ES directory, hitting a key
brings up a menu to choose which emulator to use and to chose a video mode.
1360x768 came up as the recommended mode so I chose that.

I *think* this is what you are asking for in terms of the
$config/amiga/conf directory and any .uae or other files to be found there?
[image: image.png]

One thing I did notice from one of the sources of .lha files: it mentioned
something that what they had were not the full games but only wrapper
files. Could that have something to do with why these files are not loading?

Please let me know if you need any further information and thank you again
for your help.

**Comment by midwan** [comment]
@JSchul72 
Are you sure you have the actual games contained in the `.lha` you're trying to run? It's a very common mistake to just get the slave package from e.g. https://whdload.de and think that it also contains the game itself.

**Comment by JSchul72** [comment]
I'm thinking that may be my problem. I will look for some where I can be
reasonably sure there is game content and try those.

**Comment by JSchul72** [comment]
One other question: can .zip files be WHDloaded or only .lha? I am seeing a
lot more .zip than .lha files for WHDload.

**Comment by midwan** [comment]
@JSchul72 
Amiberry can use `.zip` files as well, but RetroPie does not support those, AFAIK
