### ISSUE TITLE
50Hz scroll not smooth

### ISSUE THREAD

**Issue by deepx77** [BlitterStudio/amiberry#1055]
Hi guys, first of all thanks for this amazing software.

I have an issue with screenmodes of the Pi 4 in combination with Amiberry.
The standard screenmode it runs at (for me) is 1080P 60fps. But that does not look smooth at all.
Amiga games are 50 fps, so in the config.txt file I put: hdmi_group=1 and hdmi_mode=31 to change it to 50fps.

Now the game runs way smoother, but with slowdowns and artifacts when the screen is moving. It's most notable in pinball games or side scrollers like Giana Sisters. (60fps has the same artifacts, but less noticable, because the screen is running stuttery overall)

I also tried: 1080i, 720P, 576P (all at 50fps), no change.
My Philips TV (I also tested Game mode, TV mode, Computer mode on the tv) supports 25 to 60 fps, and I also used an Asus monitor to test.

In Amiberry I used: A500, 1MB, ADF's (with and without cycle exact) and tried A1200 030 with WHDLoad, 
I tried different display settings on Amiberry itself.

I even switched from Amibian to Dietpi, didn't think this would be the answer, but you got to test everything right?

I don't understand what I can do to change this? I hope you can help me.

**To Reproduce**

1. Load Pinball Fantasies (Dreams and Illusions show the same behaviour)

2. Load a table and just watch it scroll up/down before you start the game

3. Play a round of pinball to see how the stutters affect the gameplay :-(

**Desktop**

- OS: Dietpi (I installed it 2-2-2023, so the latest at this moment)

- Amiberry Version: v5.5.1 

- Raspberry Pi 4, 4GB (Non-overclocked and Overclocked @2ghz makes no difference)

**Comment by midwan** [comment]
@deepx77 
Do you have this issue only with the games mentioned above?

**Comment by deepx77** [comment]
Every game with any amount of scrolling. ATR, Blues Brothers.

**Comment by deepx77** [comment]
Hold up, I tried one last thing, changed the hdmi to port 2 of my Pi and it's almost gone now.

**Comment by midwan** [comment]
@deepx77 Are you running the dispmanx version of Amiberry, or the SDL2 one? Dispmanx only works on one port, since it's old and designed for older models (which only had one port).

**Comment by deepx77** [comment]
I picked the image from the dietpi website. Armv8 Bullseye file. In the sound file I see: SDL2: bcm2835.

I can see in the scrolling of pinball that it's still there, wavey lines on the bottom. But it seems less then port 1.

**Comment by midwan** [comment]
Please enable logging (Paths panel, enable the checkbox), shut down and start up the emulator again and run through one game. Then kindly attach the generated logfile here, it might provide some useful information (such as the actual refresh rate it used).

**Comment by deepx77** [comment]
It suddenly did not want to boot anymore. So I reinstalled the SD card again. 
Here is my log:  I didn't have audio this time. But after another reboot that did work again, so that's no problem.

[amiberry.log](https://github.com/BlitterStudio/amiberry/files/10579394/amiberry.log)

**Comment by midwan** [comment]
@deepx77 
I can notice what you described actually. And I also noticed that it's not there in the `dev` branch version, which is interesting.

You can try that version if you want to check yourself - just keep in mind it uses more CPU in general, so some things might be slower.

**Comment by deepx77** [comment]
Okay. Glad to hear you did notice something and I'm not crazy... well...  ;-)
How can I try the dev version in DietPi? I'm not that smart with compiling. Otherwise I will wait for a final release.

**Comment by midwan** [comment]
I don't have pre-compiled binaries for `dev` yet, though I was thinking of changing that.

For now, you'll need to compile it yourself to get it - the steps are the same as mentioned in the README, with the only exception being that you will need to specify the `dev` branch during cloning the repo: for example, `git clone https://github.com/blitterstudio/amiberry -b dev amiberry-dev`
