### ISSUE TITLE
Amiberry segfault when loading any config file

### ISSUE THREAD

**Issue by gjorans** [BlitterStudio/amiberry#1057]
**Describe the bug**
Amiberry 5.5.1. 
This binary: https://github.com/BlitterStudio/amiberry/releases/download/v5.5.1/amiberry-v5.5.1-x86-64-debian.zip
 

Amiberry segfaults when loading config files (any config file) on amd64
./amiberry 
Segmentation fault (core dumped)

It is able to be configured and started. just not able do load the config again.

**To Reproduce**
Start Amiberry.
do some config (any)
save config
load config

I did a recording showing the bug:

https://www.youtube.com/watch?v=Ckhtf8-MsL0

**Expected behavior**
loading the config and starting
**Screenshots**
[https://www.youtube.com/watch?v=Ckhtf8-MsL0](https://www.youtube.com/watch?v=Ckhtf8-MsL0)

**Desktop (please complete the following information):**

- OS: [e.g. Debian]
Linux Mint

- Version [e.g. 5.4]
20.2 
(debian bullseye/sid)

Output from the log didnt say much:

Amiberry v5.5.1 (2023-01-02) Logfile

target_cfgfile_load(): load file /home/<user>/Stuff/Amiberry/5.5.1/conf/A500.uae
load config '/home/<user>/Stuff/Amiberry/5.5.1/conf/A500.uae':3

**Comment by gjorans** [comment]
Tested a compile. And self compiled from git does not have this problem.

**Comment by midwan** [comment]
@gjorans 
This might be a bug that was fixed since the release, which would explain why it works with a self-compiled one (I assume you got the latest sources and compiled them, which would have been newer than the release). You can double-check that if you get the sources of 5.5.1 specifically, and compile those - do you still get the crash?

The weird thing is of course, that I cannot recreate this here.

**Comment by bugjacobs** [comment]
Hello ! I am on Linux Mint 20.3 on one install and It happens with 6.3.4 precompiled but not my own compiled 6.3.4 - I after a while discovered that I needed the Bullseye to fix missing libFLAC.so.12 but then this came along :-) No big deal as it appears my own compile works fine. Btw I also am unable to clone the github as it asks for password ?? Odd ! But solved that by downloading source from releases page. Anyway thanks for a great pieace of software !! :)

**Comment by midwan** [comment]
> Hello ! I am on Linux Mint 20.3 on one install and It happens with 6.3.4 precompiled but not my own compiled 6.3.4 - I after a while discovered that I needed the Bullseye to fix missing libFLAC.so.12 but then this came along :-) No big deal as it appears my own compile works fine. Btw I also am unable to clone the github as it asks for password ?? Odd ! But solved that by downloading source from releases page. Anyway thanks for a great piece of software !! :)

The pre-compiled builds are prepared using Debian containers, so maybe a difference in library versions vs your Mint installation?
