### ISSUE TITLE
RK3588 Support ( Rock Pi 5, ... )

### ISSUE THREAD

**Issue by Jodels2002** [BlitterStudio/amiberry#1061]
**Is your feature request related to a problem? Please describe.**

I am running Amiberry under Reborn OS (64) on a RK3588 ( Rock Pi 5). Amiberry was successfully built with make -j4 PLATFORM=a64. 

**Describe the solution you'd like**

Now the question: Is it possible to create a special platform for rk3588, since the processor is currently very popular?

**Describe alternatives you've considered**

 
Modified the makefile for before compiling:

else ifeq ($(PLATFORM),a64)
CPUFLAGS ?= -mcpu=cortex-a76+fp
CPPFLAGS += $(CPPFLAGS64)
CPPFLAGS += $(NEON_FLAGS)
AARCH64 = 1
HAVE_NEON = 1

Source: https://www.cnx-software.com/pdf/Rockchip%C2%A0RK3588%C2%A0Datasheet%C2%A0V0.1-20210727.pdf

RK3588 Datasheet Rev 0.1
Copyright 2021 ©Rockchip Electronics Co., Ltd. 8
 PD_CPU_1: 2nd Cortex-A55 + Neon + FPU + L1/L2 I/D Cache of little cluster
 PD_CPU_2: 3
rd Cortex-A55 + Neon + FPU + L1/L2 I/D Cache of little cluster
 PD_CPU_3: 4
th Cortex-A55 + Neon + FPU + L1/L2 I/D Cache of little cluster
 PD_CPU_4: 1
st Cortex-A76 + Neon + FPU + L1/L2 I/D Cache of big cluster
 PD_CPU_5: 2nd Cortex-A76 + Neon + FPU + L1/L2 I/D Cache of big cluster
 PD_CPU_6: 3
rd Cortex-A76 + Neon + FPU + L1/L2 I/D Cache of big cluster
 PD_CPU_7: 4
th Cortex-A76 + Neon + FPU + L1/L2 I/D Cache of big cluster

Compiling works. The generated amiberry bin has the same size and no difference to the original generic a64

Does it make no sense to add it or am I doing something wrong :-) ?

Love Amiberry? Please consider supporting it:

Yes, I love Amiberry - and that's why I'm a Patreon Bernd Titze (Jodels2002)

**Comment by midwan** [comment]
@Jodels2002 Added
BTW, don't add the `NEON_FLAGS` and `HAVE_NEON` for AARC64 targets, those are only used in 32-bit ones. ;)

**Comment by Jodels2002** [comment]
Works just fine. Amiberry works with the change under rk3588. 
Thanks. Perfect :-) 
-> ( But I think it's still missing in the dev branch  ) :-)
