### ISSUE TITLE
libserialport.h not found when compiling

### ISSUE THREAD

**Issue by amyren1966** [BlitterStudio/amiberry#1062]
**Describe the bug**
missing file libserialport.h in src/include when compiling

**To Reproduce**

1. Open a terminal windows and:
git clone https://github.com/midwan/amiberry amiberry-upd
cd amiberry-upd
make -j2 PLATFORM=rpi4-64-sdl2

2. See error: 
In file included from src/cia.cpp:22:
src/include/serial.h:16:10: fatal error: libserialport.h: Ingen slik fil eller filkatalog
   16 | #include <libserialport.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/cia.o] Error 1
make: *** Waiting for unfinished jobs....
In function ‘TCHAR* cfgfile_option_find_it(const TCHAR*, const TCHAR*, bool)’:
cc1plus: warning: function may return address of local variable [-Wreturn-local-addr]
src/cfgfile.cpp:463:8: note: declared here
  463 |  TCHAR buf[MAX_DPATH];
      |        ^~~
In function ‘TCHAR* cfgfile_option_find_it(const TCHAR*, const TCHAR*, bool)’:
cc1plus: warning: function may return address of local variable [-Wreturn-local-addr]
src/cfgfile.cpp:463:8: note: declared here

**Desktop (please complete the following information):**

- OS: Raspberry Pi OS 64 bit

**Comment by solskogen** [comment]
You must install `libserialport-dev` as stated in the README

**Comment by amyren1966** [comment]
Thanks for quickly pointing this out. I must admit I havent been reading the README in a while, since I just do an update now and then and its a long time since there was any changes in the dependencies.
