### ISSUE TITLE
Compilation problem with amiberry 5.6.0

### ISSUE THREAD

**Issue by Retro1968** [BlitterStudio/amiberry#1065]
Raspberry Pi 4 running RetroPie 4.8.2.
----------------------------------------

Hello Dimitris,
first of all, I would like to thank you very much for the release of amiberry 5.6.0! :)

Problem Description:
-----------------------

I just downloaded the amiberry 5.6.0 source code and compiled it under RetroPie with these options.
        
cd RetroPie
unzip amiberry-5.6.0.zip
cd amiberry-5.6.0
make -j4 PLATFORM=rpi4-sdl2
chmod 755 amiberry

As you can see on my putty screenshot, there were no errors after compiling.
![putty after compiling](https://user-images.githubusercontent.com/58906142/227771494-bbb48ba6-2d95-4f1b-97ab-bb1df5c14457.jpg)

But as you can see on my MC screenshot, no amiberry.sh file was created.
![Folder after compiling](https://user-images.githubusercontent.com/58906142/227771512-f7de4a2b-0f5b-4051-995f-59c00f68b70b.jpg)

What can be the reason?

Cheers
Retro1968

**Comment by Retro1968** [comment]
I just see that i got a "fatal error: libserialport.h: file or folder not found 16 #include <libserialport.h>

**Comment by midwan** [comment]
@Retro1968 
There's a new library requirement with this version, as documented in the Readme: `libserialport-dev` :)

**Comment by Retro1968** [comment]
Have solved the problem with:

sudo apt install libserialport-dev

Thx. :)
