### ISSUE TITLE
Errors with Cycle Exact Emulation and Config Files

### ISSUE THREAD

**Issue by PARALAX1974** [BlitterStudio/amiberry#1068]
There are some issues since updating from Version 5.2 to the current. When loading an own created config file after starting the emulator and pressing on "RESET", the screen stays black and you cannot leave the emulator any more. I have to reboot the Raspberry Pi completely with the power button. The only way to load own config files is to click on the "Reboot"-Button before loading an own configuration. Loading the config files directly and resetting Amiga works until Version 5.2. Furthermore there seems to be some errors with the "Cycle Exact" CPU & Chipset Emulation. Some games like "Zarathrusta" don't work correctly after using this option from CPU Speed Menu (Ship will be destroyed every time during the game). This also worked with Version 5.2 and Cycle Exact Chipset Emulation. It's a bit strange, as the "Cycle Exact" Chipset and CPU Emulation should be the most compatible settings for all games & demos, but it seems that something has changed in the last version.

- OS is: Retropie 4.8

**Comment by midwan** [comment]
Please attach some example config files that cause the problem, so i can try to recreate this.

I'll check the game you mentioned separately.

**Comment by PARALAX1974** [comment]
I've attached all my current Amiberry Configs and hope that it helps for bugfixing. The current version actually runs smoother at 50 Hz., but I can't use it while it does so at the expense of compatibility issues. And with version 5.2 everything seemed to work 100% with OCS, just like with WinUAE. By the way, the configuration I use is "Amiga 500-New.uae" and is in the ZIP file. Incidentally, the problem does not occur with an AGA configuration, especially since this does not (yet) offer a 100% Cycle Exact Emulation setting. I hope this will also added soon, even for Raspberry 4b user with overclocked CPU's. My 8 GB model runs with 2 Ghz. which should be hopefully enough for a cycle exact A1200/4000/CD32 Emulation.

[Amiberry Configs.zip](https://github.com/BlitterStudio/amiberry/files/11143538/Amiberry.Configs.zip)

**Comment by PARALAX1974** [comment]
Small Update here: RESET-Issue seems to be fixed meanwhile with tested Version 5.6.6, but the Game "Zarathrusta" is still buggy when using both "Cycle Exact" options. The ship is still crashing, even when not hitting any walls or enemies. This seems to be not fixed since Version 5.3.
