### ISSUE TITLE
movem.l a7,-(a7) should act differently depending on the processor

### ISSUE THREAD

**Issue by execriez** [BlitterStudio/amiberry#1070]
The following code should return a different result depending on whether or not the processor is less than a 68020.
On amiberry, the code always returns d0=0

```
; Check processor
;
;  exits with d0=0 if the processor < 68020
;  exits with d0=-1 if the processor >= 68020

PROCTEST:
	moveq	#0,d0
	dc.l	$48e70001	; = movem.l a7,-(a7)
	cmpa.l	(a7)+,a7
	beq.s	PROCTESTX	; branch if < 68020
	moveq	#-1,d0
PROCTESTX:
	rts
```
I have only tested this on the MacOS M1 version so I don't know if this affects all versions.

**Comment by execriez** [comment]
I realise my feedback is a little sparse, so explanation is probably in order.
```
movem.l a7,-(a7) 
```

does this on 68000 and 68010:
```
(a7-4)=a7
a7=a7-4
```
should do this on 68020 and above:
```
a7=a7-4
(a7)=a7
```
No matter what processor is chosen, Amiberry always executes the movem instruction like a 68000

---
Or putting it another way...

On anything less than a 68020, the instruction
```
movem.l a7,-(a7) 
```
acts like the move.l instruction, i.e.

BEFORE:

```
Reg    Addr   Contents
       N-4    ?
a7  -> N      ?
```
AFTER:

```
Reg    Addr   Contents
a7  -> N-4    N
       N      ?
```
---

However, on 68020 or more
```
movem.l a7,-(a7) 
```
should act like this...

BEFORE:

```
Reg    Addr   Contents
       N-4    ?
a7  -> N      ?
```
AFTER:

```
Reg    Addr   Contents
a7  -> N-4    N-4
       N      ?
```
---

**Comment by midwan** [comment]
Thanks! The current `master` branch's CPU emulation is not 100% accurate, so that's probably why the above happens.
I have started working on a complete merge of the CPU code from the latest WinUAE in a separate branch (`preview`), but currently that only works under the `x86-64` and MacOS targets. The ARM version still needs work.

If you want to test it there, it should behave normally.

**Comment by execriez** [comment]
Many thanks for your update.
I compiled the latest preview branch for osx-m1 and I can confirm that as you suggested, in that branch the instruction is executed normally.
