### ISSUE TITLE
XDG_RUNTIME_DIR not set in the environment error

### ISSUE THREAD

**Issue by MrV2K** [BlitterStudio/amiberry#1072]
**Describe the bug**
When I run Amiberry 5.6 in Diepi I get the following error when ever Amiberry starts or has to create a new window due to a resolution change. This causes the Amiberry screen to flicker and make the emulated Amiga stutter momentarily.

`XDG_RUNTIME_DIR not set in the environment`

**To Reproduce**
Run the service or boot into Amiberry on DietPi. It happens on startup and when workbench or games/demos change resolution. A good example is Spaceballs - State of the Art.

Is there a simple fix?

**Desktop (please complete the following information):**

- OS: DietPi
- Version v8.16.2

**Comment by midwan** [comment]
This is not an Amiberry error itself, but something coming from older versions of MESA if I remember correctly. It's harmless and can be ignored, however.

**Comment by MichaIng** [comment]
@MrV2K 
Are you still facing this? I think it is two dedicated issues:
1. For `XDG_RUNTIME_DIR` to be set, `systemd-logind` needs to run:
    ```sh
    systemctl unmask systemd-logind
    apt install dbus
    systemctl start systemd-logind
    ```
    However, as midwan said, this should not cause any issues, and could be ignored.
2. But you mean that the error (respectively any console output) is shown above the Amiberry GUI? If so, on which SBC does this happen? There are quite some reasons why Amiberry (or SDL or whatever) can produce output on the console, but this was never visible above the Amiberry GUI. What does make sense, and this is probably what you mean: While the resolution changes, the plain console is visual, hence whatever output is there, is then visible, until Amiberry pops up above it again. To solve this ultimately, any console output would need to be suppressed. I just don't like it, as it means that any possibly relevant error output is then lost as well, making debugging any real issues difficult.

**Comment by MichaIng** [comment]
Okay, I am pretty sure then it is just that you (expectedly) see the underlying console for a blink while the resolution switches. I played around a little to see whether we can avoid that somehow, but STDIN and STDOUT must both be attached to the active console for input and output (GUI) to work.

So we'd need to mute this error. Strange that logind does not help. The default XDG runtime dir for the root user is `/run/user/0`. Does that exist on your system? If not, does logind run?
```sh
journalctl -u systemd-logind
```
Generally we can also just create a custom dir and set this as `XDG_RUNTIME_DIR` from the systemd service. This would make us independent of logind. I'll also try to replicate this when I find time and test setting it manually.
