### ISSUE TITLE
Some HDFs fail on startup in latest version

### ISSUE THREAD

**Issue by corasaniti** [BlitterStudio/amiberry#1075]
**Describe the bug**
With the update to the Amiberry v5.6.0 version and LibSDL2 v2.26.4 many configurations and HDF don't start anymore and I get a black screen. I was forced to downgrade to Amiberry 5.5.1, including LibSDL2 v2.26.2

- OS:
Raspberry Pi4 Pi3 and Dietpi bullseye

- Version 
Amiberry v5.6.0 version and LibSDL2 v2.26.4

**Comment by midwan** [comment]
Thanks for reporting the issue.
The logfile shows that a crash occurred during initialization, but I'm not yet sure at which stage.

Does it work if you recreate such a config from scratch? That should show us if it's a problem parsing the contents of old configs or not, at least.

Can you attach such a config file here? Even if I don't have the HDF, it's worth a try to see if I can recreate it.

**Comment by corasaniti** [comment]
@midwan 
Of course here is attached one of the many confugurations that I can not get started. 
For this I downgraded to version 5.5.1
As soon as I have time I'll try to create this new configuration and let you know.
[amiga-ags-mini-ver1.5.zip](https://github.com/BlitterStudio/amiberry/files/11242897/amiga-ags-mini-ver1.5.zip)

**Comment by corasaniti** [comment]
@midwan 
Attached is the newConfig.zip which contains the new configuration created and its log.
The result is the same I was not able to start this setup
Thanks for the help
[newConfig.zip](https://github.com/BlitterStudio/amiberry/files/11243054/newConfig.zip)

**Comment by midwan** [comment]
@corasaniti 
Thanks!
Does the config work if you don't add any HDFs? 
Does it crash only with a specific HDF perhaps?

**Comment by corasaniti** [comment]
> Does the config work if you don't add any HDFs?
Yes
> Does it crash only with a specific HDF perhaps?
Yes

**Comment by midwan** [comment]
@corasaniti 
OK, what's different with that specific HDF then?
Is there a way to recreate it separately, so I can try it here?

**Comment by corasaniti** [comment]
@midwan 
You can find everything here

https://www.facebook.com/groups/1144009169831106/permalink/1178514513047238

**Comment by corasaniti** [comment]
@midwan 
However there are many hdfs that don't start me with version 5.6 and instead work with 5.5.1
Thanks

**Comment by midwan** [comment]
Fixed with the commit above, will be part of the next release.

**Comment by corasaniti** [comment]
@midwan 
Do you have news about this fix? When will the new release that fixes this issue? 
Thank you

**Comment by midwan** [comment]
@corasaniti 
There's no fixed date yet, there are a few more issues that need to be looked at/resolved first.

But you can always get the latest from source and compile it, if you can't wait for a new binary.
