### ISSUE TITLE
Savestate command line option ignores filename

### ISSUE THREAD

**Issue by hissingshark** [BlitterStudio/amiberry#1081]
**Describe the bug**
The `--savestate <file>` option ignores the provided filename.  It falls back to restoring the state file associated with slot 0 of the current ROM.
Tried to debug this but got lost in the source.

**To Reproduce**.
In `savestates/` I may have states from slots 0, 1 and 2:
> XOut_v1.2_1Disk_1274.uss
> XOut_v1.2_1Disk_1274-1.uss
> XOut_v1.2_1Disk_1274-2.uss

1.
If run with `./amiberry --autoload /home/osmc/RetroPie/roms/amiga/XOut_v1.2_1Disk_1274.lha -G --statefile` it correctly logs:
> Missing argument for '--statefile' option.

2.
But `/amiberry --autoload /home/osmc/RetroPie/roms/amiga/XOut_v1.2_1Disk_1274.lha --statefile -G` silently fails.
It takes the `-G` as a nonsense <file> argument.
It then restores  `XOut_v1.2_1Disk_1274.uss` (slot 0).

3.
Provided with the file for slot 2:
`./amiberry --autoload /home/osmc/RetroPie/roms/amiga/XOut_v1.2_1Disk_1274.lha --statefile savestates/XOut_v1.2_1Disk_1274-2 -G`
It restores the slot 0 file again!

**Expected behavior**
I assume the specific state file provided is the one to be restored. 

Running v5.6.0 on Vero4k.

Many Thanks.

**Comment by midwan** [comment]
Confirmed, this is a bug when using the command line option (the GUI method works as expected).

**Comment by midwan** [comment]
Fixed, will be part of the next release
