### ISSUE TITLE
When GUI window becomes inactive, contents are no longer redrawn/updated

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1090]
The youtube vid accurately shows the problem -->> https://www.youtube.com/watch?v=mzLvZtyjieI

(excuse the mess, looking a feasibility of 1024x768 gui =)

If the amiberry GUI window becomes inactive (lost/stolen focus), contents are no longer redrawn/updated after occlusion by another (active) window ~ the instant (mouse) focus is regained and amiberry window become active, contents are redrawn. 
This looks 'bad' and is likely an unwanted behavior? (we don't want the GUI contents getting 'trashed' like this and made ugly)

Vid recorded on this Debian 10.13 [AMD64] with nvidia drivers and amiberry v5.6.1 (local git build) ~ I see the same behavior on i915 based vid drivers with my LFS builds & fresh Deb 11 install on another AMD64 box with nouveau drivers. (that mob spans SDL2 from v2.0.9 thru v2.26.3)

Query: Could this be handled in a better way, or, is it some bug somewhere?

TIA

**Comment by giantclambake** [comment]
// ...as a coder, I make for a great pizza chef ...

A quick glimpse of the code and a search of the tomes, turns up this...

```
The loop is centered around events. If the window does not have focus it won't receive any input events
and that's often all the events you get. You have options.

set up a timer to inject a custom event at regular intervals that would drive your loop when no other events
are received.

let the loop not be dependent on events, but just run continuously and then inside the loop check if there
happen to be events to process and if not, do other stuff.
```

...that sounds about right to me ~ main_window is doing this? Or...should this be done somewhere else, as really this only affects GUI display...ie; I'm a mechanic, choose the timer route, and only inject custom (update display) events when GUI is active. I imagine on a small device/display, one would never really come across this, so it's likely another nuance of the 'desktop app' usage scenario wrt amiberry?

Sadly, I can't code and help directly ~ only report and read into the issue, which I hope helps 8)

**Comment by midwan** [comment]
Fixed with the commit above
