### ISSUE TITLE
Multiple Controllers' Buttons Not Working in RetroPie

### ISSUE THREAD

**Issue by DoogyR3V** [BlitterStudio/amiberry#1092]
I am having an issue when using multiple (identical) controllers where only the first registered controller's buttons work. I'm running Amiberry 5.6 on Retropie.

In the emulator, the D-pads and analogue sticks work correctly on all controllers whichever port they are assigned to but the buttons only work on the first controller.

In the GUI, the D-pad and buttons only work on the first controller but the analog sticks work on all of them.

It might be related or not but in the amiberry.conf file under default_controllerX and default_mouseX, joy0 doesn't represent the first joystick, joy1 does.

A little bit more info, hopefully relevant. All controllers can enter the GUI with the Retroarch hotkey combo. Only the first controller can exit with this combo. Oddly, this behavior is the same whether the menu combo is disabled or not. Disabling the quit combo seems to work correctly, though, and only the first controller can quit when it's enabled

**Comment by willindernet** [comment]
I have a similar problem. Retropie with Amiberry and Gamecondriver (db9_gpio_rpi).

Gamecondriver is installed and loaded (options db9_gpio_rpi map=1,1). I checked all the buttons on my two joysticks with jstest /dev/input/jsX. They all work.

In Amiberry, however, the fire button of the second joystick does not work. All other functions are available.

With UAE4ARM it worked.

**Comment by willindernet** [comment]
If you need help with the test or logfiles, I can support you

**Comment by midwan** [comment]
Do you have the same problematic behavior on a diagnostic tool?
I usually test things with `AmigaTestKit` (available here: https://github.com/keirf/amiga-stuff/releases/tag/testkit-v1.20), which can visualize the controller input from each port.

Check that you have your controllers correctly configured in the Input Ports as well (Port 0 and 1). The mode is important, the `Default` is a standard 1-2 fire button joystick, use CD32 mode if you want to support all the buttons. And make sure to also set the same option in AmigaTestKit, so you can see what is being pressed.

**Comment by willindernet** [comment]
Hi Dimitris,

Thank you very much for your answer.
I use original Competition Pro (DB9). I have connected them to the GPIO pins of the Raspberry Pi. I use the gamecondriver (db9_gpio_rpi) as driver. I did this as described at 
[Retropie](https://retropie.org.uk/docs/GPIO-Modules/). It also worked under UAE4ARM. Then I wanted WHDLoad and switched to Amiberry. Here the fire button of the second joystick no longer works. All other functions are there. With the diagnostic tool 
/dev/input/Jess and /dev/input/js1 the joysticks can be tested. They both work. 
 will test with AmigaTestKit in the next few days.
I have described what I did in German. But Google Translate does a good job: https://ichwillinsindernet.de/retropie-mit-amiga-emulator/

Thanks and greetings 
Norman

**Comment by DoogyR3V** [comment]
I've tried it with DiagROM. It's exactly the same as with a game. Set up Port 0 as first controller in list, type default or joystick; all movement and fire button registers. Set up Port 1 as second controller, either type; all movement registers, no button register. Swap controller positions in list >> Set up Port 1 as first controller in list, type default or joystick; all movement and fire button registers. Set up Port 0 as second controller, either type; all movement registers, no button register.

If I map second controller directions to fire button input it registers, e.g. dpad up can work as fire button but button inputs do not work when manually mapped, e.g. north button or leftjoy press on second controller to fire button. First controller buttons can be mapped to other port fire button and work correctly. Obviously, both these configurations are useless but they prove that the button inputs of the second (or third or higher) controller are not being picked up by the emulator.

**Comment by midwan** [comment]
Bug located and fixed. Will be part of the next release.

**Comment by willindernet** [comment]
Great, thank you

**Comment by DoogyR3V** [comment]
> Bug located and fixed. Will be part of the next release.

Excellent, thanks!
