### ISSUE TITLE
Ambiguity wrt internal/replacement ROM usage

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1095]
With a fresh build/install of amiberry, at first time start (before populating /kickstarts with ROM images) you see this;

![this is NOT a rom file](https://i.imgur.com/ZRQmd7J.png)

That is a misnomer ~ the ROM file named 'amiberry-5.6' does not exist ; it is impossible for the user to select this manually.

Perhaps this is in error?

Premise: There may be some Amiga disk images that work fine on internal/replacement ROM code ; that ROM code itself may improve over future years allowing more titles to run. This may/would give rise to users wanting to select the internal ROM replacement code deliberately, and not get swatted with the internal rom being used warning (there doesn't seem to be a way to disable that).

Maybe the misnomer should be made real, and the file 'amiberry-5.6.ROM' should exist, so users can choose it thus indicating they want to try/use the internal rom code, and the popup warning in that case isn't generated? 

Apols for being such a pedant, it was just something I noticed that "didn't make sense", and for sure there's no easy way for user to choose 'use internal/replacement ROM' for example. I would consider this to be a feature, as it were to spark the interest of some yet to be found coder, to become obsessed with and work on the internal ROM replacement code, to make it more complete/compatible with the original Amiga ROM code (I used to work on/with WINE over a decade ago, so I know I'm not being a total dreamer here B) 

The ambiguity is that I cannot divine whether the appearance of 'amiberry-5.6' in the ROM dropdown menu, is merely announcing amiberry($version), or else is a placeholder signifying the internal/replacement ROM code itself is to be used? Seeing as this subsequently disappears altogether later on in actual usage, it becomes a misnomer wrapped in an enigma, and appears to be rather mysterious.

Granted, a barely worth it, corner case sort of feature ... at present ... but including the ability to select internal ROM resolves all the ambiguity, and removes the mystery. (and who knows, future internal ROM code may become a more viable option one day).

**Comment by midwan** [comment]
That doesn't seem right - there should not be any ROM item named "amiberry" showing there. Might I ask how did you get that showing?

There is no internal ROM either, anymore. I've included the AROS kickstart ROMs as external files, to make it easier to update them as new versions come along. Having it as internal would make that impossible, and even though you could still use AROS roms externally, it made the executable unnecessary larger.

**Comment by giantclambake** [comment]
I agree ~ it isn't right =)  

To recreate that, compile from  https://github.com/BlitterStudio/amiberry/archive/refs/tags/v5.6.0.tar.gz

Start amiberry and you should see 'amiberry-5.6' in the Main ROM field, and be able to select that from the dropdown menu.

If you then populate the /Kickstarts directory with Amiga ROMs and restart amiberry, you should no longer see (or be able to select) the 'amiberry-5.6' entry.

If you then remove the Amiga ROM files and restart amiberry, the entry 'amiberry-5.6' reappears. 

If you select 'amiberry-5.6' and start the emulation, you see the warning "Could not load system ROM, trying system ROM replacement" (*read below)....ie; ostensibly nothing was selected =)

//amiberry v5.6.1 (git-master)

The Main ROM entry of 'amiberry-5.6' no longer appears, and is a blank field.  In this condition, it is actually possible to select the blank field from the dropdown menu. Just being able to do this, gives the impression that no Main ROM file was selected -- if you then start amiberry, it leads to the same warning "Could not load system ROM, trying system ROM replacement"...

In this case, populating /Kickstarts with  (known) Amiga ROMs, removes the selectable blank field from the dropdown menu box, however, if /kickstarts contains valid (but unknown..ie; no CRC match) Amiga ROMs, this selectable blank field reappears at the bottom of the dropdown menu. By rights, users shouldn't be able to select 'nothing' here =)

(*) if there is now no internal ROM replacement, and by default the AROS m68k ROM is to be loaded, the popup warning should accredit that situation...ie; "Could not load system ROM, trying AROS system ROM replacement"

TIA

**Comment by midwan** [comment]
The AROS rom files are part of this repo, and are included in the binary releases as well. This means that `kickstarts` should always contain at least those files, until you add your own ROMs.

Is that the case in your environment also, or did you change something?

I'll update the message shown to mention it will try to load the AROS rom (if found).

**Comment by giantclambake** [comment]
Confirming this fix for #1095

@midwan 

Yes, that's correct for my amiberry environment ~ it was mostly the menu handling that alluded to the case an 'internal' replacement ROM image (might) exist --- this commit clears it up nicely.  TY
