### ISSUE TITLE
Amiberry splash-screen sometimes red, sometimes cyan (whdbooter auto configurator)

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1099]
To recreate;

Choose a whdload.lha archive ; remove it's corresponding entry in  whdboot/game-data/whdload_db.xml

This will force amiberry to start the whdbooter prog, when you load/run the whdlood.lha file via --autoload or GUI

As part of that process, the Amiberry logo forms a splashscreen ~ here it appears either red ('proper'), or else cyan in colour.

(easter-egg? =)

**Comment by midwan** [comment]
That's kind of a "feature" of the AMOS Pro application that the fallback WHDLoad booter is. It's always been like that, I'm not 100% sure why, but it's harmless :)

**Comment by giantclambake** [comment]
Thanks, understood ~ closing this as being a 'known curio' =)
