### ISSUE TITLE
Fullscreen toggle hotkey not working

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1103]
Quoting https://github.com/BlitterStudio/amiberry/wiki/GUI:-Misc  

"FullScreen: A key to toggle Full-screen/Fullwindow and Windowed mode. None is set by default"

To recreate;

Due to #1102  you need manually edit amiberry.conf to set the hotkey mapping and save changes;

default_fullscreen_toggle_key=F

Launch amiberry GUI ~ you don't actually need an Amiga title ; default.uae config with kickstart 1.3 ROM is enough.

~ if started in windowed mode, the fullscreen toggle key (F) causes screen to go black for a few seconds, then returns in the windowed mode we started with

~if started in fullscreen mode, the fullscreen toggle key (F) causes screen to 'shake' ... emulation stays fullscreen

This is problematic when, say you load and start a whdload.lha file (demo/game), it will invariably start in windowed mode. It would save a lot of fuss if this fullscreen toggle worked, as you don't have to edit the XML or create a custom config file just to watch a graphics/music demo in fullscreen mode.

**Comment by solskogen** [comment]
If you find a spelling mistake on the wiki you can just edit and fix it yourself :-)

**Comment by giantclambake** [comment]
@solskogen   

That, I did not know ~ thanks for the heads-up =)

**Comment by midwan** [comment]
@giantclambake 
It seems to me that you want to start things up in Full-Window mode always?
You can take a look at the wiki, there's a relevant option you can set for that in `amiberry.conf`: https://github.com/BlitterStudio/amiberry/wiki/Amiberry.conf-options

**Comment by giantclambake** [comment]
@midwan 

No, I don't always want to start things fullscreen/full-window  =)  I want users to be able to start for instance a whdload.lha title, have it open in windowed mode (as most do), and for the user to decide/select if they wish to view that title in fullscreen of full-window mode with a simple key-press.

At present, the best I can offer users is to maximize/stretch the display window (requires mouse or  WM shortcut)

Regarding the wiki, I imagine you're referring to ;

```
default_fullscreen_mode

You can use this option to control what screen mode the emulator should start with, by default. There are currently 3 modes supported: 0 = Windowed (only possible in a Desktop environment) 1 = Fullscreen (changes resolution of the monitor) 2 = Full-window (scales the picture to the current monitor resolution)

Possible values: 0, 1 or 2

Default value: 0
```

I was under the impression that the possible values here (0,1,2) were changed (on the fly) by ;

```
default_fullscreen_toggle_key

The default key to toggle Fullscreen mode, in plain text. The text here will be interpreted by SDL2's [SDL_GetKeyFromName()](https://wiki.libsdl.org/SDL_GetKeyFromName) function, to get the actual key code.

Possible values: any human-readable text representing a key

Default value: none
```

As reported, default_fullscreen_toggle_key does not save the actual key code (#1102) to amiberry.conf, and if you manually edit default_fullscreen_toggle_key=(some keypress), the mapped default_fullscreen_toggle_key has no effect.

So the inference of what you're saying here, is default_fullscreen_mode always overrides default_fullscreen_toggle_key? That's certainly what it seems, but if so, that means default_fullscreen_toggle_key is redundant/useless?

Question: what purpose than does default_fullscreen_toggle_key serve?
