### ISSUE TITLE
Odd display handling when quitting amiberry [GUI]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1105]
//Note: There are actually 2 issues here ~ display handling when quitting the GUI ~ display handling when starting //emulation in fullscreen mode. I suspect the 2 issues are somehow related, so I've included both in this description, //however if that presumption is in error, let me know and I'll create another issue for the latter.

To recreate (as seen in the YT vid):

https://www.youtube.com/watch?v=ou6lXZXyT24

Start amiberry -> check display is set to windowed mode -> Quit amiberry [program closes cleanly]

Start amiberry -> check display is set to full-window mode -> Quit amiberry [program briefly spawns 2 windows as it quits]

Start amiberry -> check display is set to fullscreen mode (note I set to my native display res of 1280x1024) -> Quit amiberry  [program spawns blackscreen @ 800x600 for a couple of seconds, then desktop is displayed]

//note my capture does not show the return to desktop

How did I conclude the fullscreen description above is correct? ;

root [ /var/log ]# tail Xorg.0.log

[450696.037] (II) intel(0): resizing framebuffer to 800x600
[450696.039] (II) intel(0): switch to mode 800x600@60.3 on VGA1 using pipe 0, position (0, 0), rotation normal, reflection none
[450696.175] (II) intel(0): resizing framebuffer to 1280x1024
[450696.180] (II) intel(0): switch to mode 1280x1024@60.0 on VGA1 using pipe 0, position (0, 0), rotation normal, reflection none

This is consistent -- it doesn't matter which resolution you select with fullscreen set, it always spawns @ 800x600

//
//reboot machine

The second issue I mention above, can be recreated by following on from the above, except starting the emulation instead;

https://www.youtube.com/watch?v=PDrudY2Rdls

Start amiberry -> check display is set to fullscreen mode (note I set to my native display res of 1280x1024) -> Start emul

[program starts, screen goes black for a couple of seconds (not shown), returns display desktop @ 1280x1024, and amiberry has opened a 800x600 window, but clearly it's in 1280x1024 resolution, it's just somehow botched the X display co-ords. If I use Alt-Tab (or minimize/maximize the amiberry window), the emulation displays fullscreen 1280x1024 as it should be.]

Same again, tail Xorg.0.log discloses..

[    56.825] (II) intel(0): resizing framebuffer to 800x600
[    56.827] (II) intel(0): switch to mode 800x600@60.3 on VGA1 using pipe 0, position (0, 0), rotation normal, reflection none
[    56.964] (II) intel(0): resizing framebuffer to 1280x1024
[    56.969] (II) intel(0): switch to mode 1280x1024@60.0 on VGA1 using pipe 0, position (0, 0), rotation normal, reflection none

This affects any Amiga title I want to start in fullscreen mode.

**Comment by giantclambake** [comment]
Supplemental:

Now that the FullScreen toggle key is working again, I suspect this issue has something to do with the following behaviour;

https://www.youtube.com/watch?v=ECuaDVKdh_Y

**Comment by midwan** [comment]
Is this only happening with Full-screen modes then?
What about Full-window modes? Generally those seem to behave better, as they don't request to switch resolution on the monitor, and only scale the output image instead.

**Comment by giantclambake** [comment]
@midwan 

Yes, only with the FullScreen mode set in Display panel ~ Full-window mode works as expected. Basically it makes FullScreen mode unusable unless you Alt-Tab/minimize-maximize the window as shown above. 

I should point out that with nvidia proprietary drivers, FullScreen mode can cause the display to be stuck in 800x600 mode when things return to the desktop, and you have to use nvidia-config to reset the native display resolution. Using Xorg nouveau drivers, the behaviour is the same as described.

**Comment by giantclambake** [comment]
Additional details;

I spent some time looking at this more closely ~ I was able to coax some other odd behaviour out of the fullscreen_toggle key, but in saying that there was some inconsistency in results ...ie; as per my previous mention of nvidia driver behaviour, that's around 50/50 chance you'll get left with a 800x600 desktop and the native 1920x1080 resolution has not been returned...it sort of suggests some race situation...(between the emulator and gui code?)...like I say, it's odd.

For instance, if your host native display is 1280x1024, and in amiberry you have FullScreen set @ 1280x1024, why does amiberry switch X display mode to 800x600 in the first place?

I mention originally about the display 'shaking' when the fullscreen_toggle key is used ~ that turns out to be the fullscreen toggle key switching between FullScreen & Full-window mode at the same host display resolution. I believe that only occurs if the currently loaded .uae config is set to start emulation FullScreen at native host display resolution.

On the plus side (and this hasn't escaped my attention), if you do a 'load & go' (quickstart->load floppy or select whdload file -> start), everything works as expected wrt fullscreen toggle & screenmode switching.

If you set default.uae config to Fullscreen @ 800x600 everything works as expected ; it's only when you select something other than 800x600 in the dropdown selector, that things behave badly. Another note is, when things do behave badly, it seems near impossible to get the F12/open GUI key to work...you can alt-tab or min/max the window, capture/release mouse focus, but F12 does not respond ... it's odd =)

I think the simple test case is to gunzip the attached default.uae file into your conf/ directory, start amiberry [should startup as normal], then Quit the amiberry GUI [switches screenmode to 800x600 before quitting]

Do you see the same there?

[default.uae.gz](https://github.com/BlitterStudio/amiberry/files/11745168/default.uae.gz)

**Comment by midwan** [comment]
I'd recommend you avoid using Full-screen modes for now, and use Full-window instead.
Full-screen has been problematic with glitches since it was added, I guess due to the way SDL2 / Linux handles it.
I am considering removing that option and leaving only Full-Window and Windowed, to simplify things...

**Comment by giantclambake** [comment]
I'll blame Xorg =) When I was doing this sort of stuff with codeweavers/WINE, X was a constant source of frustrations such as this ...in equivalence, the need to launch a win32 app in a 'virtual desktop' because X would get things terribly wrong wrt screenmode / resolution switching ~ that behaviour is/was very similar to what I see here TBH. We won't hold our breath, but perhaps when wayland matures a lot of Xorg shortcomings will be addressed...hopefully...

Can I ask you to consider keeping Full-screen mode BUT limit the available resolution to 800x600?

Rationale: That actually works correctly and as it should, fullscreen toggle key works as expected, and functionally it does nothing wrong. The only caveat is that this incurs the 'pregnant pause' as X switches screenmode resolution, but that is intrinsic to X and/or the SDL layer...ie; if you have a the emulation running and toggle fullscreen key, audio output from the emulator stutters for some milliseconds, but recovers a full second or more before the X display returns. This isn't amiberry... more like SDL/X .. but it works =)

What doesn't work is if Fullscreen is set to any other resolution available in the dropdown list....and one of the resolutions offered is 1920x1080 which my host display hardware doesn't even support (if selected, there's a bigger pause before seeing windowed mode start @ 800x600 )  ...but whatever, if the Fullscreen resolution was locked to 800x600, it's far far less problematic.

OTOH and like you say, there are a number of glitches with Full-screen modes, and I've already proven to myself that non-free video drivers can rope in even more, and it becomes a small minefield 8)

Certainly you don't want to spend time fixing all this, when that time may be better spent improving the uae engine itself for example, and given the fact I only came across amiberry at v5.6.0 ... your words "Full-screen has been problematic with glitches since it was added"  very much provides some relevant history to me view.

I just tossed a 1955 Australian penny ~ heads = keep fullscreen locked at 800x600 ; tails = remove fullscreen -> the coin landed on heads. Your turn... //grin//

**Comment by giantclambake** [comment]
Addendum: If you launch a whdload.lha with --autoload, it will start in Windowed mode -> if you hit the fullscreen toggle key, the display settings are Fullscreen: 800x600 ; Screen mode: Fullscreen

That works well, and I think lends a hint towards keeping it, but only at this setting?

**Comment by giantclambake** [comment]
//...even more drivel about this ~ I've a lot of time on my hands...

If I imagine the case wherein Fullscreen mode is locked @ 800x600 (whether or not that is exposed to the GUI or just incorporated as being part of fullscreen_toggle_key default functionality like it is now, becomes less complex =)

The moment I consider that, my daft logic is most all folks using amiberry on your typical linux distro, will have a native desktop resolution that is NOT 800x600.  I'm not sure if that means very much, but it's a valid observation these days.

If that were so, then the only real problem is the manner in which the GUI quits, IF the Display->Screenmode->Fullscreen widget is set (irrespective of resolution but here we're speaking to 800x600). Essentially speaking it doesn't make sense that the GUI display settings affect the GUI itself ~ these settings are for the emulation engine itself. That said, I did a bit more reading of the SDL docs and get this gist of what's going on...(I think ;)...

//In a sane world, the GUI should check what the current host $display is ~ if it's 800x600, all good, do nothing, quit as normal

As this quirk also affects GUI quit if the Full-window mode is set (but to a lesser degree)...

~if the quit button/call is made, user has finished and saved any changes made
~~if host $display is !=800x600 then inject windowed mode as the current volatile Display setting, then quit as normal

Is there time enough/some way to such a thing, basically enforcing windowed upon GUI quit? The problem does extend to the Restart/Reset buttons as well (in GUI, no emulation running), but the quit behaviour is worse as alt-F4 and wm close window also result in X changing screenmode... when it really shouldn't

**Comment by giantclambake** [comment]
Closing this ~ issue no longer present in amiberry v5.6.4
