### ISSUE TITLE
Selected 'FullScreen' hotkey not saved to amiberry.conf  [GUI --> Miscellaneous ]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1107]
To recreate ;

Start amiberry GUI --> select Miscellaneous config item

Click on '...' for FullScreen: -> requester window opens, prompting you to hit a key -> you tap a key..ie; F11 -> requestor window closes, and the FullScreen: field appears to be mapped to F11 in the GUI 

However. checking amiberry.conf reveals that  'default_fullscreen_toggle_key= ' has not been set to selected key mapping.

Note: this also affects the Open GUI: , Quit Key: , Action Replay: , Minimize:  widgets in the panel -- no configured/detected keypress is saved to amiberry.conf

**Comment by midwan** [comment]
It's not supposed to save there.
Those options from the GUI save to a normal `.uae` config file.
The `amiberry.conf` file contains the default options, and most of the time needs to be edited manually.

**Comment by giantclambake** [comment]
Thanks for the comment, and apologies for causing you any frustration/reiteration ~ I (finally) understand now why my thought-train was being derailed.

amiberry.conf;

//default settings

default_open_gui_key=F12
default_quit_key=
default_ar_key=Pause
default_fullscreen_toggle_key=

filename.uae;

//not present unless defaults changed (this caught me out) or keypress mapped

amiberry.open_gui=
amiberry.quit_amiberry=
amiberry.action_replay=
amiberry.fullscreen_toggle=

Ergo, when I read from the wiki ... 

"Open GUI: The key to open the main Amiberry GUI. By default, this is F12." & "Action Replay: A key to open the Action Replay/HRTmon. The default one is the Pause key."

.. my brain expected that in any/every *.uae file to see;

amiberry.open_gui=F12
amiberry.action_replay=Pause

This'll be an English thing (inferred/participle noun) ; it's an easy fix, using pretty much your own words. 

If the wiki read as below;

"In this panel, you can control various emulator options that didn't fit in any of the previous panels. Changes made here are saved to the currently loaded .uae config file, and override any defaults defined in the amiberry.conf file." 

That would obviate the fact that defaults are contained in amiberry.conf and options in the panel itself relates/are saved to the current .uae file.

**Comment by midwan** [comment]
Thanks, wiki page updated accordingly
