### ISSUE TITLE
macOS M1 native builds no longer released

### ISSUE THREAD

**Issue by n0rt0nthec4t** [BlitterStudio/amiberry#1108]
Since 5.6, there are no native macOS M1 binary packages release

**Comment by midwan** [comment]
I don't prepare those, so they are available with some delay (someone from the community does them).

Ping @solskogen

**Comment by n0rt0nthec4t** [comment]
Since targeting x86 for macOS, can it be targeted as a universal binary? @solskogen

**Comment by solskogen** [comment]
Maybe, but I don't know how that works together with the dependencies and such that is provided by Homebrew.

**Comment by n0rt0nthec4t** [comment]
@solskogen https://wiki.libsdl.org/SDL2/README/macos

Atleast on the SDL side, can make it universal. the build amiberry with Xcode 

You can also build SDL as a Universal library (a single binary for both 64-bit Intel and ARM architectures), by using the build-scripts/clang-fat.sh script.

```mkdir build
cd build
CC=$PWD/../build-scripts/clang-fat.sh ../configure
make
sudo make install```
