### ISSUE TITLE
Amiberry v5.6.1 binary tarball broken on Debian 10.13

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1113]
./amiberry: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./amiberry)
./amiberry: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by ./amiberry)
./amiberry: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./amiberry)

I reported something like this on EAB forum wrt v5.6.0

Note: If I compile from git-master, the amiberry GUI starts but throws SIGSEGV when starting emulation;

```
==13639== Thread 4 render:
==13639== Invalid read of size 8
==13639==    at 0xA5AE1A9: ??? (in /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0)
==13639==    by 0x507E937: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==13639==    by 0x507AEAB: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==13639==    by 0x4A022E: ??? (in /home/gcb/amiberry/amiberry)
==13639==    by 0x2C35BC: ??? (in /home/gcb/amiberry/amiberry)
==13639==    by 0x509EE8B: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==13639==    by 0x5112118: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==13639==    by 0x53C8FA2: start_thread (pthread_create.c:486)
==13639==    by 0x5F5506E: clone (clone.S:95)
==13639==  Address 0x990 is not stack'd, malloc'd or (recently) free'd
==13639== 
==13639== 
==13639== Process terminating with default action of signal 11 (SIGSEGV)
==13639==  Access not within mapped region at address 0x990
==13639==    at 0xA5AE1A9: ??? (in /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0)
==13639==    by 0x507E937: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==13639==    by 0x507AEAB: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==13639==    by 0x4A022E: ??? (in /home/gcb/amiberry/amiberry)
==13639==    by 0x2C35BC: ??? (in /home/gcb/amiberry/amiberry)
==13639==    by 0x509EE8B: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==13639==    by 0x5112118: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==13639==    by 0x53C8FA2: start_thread (pthread_create.c:486)
==13639==    by 0x5F5506E: clone (clone.S:95)
```

I'm not terribly worried by this (I should update my  Debian system), but just reporting in case it matters.

**Comment by solskogen** [comment]
Debian 10 quite old. Debian 12 was just released, which means that even Debian 11 is oldstable.

**Comment by solskogen** [comment]
Does the 'preview' branch compile (and start?)

**Comment by midwan** [comment]
The pre-built binary is compiled using Debian:latest in a Docker container, so there might be a difference there.
Try compiling it from source to check if it works for you.

**Comment by giantclambake** [comment]
Using source tarball  ~ https://github.com/BlitterStudio/amiberry/archive/refs/tags/v5.6.1.tar.gz

//debug amiberry build, output of valgrind


==11466== Thread 4 render:
==11466== Invalid read of size 8
==11466==    at 0xA9021A9: ??? (in /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0)
==11466==    by 0x53D2937: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==11466==    by 0x53CEEAB: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==11466==    by 0x536F46: auto_crop_image() (amiberry_gfx.cpp:1090)
==11466==    by 0x315B46: finish_drawing_frame(bool) (drawing.cpp:4210)
==11466==    by 0x3169C1: render_thread(void*) (drawing.cpp:4646)
==11466==    by 0x53F2E8B: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==11466==    by 0x5466118: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==11466==    by 0x571CFA2: start_thread (pthread_create.c:486)
==11466==    by 0x62A906E: clone (clone.S:95)
==11466==  Address 0x990 is not stack'd, malloc'd or (recently) free'd
==11466== 
==11466== 
==11466== Process terminating with default action of signal 11 (SIGSEGV)
==11466==  Access not within mapped region at address 0x990
==11466==    at 0xA9021A9: ??? (in /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0)
==11466==    by 0x53D2937: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==11466==    by 0x53CEEAB: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==11466==    by 0x536F46: auto_crop_image() (amiberry_gfx.cpp:1090)
==11466==    by 0x315B46: finish_drawing_frame(bool) (drawing.cpp:4210)
==11466==    by 0x3169C1: render_thread(void*) (drawing.cpp:4646)
==11466==    by 0x53F2E8B: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==11466==    by 0x5466118: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.9.0)
==11466==    by 0x571CFA2: start_thread (pthread_create.c:486)
==11466==    by 0x62A906E: clone (clone.S:95)


So..no =)  

Same problem it seems ~ perhaps there's nobody out there still using buster (even though it still has LTS until 06/2024)

Note: this debian 10.13 instance is using nvidia drivers
