### ISSUE TITLE
Floppy drive sounds not working?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1114]
git-master/x86-64/linux

Note: This feature is undocumented in GUI->Sound->helptext ; it is however mentioned in the wiki

To recreate:

As these settings are saved to the currently loaded .uae config file, I chose 2 methods to test;

-Create a ks-13.uae configuration -> this setup just loads kickstart-1.3 ROM with no floppy images loaded, and 'Floppy Drive Sound Emulation is enabled in GUI->Sound->Enable floppy drive sound, using the default suggested volume(?) settings of 67%. After starting emulation, emulation starts, and you're presented with the 1.3 insert disk screen. Expected result is to hear the drive 'click' sound, but nothing is heard ~ if you have the status bar active, you can see the DF0: widget toggling between track 0&1 as might be expected to coincide with the drive click sound, but all is quiet.

-Create a wb-13.uae configuration -> this is pretty much identical to the above, except with a workbench-1.3  .dms image loaded into DF0: ~ after starting emulation, expected result is to hear the floppy disk open sound, followed by disk access sounds as Workbench 1.3 is loaded ~ again via status bar you see this disk activity, but no sound is heard.

A further question ~ when you do enable floppy sounds, and use the 67% value then save the configuration, in the .uae file the values are saved thusly;

```
floppy_volume=33
floppy0=
floppy0sound=1
floppy0soundvolume_disk=33
floppy0soundvolume_empty=33
floppy1=
floppy1sound=1
floppy1soundvolume_disk=33
floppy1soundvolume_empty=33
floppy2=
floppy2sound=1
floppy2soundvolume_disk=33
floppy2soundvolume_empty=33
floppy3=
floppy3sound=1
floppy3soundvolume_disk=33
floppy3soundvolume_empty=33
```

So the sliders associated with the drive sounds, represent volume attenuation, not volume gain? ...ie; if sliders are set to 0%, the values above go to 100 (full attenuation?)

See attached .uae file from first example above for reference.

TIA
[ks-13.uae.gz](https://github.com/BlitterStudio/amiberry/files/11827911/ks-13.uae.gz)

**Comment by midwan** [comment]
@giantclambake 
This feature expects to find the audio samples in order to play them back, as floppy sound.
Specifically, those are normally under `data/floppy_sounds/` and these files are searched for:
- drive_click.wav
- drive_snatch.wav
- drive_spinnd.wav
- drive_spin.wav
- drive_startup.wav

Do you have those files in the expected location?

Regarding the config values, I know it's a bit weird, but I've left them like this to sync with WinUAE (which also does the same thing)

**Comment by giantclambake** [comment]
Yes indeed;

gcb@gallah:~$ ls -l Amiberry/data/floppy_sounds
total 144
-rw-r--r-- 1 gcb gcb 17998 Mar 25  2023 drive_click.wav
-rw-r--r-- 1 gcb gcb 39828 Mar 25  2023 drive_snatch.wav
-rw-r--r-- 1 gcb gcb 20180 Mar 25  2023 drive_spinnd.wav
-rw-r--r-- 1 gcb gcb 20180 Mar 25  2023 drive_spin.wav
-rw-r--r-- 1 gcb gcb 43492 Mar 25  2023 drive_startup.wav

Wrt config values, that's fine ~ it's just a word thing ; 'volume' versus 'attenuation' (and in the audio domain, versus 'gain' =^)

I'll need recheck against the rpi machines (which I got after reporting this wrt x86-64)

**Comment by giantclambake** [comment]
Closing this -- I suspect this had something to do with debian-10.13 at the time of report, and in the months interim I updated (finally) to debian bullseye and latterly to bookworm, and now that I retest this, the problem would seem to have resolved itself.
