### ISSUE TITLE
Amiberry v5.6.1 binary release fails on Debian 12

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1120]
Did a fresh install of Debian 12 to check/test things;

https://github.com/BlitterStudio/amiberry/releases/download/v5.6.1/amiberry-v5.6.1-x86-64-debian.zip

./amiberry: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory

Cause = Debian 12 ships with  libFLAC.so.12.0.0

- Compile from source tarball/git clone works as expected

Note:

"If you want to compile Amiberry from source, you'll need the -dev version of the same packages instead. For example, on Debian-based distros:"

`sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libflac-dev libmpg123-dev libpng-dev libmpeg2-4-dev libserialport-dev`

Actually, to compile Amiberry from source you need;

"_If you want to compile Amiberry from source, you'll need the -dev version of the same packages instead and a working build environment. For example, on Debian-based distros:_"

sudo apt install build-essential libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libflac-dev libmpg123-dev libpng-dev libmpeg2-4-dev libserialport-dev

TIA

**Comment by midwan** [comment]
The x86-64 binaries are built using a docker image, with Debian:latest.
Perhaps that needed an update, so I've just done that. We'll see with the next binaries produced from it :)

**Comment by giantclambake** [comment]
Just confirming builds are now good with Debian:latest again =)
