### ISSUE TITLE
Memory leak when pausing / unpausing emulation.

### ISSUE THREAD

**Issue by broadblues** [BlitterStudio/amiberry#1122]
**Describe the bug**

I've noticed that when the emulation is paused then unpaused that a small amount of memory is lost. If pause  / unpause is repeated eventually there will be insufficient memory to render updates the screen. 

I noticed the issue when testing  my DBUS customisation but I can reproduce it using only the Pause Emulation function in the Controller mappings.  

**To Reproduce**

Start your favourite game and go to the Amiberry GUI ->Custom Controls
Pick an unused button on your controller and set the function to "Pause emulation" 
Start/Resume emulation from GUI
While emulation is running, continually pause and unpause the emulation using the selected button.
Monitor the memory available at each step using a tool such as 'free' 
Free memory drops at each iteration. 
Eventually the available memory gets so low that screen updates stop, but sound continues in the background.

NB: I'm testing this on an OrangePi Zero 2 with 1Ggb mem shared between the CPU and GPU

All memory appears to be restored at program exit

**Expected behavior**

No memory leak :-)0

**Desktop (please complete the following information):**

- OS: Debian 3.0.8 Bookworm with Linux 5.16.17-sun50iw9

OrangePi Zero 2  1Gb RAM

**Comment by midwan** [comment]
I couldn't find any memory leak during Pause/Unpause in my tests here, but I did find a few when opening/closing the GUI. Perhaps those are related.

The ones I found are now fixed :)
