### ISSUE TITLE
WHDLoad always drops back to AmigaDOS window

### ISSUE THREAD

**Issue by wn2000** [BlitterStudio/amiberry#1124]
I upgraded my Amiberry from 3.x to 5.6.1.
Then all WHDLoad lha files stopped working.
It would drop to the AmigaDOS window with no error message shown in the window (just the ">1" prompt).

This is on a Rockchip RK3328 SoC. I built from source.
I've updated the WHDLoad and boot-data.zip binary.

Here is the log:
https://pastebin.com/TU5kfYqW

Would appreciate it if I you can give me some clue.

**Comment by giantclambake** [comment]
//comparative logfile launching same title [amiberry v5.6.1 / x86_64 /debian12] 

CD "Games:AkiraCD32"
WHDLoad SLAVE="Games:AkiraCD32/AkiraCD32.Slave" PRELOAD NOREQ NOWRITECACHE  SAVEPATH=Saves:Savegames/ SAVEDIR="AkiraCD32"

WHDBooter - Saved Auto-Startup to /tmp/amiberry/s/startup-sequence
_WHDBooter - Game: Port 0     : CD32
WHDBooter - Game: Port 1     : CD32
WHDBooter - Game: Control    : JOYSTICK
WHDBooter - Game: Fast Copper: nul
WHDBooter - Game: CPU        : nul
WHDBooter - Game: Blitter    : nul
WHDBooter - Game: CPU Clock  : nul
WHDBooter - Game: Chipset    : AGA
WHDBooter - Game: JIT        : nul
WHDBooter - Game: CPU Compat : nul
WHDBooter - Game: Sprite Col : nul
WHDBooter - Game: Scr Height : 400
WHDBooter - Game: Scr Width  : 720
WHDBooter - Game: Scr AutoHgt: FALSE
WHDBooter - Game: Scr CentrH : SMART
WHDBooter - Game: Scr CentrV : SMART
WHDBooter - Game: Scr OffsetH: nul
WHDBooter - Game: Scr OffsetV: nul
WHDBooter - Game: NTSC       : nul
WHDBooter - Game: Fast Ram   : nul
WHDBooter - Game: Z3 Ram     : nul
WHDBooter - Game: CPU Exact  : nul
WHDBooter - Host: Controller 1   : joy0
WHDBooter - Host: Controller 2   : joy1
WHDBooter - Host: Controller 3   :
WHDBooter - Host: Controller 4   :
WHDBooter - Host: Mouse 1        : mouse
WHDBooter - Host: Mouse 2        : joy0_
Autoconfig board list:
Card 01: '<no name>' no autoconfig 00da0000 - 00daffff.
Card 02: '<no name>' no autoconfig 00600000 - 00a7ffff.
Card 03: 'UAE Boot ROM' no autoconfig 00f00000 - 00f0ffff.

//it appears like whdbooter is not initializing (all the lines in italics)
//I'm not sure if this is normal for ARM builds, but it looks suspicious 

HTH 
Card 04: 'Z2 Fast RAM'

**Comment by wn2000** [comment]
Thanks for looking into this! Very useful info.
I wonder how we could enable debug mode of whdboot.
There's a `whdboot/save-data/Debugs` folder but I did not find any doc on how to use that.

**Comment by giantclambake** [comment]
Ah yes, indeed...that is a debug build (my bad for not checking), but correct ~ compiled with debug=1 will yield more info =)

**Comment by wn2000** [comment]
After a bunch of bisecting, I was able to locate this commit as the failing point:
562380a57aae035a204e1b0df1e087679e71e031

**Comment by wn2000** [comment]
Ok it's due to this code:
https://github.com/BlitterStudio/amiberry/blob/346d096d8478b1bc489bf36c25c18f2ddb1e8ba3/src/osdep/amiberry_filesys.cpp#L54-L64

It seems on my system the `iconv()` call returns an error when the input is already ascii.
So in this case the input is silently dropped.

I'm curious why we even need this function? By adding a printout, it seems all it tries to convert are file/folder names inside `/tmp/amiberry`, like `c`, `s`, `devs`, `.`, `..`, `WHDLoad`, etc.

As a result, replacing this function with
```
output = input;
return;
```
solves my issue.

**Comment by midwan** [comment]
@wn2000 
That function is used to convert between the different codesets (UTF8 and Latin1). It's needed in cases where non-Latin characters are used in the filesystem, as those could lead to unreadable directories/filenames (from the Amiga side).

What error does it throw in your case?
Perhaps we can catch that and use the `input` field in those cases, selectively.

**Comment by wn2000** [comment]
I went back and added more printouts. Turns out it fails at the `iconv_open()` call:
https://github.com/BlitterStudio/amiberry/blob/346d096d8478b1bc489bf36c25c18f2ddb1e8ba3/src/osdep/amiberry_filesys.cpp#L49
`errno` is 22 meaning the requested conversion is not supported.

There definitely needs to be an error checking on the return value of this, which would have saved days of debugging effort.

As to why it fails, I think I'm having a similar issue as this one:
https://bugzilla.redhat.com/show_bug.cgi?id=62103
in the sense that I'm running 32bit binary in a aarch64 environment, where my `/usr/lib/gconv` has 64bit libs.

Btw I don't see my built amiberry link to `libiconv`, and I don't even have `libiconv` in my build environment. Where did it get the `iconv` functions? Are those different from what `libiconv` provides?

**Comment by wn2000** [comment]
Btw according to this:
https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.17/iconv_open.3.html

it should be possible to call
```
iconv_t iconv_ = iconv_open("ISO-8859-1//TRANSLIT", "UTF-8");
```
or
```
iconv_t iconv_ = iconv_open("ISO-8859-1//IGNORE", "UTF-8");
```
to handle non-convertible characters automatically.

**Comment by wn2000** [comment]
> Btw I don't see my built amiberry link to libiconv, and I don't even have libiconv in my build environment. Where did it get the iconv functions? Are those different from what libiconv provides?

I see glibc and libiconv both offer iconv implementation.
Now to figure out how to use libiconv instead of glibc's implementation...

**Comment by wn2000** [comment]
Another thought: If the intension here is to convert utf-8 to latin1 and ignore any unconvertible characters, the solution here can be directly used, without relying on iconv:

https://stackoverflow.com/a/20158473

making it fully cross-platform.

**Comment by midwan** [comment]
I've added the translitarate option in `iconv_open`, hopefully this solves the issue for your case as well.
If Ignore works better, please let me know. I don't have any environment to recreate this, so both options work equally well for me.
