### ISSUE TITLE
No IPF support in macOS M1 pre-compiled bins?

### ISSUE THREAD

**Issue by Luca1991** [BlitterStudio/amiberry#1126]
Hello,
as written in the wiki, I expected IPF support out of the box for pre-compiled macOS M1 package.

**To Reproduce**
1. Boot with an IPF image
2. Error: capsimg.so not found. CAPS/IPF support not available.

**Expected behavior**
I should be able to boot IPF images with pre-compiled packages, as far as I can read in the wiki.

**Screenshots**
<img width="793" alt="Screenshot 2023-09-13 alle 19 08 55" src="https://github.com/BlitterStudio/amiberry/assets/3731220/2b388563-399c-41d1-b101-94924b5ce2a4">

**Desktop:**

- OS: macOS (M1)

- Version: Ventura (13.5.2)

**Extra:**
Just wanted to say thank you :)

**Comment by midwan** [comment]
@Luca1991 
Looks like the required library that provides IPF support is missing/not found in the archive.
This is included indeed with the automated Linux builds, so the wiki is correct for those cases at least.

Unfortunately, I don't have a macOS device to test with here, so those builds are a bit more tricky for me.

**Comment by Luca1991** [comment]
@midwan thank you for your reply. It looks like that capsimg is missing from the macOS 64bit intel package too.

So, if I've understood correctly, the only way to have IPF support is by building from source right? if that's correct, this is not a problem for me.

**Comment by giantclambake** [comment]
"You will need to copy the file above into the same directory your amiberry binary is located, so it can open it on startup."

...bottom of FAQ

**Comment by Luca1991** [comment]
> "You will need to copy the file above into the same directory your amiberry binary is located, so it can open it on startup."
> 
> ...bottom of FAQ

@giantclambake I've asked because apparently this is not the case for macOS. Copying capsimg.so to /Amiberry.app/Contents/MacOS/ has no effect. This was my first try, as I've read the FAQ 😇

**Comment by Luca1991** [comment]
Ok, for anyone interested in, I've a found a workaround:
1. compile capsimg from source
2. copy/move capsimg.so to Amiberry.app/Contents/MacOS/
3. DO NOT start Amiberry from Amiberry.app, instead open a new terminal and navigate to Amiberry.app/Contents/MacOS/ and then launch Amiberry using ./Amiberry 

Using this way the capsimg.so will be loaded and you will be able to use IPF files.

I'll update this issue if I'll find a proper fix

**Comment by giantclambake** [comment]
Ok.... wiki needs to be updated in this regard =)

![glimpse](https://imgur.com/SrtwmNT.png)

I don't see any specific handling for MacOS so you must be falling through to what the wiki examples.

One supposes that needs to be added?

**Comment by midwan** [comment]
> Ok, for anyone interested in, I've found a workaround:
> 
> 1. compile capsimg from source
> 2. copy/move capsimg.so to Amiberry.app/Contents/MacOS/
> 3. DO NOT start Amiberry from Amiberry.app, instead open a new terminal and navigate to Amiberry.app/Contents/MacOS/ and then launch Amiberry using ./Amiberry
> 
> In this way the capsimg.so will be loaded and you will be able to use IPF files.
> 
> I'll update this issue if I'll find a proper fix
> 
> EDIT: just to be clear: I think that the problem is in dlopen. At the moment, my best bet is that the relative path passed as first argument ("./capsimg.so") is not valid in macOS when launching from .app OR when launching Amiberry (mach-o bin) from any other path that is not Amiberry.app/Contents/MacOS/. @midwan can you confirm this? thanks

Thanks for the tests and feedback.
Unfortunately I don't know how this works under MacOS, as I don't use the platform myself. The binaries are provided by others in the community, so I just have a "best-guess" approach on how this should work. It would be great to have someone with more in-depth knowledge help us out here :)

**Comment by Yserra** [comment]
here is the workaround found in the Mac-Greaseweazle community (where you also need capsimg.so to read/write IPF from/to disk): download the pre-compiled CAPSImg library from FS-UAE, another Amiga Emulator on Mac (here: https://fs-uae.net/download#macosx ), then install the CAPSImg.framework subfolder into /Library/Frameworks/ (or ~/Library/Frameworks/). 

Obviously, Amiberry has to be adapted to look for the Library as /Library/Frameworks/CAPSImg.framework/CAPSImg. 
![screenshot_1141](https://github.com/BlitterStudio/amiberry/assets/48497199/958c50c9-3572-46a4-b4fe-c3275a7612ba)
