### ISSUE TITLE
Bookworm 

### ISSUE THREAD

**Issue by steve2611967** [BlitterStudio/amiberry#1137]
Amiberry works fine on rpi 4 with bullseye, but not with  #bookworm.

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by steve2611967** [comment]
Well, installed bookworm, downloaded amiberry and libraries. Clicked on
icon, then execute, execute in terminal, etc comes up, I click execute
nothing happens except for a screen flash. Had it working in bullseye, got
amiga 3.5 workbench running, set up hardfiles.

**Comment by solskogen** [comment]
Oh, I see. Yes, that won't work. What you can do until there's a spesific bookworm build for the release (Raspberry Pi OS bookworm weren't released when the latest amiberry was released) is to go to https://github.com/BlitterStudio/amiberry/actions/runs/6640949663 and download amiberry-rpi4-sdl2-64bit-debian-bookworm  from there.

**Comment by midwan** [comment]
> Oh, I see. Yes, that won't work. What you can do until there's a spesific bookworm build for the release (Raspberry Pi OS bookworm weren't released when the latest amiberry was released) is to go to https://github.com/BlitterStudio/amiberry/actions/runs/6640949663 and download amiberry-rpi4-sdl2-64bit-debian-bookworm from there.

I'm not sure if the action artifacts are visible/downloadable for everyone, but you're welcome to try :) I suspect that only people with access to the repo can download those...

In any case, I'm planning to release a small bug-fix update, which will trigger the new build workflow and produce new binaries for bookworm as well. Just need to find the time to work on it now.

**Comment by solskogen** [comment]
Oh, you're right. Then OP's best bet would be to compile amiberry. It's not that hard, as long as you follow the steps in the README file :-)

**Comment by midwan** [comment]
This is already fixed and tested in the automated builds, so it's going to be part of the next release.

**Comment by steve2611967** [comment]
That's great, thank you Steve
