### ISSUE TITLE
JIT for x86-64  ?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1138]
Yes, I know it's currently unsupported/unavailable with the x86-64 amiberry target, and TBH I vowed not to raise this issue, unless I could clearly identify the lack of JIT on x86-64 constituted a 'real' shortcoming wrt the emulation performance itself ...ie; as my x86-64 machines have CPU speeds of 3GHz or more, they can run something like ClassicWB-P96 at the same speed or better, as running ClassicWB-P96 on the rpi4 with JIT enabled (and in this latter case you need JIT enabled anyway to obtain good performance).

Having said that, there is a difference to be found between the 2 platforms ~ so far, the most obvious case is if one recreates the Pimiga workbench setup, on an x86-64 machine (basically just copy the /home/pi/pimiga/disks directory from the Pimiga dist, into your ~/amiberry/disks location, and recreate the pimiga3.uae settings to suit...ie; you won't have JIT =) When you run the emulation, it all works with one exception -- there is no Workbench background, but windows are as they should be... https://imgur.com/rTjfmy9.png

In fact, I could not find any way to put a pattern/picture on the workbench surface ; the software wasn't complaining, selector dialogs all working, no matter what you did you got grey. I copied the same Pimiga hdd directories over to my rpi4B/4g, to setup the same emulation there -- I quickly found I could recreate the above 'workbench stuck on grey background' scenario, simply by disabling JIT on the rpi4 ~ sure, it boots a bit slower but does get to workbench, but you're stuck with grey background and coloured windows, and no way to change background --- F12 -> enable JIT -> Reset ...emulation boots to workbench, with background picture, and you can effect changes. I'm confused ... which piece of Amiga software is reliant on the host-side emulator having JIT enabled to display workbench background pictures? Does anyone know?...

At any rate, I cannot enjoy the full Pimiga 'experience' running x86-64 hardware, using amiberry in platform=x86-64 guise, due mostly to the lack of JIT support. (I can spark up winuae via WINE and JIT works there...as does the workbench background thing) ~ this gives me pause to ponder, what other Amiga softwares might run better, with x86-64 JIT support.

Ergo, as there's no current ticket lobbying for the case, I raise the question full well knowing a fix many be a long way down the track =)

TIA

**Comment by chrisripp** [comment]
hello, I am testing Amiberry on my Pclinuxos x64, the caffeineOS and CoffinOs distributions are launching well and the host-run is working very well. On the other hand, without jit the A4000 distributions crash. 68060 is not present in the configurations, as well as the jit option. But it's very good work. Well done Team. I will follow your work. Best wishes.

**Comment by midwan** [comment]
@chrisripp 
You may want to try out the `preview` branch also, which has 060 implemented, as well as a bunch of other stuff (it's currently in-sync with the latest WinUAE 5.1.x beta). Still no JIT there, but might help with your crashes.

**Comment by midwan** [comment]
This is now implemented and enabled in the `preview` branch.

**Comment by giantclambake** [comment]
@chrisripp

Any chance you can attach the config.uae file you're using with amiberry for caffeineOS?

TIA

**Comment by giantclambake** [comment]
Gosh....how does one get a 'proper' handle on problems here?...any advice?... I mean beyond the obvious of having to debug the Amiga guest side, as well as the Amiberry process....

Best I can figure it, you need some piece of Amiga software, that breaks so horribly it generates debug on the Amiberry side...

This -->   https://aminet.net/search?query=I+want+to+be+machine

This is the demo I mention above, that causes immediate crash to desktop in `preview` with JIT enabled in x86-86. I've tested it on a few different workbench installs, to try eliminate fancy, RTG, and try to get near 'stock'.... and it behaves reliably bad =)

On x86-64 **no JIT**, it does pop an amiga cli window which reads 'cant cancel env' -- it keeps running playing music but no graphics, eventually it crashes and burns...

On rpi4 (amiberry v5.6.5) with **JIT enabled**, it behaves in the same way... [I'll check this with preview build]

On x86-64 with **JIT enabled** it crashes everything quick as blink ...but at least it leaves a trace.

Although imperfect, I expect similar results as per the first two cases, and not a crash to desktop ...ie; when that demo does eventually crash, you can still F12 and reset the emulation.

[amiberry.log.gz](https://github.com/BlitterStudio/amiberry/files/13612722/amiberry.log.gz)

**Comment by solskogen** [comment]
The demo works fine on preview on the Pi5 at least (no JIT support for aarch64 on the preview branch yet)

**Comment by solskogen** [comment]
No crash on master with JIT on the Pi5 either.

**Comment by giantclambake** [comment]
> The demo works fine on preview on the Pi5 at least (no JIT support for aarch64 on the preview branch yet)
> No crash on master with JIT on the Pi5 either.

@solskogen ..interesting... as midwan has speculated, might be a distro thing ... if you could provide your .uae config that works with aforesaid demo, I can check if there's something erroneous with mine (wrt preview branch, your amiberry.conf file might be interesting as well ;) May even be a rpi4 thing...but as I noted, I'll have to crosscheck the preview later, when JIT is available again in that branch.

..though, it's not that I'm really concerned with differences between ARM platforms ; it's more a case of if it works on one platform with JIT (to any extent), I expect same/similar results with JIT on x86-64....ie; the above case where it starts in 2 scenarios and yet crashes outright on x86-64 only with JIT enabled....the behavior is inconsistent, I really don't care what the demo does when running ~ it failed to start, that's a problem...crashing everything in the process is collateral damage ;)

This --> https://www.pouet.net/prod.php?which=9549

Has my 'spooky' award right now ...starts and runs fine on rpi4 / v5.6.5 / JIT enabled -- starts and runs fine on x86-64 / v5.6.5&preview / JIT **disabled** --  fails to launch at all on x86-64 / preview / JIT enabled  

Yet to find another demo.exe that just quickly blinks the screen and does nothing (Ralph Mellish) ...OTOH there's several titles that fail to launch, and hit an amigados error (suspend/reboot) ~ these same titles work fine on x86-64 master/preview with no/disabled JIT (and on the rpi4 with JIT), and I wonder if this is all somehow related...ie; fail to launch coincidence

Don't get me wrong here ~ when it works, it works really well, and when that is the case proves out my hypothesis in the opening post here : x86-64 users really have been missing out wrt emulation performance with no JIT ;)

Maybe where it might impact most (wrt Amiberry), is when it comes to whdautoloading, and the .lha's XML entry contains the directive `JIT=TRUE` ...I think this was just blithely ignored on x86-64 previously, that will no longer be the case ; I might go find a number of these, just to see if it's all sane... (also need to test on a LFS build)...

**Comment by solskogen** [comment]
Please try with a Raspberry Pi OS bookworm to ensure. The uae config I had was just a standard A1200 with kickstart 3.2.2.

**Comment by giantclambake** [comment]
> Please try with a Raspberry Pi OS bookworm to ensure. The uae config I had was just a standard A1200 with kickstart 3.2.2.

Ahhh... kickstart 3.2.2 .... I'm using 40.68 (ks3.1) ... considering it's mostly amigados errors I'm seeing, I'll have to get some later romfiles and retest ;)

**Comment by giantclambake** [comment]
Observation: For some reason, the audio output volume seems lower on x86-64 with JIT enabled in `preview` ; can anyone confirm?

**Comment by solskogen** [comment]
It worked fine with 3.1 kickstart as well :-)

**Comment by midwan** [comment]
Closing this, as it's already implemented (in `preview`).
I don't think we'll be merging `preview` to `master` anytime soon, considering the performance drop for slower RPI devices. Perhaps we'll separate the versions and leave v5.x as a legacy version, with the old emulation code, and v6.x onwards will be the "next-gen" one. We'll see...
