### ISSUE TITLE
MacOS M1: Blitter can't be saved/used to "Wait for Blitter"

### ISSUE THREAD

**Issue by PoisonAstro** [BlitterStudio/amiberry#1143]
![Uploading Bildschirmfoto 2023-11-04 um 14.11.24.png…]()
**Describe the bug**
I'm going to some old Intro Disks atm and created a Kickstart 1.2 config, setting Blitter to "Wait for Blitter".
However, it always revert to "Normal Blitter" after emulation start. Then I can press F12, set Blitter again and sometimes it works and sometime it revert back to "Normal". Using Quickstart helps but it's only windowed and not fullscreen.

**To Reproduce**

1. Go to 'Chipset'

2. Click on 'Wait for Blitter' 

3. Press Start and wait until emulation start

4. Press F12 and Blitter is back to normal. 

**Desktop (please complete the following information):**

- OS: MacOS Sonoma, M1 Max MacBook Pro

- Version 14.1

**Additional context**
Amiberry Version 5.6.1

Love Amiberry? Please consider supporting it:
Bought you an coffee on Thursday, enjoy :-D

**Comment by giantclambake** [comment]
Just FTR, couldn't recreate this on rpi4/x86-64 ~ created  Kickstart 1.2 config attached

[default-1.2.uae.gz](https://github.com/BlitterStudio/amiberry/files/13258124/default-1.2.uae.gz)

**Comment by PoisonAstro** [comment]
Thank you @giantclambake for your config.
Yes, it works and I've investigated a little further: It happens when I activate both Cycle Exact modes even with your config.
<img width="730" alt="Bildschirmfoto 2023-11-05 um 11 36 53" src="https://github.com/BlitterStudio/amiberry/assets/121714798/12f94095-01a5-4302-90ae-6f84e377eb07">

**Comment by giantclambake** [comment]
I think 'normal' blitter is associated with cycle exact, so this is likely expected behaviour ~ that said, very few Amiga titles actually need the cycle exact settings being enabled.

**Comment by PoisonAstro** [comment]
Thank you very much for your help!
Case closed.
