### ISSUE TITLE
rpi bookworm - libFLAC.so.8: cannot open shared object file

### ISSUE THREAD

**Issue by digitalight** [BlitterStudio/amiberry#1144]
**Describe the bug**
Amiberry binary will not load on Raspberry Pi bookworm 64bit.

**To Reproduce**

Fresh install of Raspberry Pi OS bookworm 64bit desktop.
Install the listed dependancies.  libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-image-2.0-0 flac mpg123 libmpeg2-4 libserialport0

Download and extract [amiberry-v5.6.1-rpi4-sdl2-64bit-rpios.zip](https://github.com/BlitterStudio/amiberry/releases/download/v5.6.1/amiberry-v5.6.1-rpi4-sdl2-64bit-rpios.zip)

Run ./amiberry in terminal

Get the following error:
./amiberry: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory

flac package is confirm installed version 1.4.2

**Expected behavior**
Amiberry screen to appear

- OS: Raspberry pi bookworm (64bit)

- Version 5.6.1

**Additional context**
Maybe flac package has been updated in bookworm and causing unexpected behaviour

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by giantclambake** [comment]
Known issue ~ currently you need compile from the source tarball.

**Comment by midwan** [comment]
Yes, as mentioned above: the binaries from the 5.6.1 release came out before bookworm was released, so they don't work on it. This is already fixed internally with the automated builds, so the next Amiberry release will get binaries running not just on bookworm, but also the last 2 Debian releases as well (bullseye and buster).
But for now, you can compile it manually if you want to run it on bookworm.
