### ISSUE TITLE
Add helptext to GUI -> Priority

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1151]
This text was not yet done (//todo stub) ~ little wonder, it would seem to me to be pretty much self-explanatory in essence.

However an empty panel does not a help button make, so again lean on the Wiki and try to pad out the obvious ... for mine, what an active amiberry does when mouse capture is lost/regained, is likely the top candidate for user tweaking, and I was grappling on how to present that facility whilst keeping it tied to the 'when active' state. I concluded to use the much maligned 'pipe' device to this end, as it tends to make one read 'when active & mouse uncaptured' as a matter of natural eye movement.. 

![ftang](https://imgur.com/9pB57bF.png)

Note: details of 'mouse uncaptured' should be propagated to wiki page.

TIA

For src/osdep/gui/PanelPrio.cpp

```
 bool HelpPanelPrio(std::vector<std::string>& helptext)
{
        helptext.clear();
        helptext.emplace_back(" ");
        helptext.emplace_back("In this panel you can configure the task priority for Amiberry, under different usage");
        helptext.emplace_back("scenarios. In most cases, the default settings work fine here.");
        helptext.emplace_back(" ");
        helptext.emplace_back("\"When Active\" - Set the priority options for when Amiberry is currently active.");
        helptext.emplace_back("     \|");
        helptext.emplace_back("  \"Mouse uncaptured\" - Set what Amiberry does when active and mouse capture is lost.");
        helptext.emplace_back(" ");
        helptext.emplace_back("\"When Inactive\" - Set the priority options for when Amiberry is currently inactive.");
        helptext.emplace_back(" ");
        helptext.emplace_back("\"When Minimized\" - Set the priority options for when Amiberry is minimized.");
        helptext.emplace_back(" ");
        return true;
}
```

**Comment by midwan** [comment]
Fixed with 1dd57cebf3ad3822a66cad20d7ecf88a24a080bc
