### ISSUE TITLE
Query: Can we enable mouse scroll-wheel input for helptext windows?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1152]
It's just an ease of navigation/reading thang wrt longer helptext entries =) It works in other listviews fine...

Possible?

TIA

**Comment by midwan** [comment]
It already works, you just need to click in the Help window once to select it. It scrolls one line at a time.

**Comment by giantclambake** [comment]
Ahh... that wasn't immediately obvious, thanks =)
