### ISSUE TITLE
amiberry v5.6.3 wont run with retropie

### ISSUE THREAD

**Issue by Retro1968** [BlitterStudio/amiberry#1163]
System: Raspberry Pi 4B with RetroPie.

Hello Midwan, at first I want to thank you very much for amiberry v5.6.3.

While I have no problems with amiberry v5.6.3 under raspiOS 64 bit, amiberry v.5.6.3 does not want to run under RetroPie.

So far, amiberry v.5.6.1, which I installed manually, worked without any problems on Retropie. Now I installed amiberry v5.6.3 manually in the same way like always. But it does not work. If i start it the screen gets black and brings me back to the RetroPie-Menue. If I copy the "amiberry" file from version v.5.6.1 into the amiberry v5.6.3 installation, it runs (of course then in version 5.6.1). I find that very strange. With amiberry v.5.6.2 I had the same problem under RetroPie. Since then there must have been some changes that prevents amiberry from starting under RetroPie.

I compile with this command: make -j4 PLATFORM=rpi4-sdl2

Best regards
Retro1968

**Comment by midwan** [comment]
@Retro1968 
I think RetroPie used the Dispmanx version, isn't that still the case?

**Comment by Retro1968** [comment]
Since a while ago an raspios update brought sdl2 to it. I used since that the command: make -j4 PLATFORM=rpi4-sdl2
amiberry v.5.6.1 was compiled the same way.

**Comment by Retro1968** [comment]
To be on the safe side, I just recompiled amiberry v.5.6.1 with this command: make -j4 PLATFORM=rpi4-sdl2
Yes, amiberry v.5.6.1 works with the SDL2 option. :-)

**Comment by midwan** [comment]
I just tested with the latest from `master`, on a fresh installation of RetroPie 4.8.
Both the supplied DMX 5.6.2 and a self-compiled latest from `master` using `rpi4-sdl2` as the PLATFORM option, worked normally for me.

Could you try with the latest changes?

**Comment by Retro1968** [comment]
I just compiled the latest amiberry-master with this command: make -j4 PLATFORM=rpi4-sdl2
Unfortunately without success.

**Comment by midwan** [comment]
Did you try running it from the console, or under EmulationStation?
My tests were from the console directly (just in case)

**Comment by Retro1968** [comment]
I always start the amiberry from the emulation station by clicking on the start file "+start amiberry" and use it to boot to AOS 3.2.2.1. This also works without any problems with amiberry v.5.6.1. Not anymore since amiberry v.5.6.2.

**Comment by midwan** [comment]
Can you try from the console also, please?

**Comment by Retro1968** [comment]
Dont know what you mean. i only can start it in that way.

This is my amiga entry in es_systems.cfg

<system>
    <name>amiga</name>
    <fullname>Commodore Amiga</fullname>
    <path>/mnt/toshiba/roms/amiga</path>
    <extension>.adf .adz .cue .dms .ipf .lha .sh .uae .zip .ADF .ADZ .CUE .DMS .IPF .LHA .SH .UAE .ZIP</extension>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ amiga %ROM%</command>
    <platform>amiga</platform>
    <theme>amiga</theme>
  </system>

**Comment by midwan** [comment]
If you press F4, you'll close ES and get to the console. Then navigate to `/opt/retropie/emulators/amiberry` and launch it from there, usually with something like `./amiberry`. If it works, then it's something to do in combination with ES. If it doesn't work for you still, then it's something else...

**Comment by Retro1968** [comment]
I tried it but it did not work.

**Comment by Retro1968** [comment]
It must be a problem with amiberry. Since v5.6.1 is running on me.

**Comment by midwan** [comment]
I'm on the latest RetroPie also, and the latest Amiberry (freshly compiled from source), and it _does_ work for me however... There must be something we missed.

**Comment by midwan** [comment]
Do you get to the Amiberry GUI at all?

**Comment by Retro1968** [comment]
no. only with amiberry v.5.6.1.

**Comment by Retro1968** [comment]
Please show me your amiga entry in your "es_systems.cfg". I showed you mine above.

**Comment by midwan** [comment]
I doubt it's related to that, but sure... where can I find it?

**Comment by Retro1968** [comment]
/etc/emulationstation

**Comment by Retro1968** [comment]
<command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ amiga %ROM%</command>

**Comment by midwan** [comment]
I have the same:
```
<system>
    <name>amiga</name>
    <fullname>Commodore Amiga</fullname>
    <path>/home/pi/RetroPie/roms/amiga</path>
    <extension>.adf .adz .chd .cue .dms .ipf .lha .m3u .sh .uae .zip .ADF .ADZ .CHD .CUE .DMS .IPF .LHA .M3U .SH .UAE .Z
IP</extension>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ amiga %ROM%</command>
    <platform>amiga</platform>
    <theme>amiga</theme>
  </system>
  ```

**Comment by midwan** [comment]
and I also tried renaming the bundled binary, and putting the sdl2 compiled one in it's place, then launching it from ES. It still works normally here.

Please post your `amiberry.conf` file, and if you have a config named `default.uae`, please attach that one also.

**Comment by midwan** [comment]
Also, please enable logging (you can do that by editing `amiberry.conf` and set the relevant option to `yes`), and try running it from the console if possible. See if any messages show up in the console and in the log.

**Comment by Retro1968** [comment]
[amiga.zip](https://github.com/BlitterStudio/amiberry/files/13369195/amiga.zip)

**Comment by midwan** [comment]
One more thing: since you have a `default.uae`, try renaming that and test again. The GUI should pop-up at least.

**Comment by Retro1968** [comment]
when i delete default.uae the amiberry gui pops up for a very short time before it crashes back to emulationstation

**Comment by midwan** [comment]
Try the steps above, including the logs please. We need more details to understand what's going on, since I cannot recreate it here.

**Comment by midwan** [comment]
Yeah, I didn't see anything weird in amiberry.conf either.
I'll need logs and test running it from the console, in order to see any error output it might throw there.

**Comment by Retro1968** [comment]
[amiberry.log.txt](https://github.com/BlitterStudio/amiberry/files/13369390/amiberry.log.txt)

**Comment by midwan** [comment]
Thanks, now we can see some more info...
It looks like it blew up at some point after initializing one of your joysticks:
```
Joystick #1: e4you e4you Retro Fun
      GUID: 03000000830400000590000000010000
      Axes: 2
      Buttons: 2
      Balls: 0
Joystick #1 does not have a mapping available
```
No further output after that, just the exception. Can you try after disconnecting that specific joystick, to see if it makes a difference? Please generate a new log if it still crashes after that.

**Comment by Retro1968** [comment]
retrofun is a joystick adapter. disconneting it makes amiberry v.5.6.4 work! But why is this error not with amiberry v.5.6.1???

**Comment by midwan** [comment]
I don't know yet, but it's good to narrow it down further. Now we know where the crash is happening, and that it only triggers when that adapter is connected (which explains why it doesn't crash for me).
I'll try some refactoring of the code in that area, to see if it helps fix the situation.

**Comment by Retro1968** [comment]
Ok, thx. for today i say goodnight mate. :-)

**Comment by midwan** [comment]
I have some minor changes in a separate branch, named `controller-refactor`. When you get a chance, please clone that one, compile and see if the result makes any difference in your case.

**Comment by Retro1968** [comment]
Yes, great, that fixed the error. So there are no more crashes with the retrofun adapter. Thank you!
