### ISSUE TITLE
Amiberry sometimes forgets it has a cd iso inserted

### ISSUE THREAD

**Issue by solskogen** [BlitterStudio/amiberry#1165]
It might have something to do with either restarts, or resets of the emulation. I haven't found a clear way to reproduce it (it just happens) - but sometimes I have to eject and insert the iso again for it to be recognized.

**Comment by midwan** [comment]
This might be fixed after e65b56344964e10f756db78b8a44fd751ea164ed - please check on your end?

**Comment by solskogen** [comment]
I was never able to really reproduce this in a way that it's easy for others to reproduce. Closing.
