### ISSUE TITLE
Add option for starting the GUI in fullscreen

### ISSUE THREAD

**Issue by solskogen** [BlitterStudio/amiberry#1170]
The GUI always starts up in window mode when you start amiberry, but is fullscreen when you resume to the GUI IF emulation is started in fullscreen. Please add an option to start amiberry in fullscreen mode from the get-go.

**Comment by midwan** [comment]
Have you checked the option `default_fullscreen_mode` in `amiberry.conf` ?
https://github.com/BlitterStudio/amiberry/wiki/Amiberry.conf-options#default_fullscreen_mode

**Comment by solskogen** [comment]
Either that option doesn't work, or it doesn't controll the GUI.

**Comment by midwan** [comment]
Are you testing this under X11 or Wayland? Because it doesn't apply (for obvious reasons) to KMS

**Comment by solskogen** [comment]
I KMS the gui is always fullscreen :-) I'm talking about X11 and Wayland.
