### ISSUE TITLE
Three-finger-salute stops keyboard from working

### ISSUE THREAD

**Issue by solskogen** [BlitterStudio/amiberry#1171]
3.1 kickstart, Amiga OS 3.9 with boingbag2 installed.
Doing the three finger salute with right windows key, then left windows key and left control (RCtrl = RAmiga on) stops the keyboard from working in emulation after boot. Neither a reset, nor restart button in the GUI fixes it. I have to quit amiberry and start it up again. 
Sometimes hard to re-create. Will test further with other kickstarts and OS.

**Comment by midwan** [comment]
Does it come back if you press any of those modifier keys again? I'm thinking it might get "stuck" in the down state, and it's not reverted until it's pressed again.

**Comment by solskogen** [comment]
Same happens with 3.2.2 (I've configured a A4000T for this, not sure if that's relevant or not)
