### ISSUE TITLE
Booting some WHDLoad games fails with error about CPU

### ISSUE THREAD

**Issue by midwan** [BlitterStudio/amiberry#1183]
hey guys.  so I have tested things fully now and i think there is an issue running WHDLoad games with the latest version of amiberry.  I compiled an sdl2 version of 5.6.4 and the dispmanx version.  both open the GUI and can also get to the kickstart screen, but they will not load WHDLoad games.  I installed an old version 3.3 and it works fine.  if I change the amiberry file to either of the other two compiled versions is fails to run and hangs or displays a processor error.  I have a log for each build i have tested which are attached. the amiberry.log.panza was using the dispmanx build, the amiverry.log.stunt was using the sdl2 build.  I have used the same kickstarts etc in all cases.  is there anything in the logs which would suggest why its not working?
[amiberry.log.stunt.log](https://github.com/BlitterStudio/amiberry/files/13401787/amiberry.log.stunt.log)
[amiberry.log.panza.log](https://github.com/BlitterStudio/amiberry/files/13401788/amiberry.log.panza.log)

_Originally posted by @oooMaNiXooo in https://github.com/BlitterStudio/amiberry/issues/1179#issuecomment-1817698065_

**Comment by giantclambake** [comment]
All I notice in both logs, is that the correct ROM is identified;

WHDBooter - Host: A600 ROM Available

....and yet, whdbooter is loading an A1200 ROM;

ROM loader.. (<none>)
Known ROM 'KS ROM v3.1 (A1200)' loaded

Also,  why are the ROM symlinks recreated in each log? AFAIK that should only happen once, after populating kickstarts with ROMs, and clicking Rescan?

**Comment by oooMaNiXooo** [comment]
Yes I tried to rescan paths just in case something was wrong but it made no difference. I am unable to load anything with WHDLoad but if I use v3.3 it works immediately. One of the new builds just hangs on a black screen, the other build thrown an expected CPU type error and I have to quit amiberry. I can try and grab the specific message. If you try either new build on an rpi3 with WHDLoad I suspect you will see the issue.

**Comment by midwan** [comment]
I cannot recreate this I'm afraid.
I've tested both RPI4 and RPI3 devices on RetroPie, both DMX and SDL2 versions.
After getting the latest sources from `master` and compiling them, I've updated the WHDLoad XML (through Amiberry itself), and launched the same games.

Both run fine, using the A600 config as designed. No errors shown in the console here.

**Comment by oooMaNiXooo** [comment]
Ok I’ll wipe the card to try again. Are you installing amiberry from the menu then compiling the latest version and swapping the program file? Could it be my process if flawed? I have been installing it from source then cloning git, building the new file and replacing the installed one. Is that the correct process?

**Comment by midwan** [comment]
I also installed the provided binary first, to put the required dependencies in place.
Then I cloned the repo, compiled manually and replaced the binary.
After that, I launched it once, updated the XML and Controllers file (the second one is not needed, but I always do it just in case).
Then I run the games - no issues so far.

**Comment by oooMaNiXooo** [comment]
Ok thanks you, I will try exact process again and report back:) let’s hope it works as yours does

**Comment by giantclambake** [comment]
I'm using the same methodology as midwan describes ~ I can't recreate the problem here on the rpi3A+

./amiberry --autoload StuntCarRacer_v1.3_0222.lha

Logfile attached. 

[amiberry-stuntcar.log.gz](https://github.com/BlitterStudio/amiberry/files/13402903/amiberry-stuntcar.log.gz)

**Comment by oooMaNiXooo** [comment]
Thanks guys I will start fresh and do exactly the same. Assume you are also installing the Dev libraries to allow compilation?

**Comment by midwan** [comment]
> Thanks guys I will start fresh and do exactly the same. Assume you are also installing the Dev libraries to allow compilation?

Those are installed by the Retropie Setup script, when you install Amiberry with it.

**Comment by oooMaNiXooo** [comment]
Ok thanks. And the kickstart Roms have not changed since 3.3 I assume?

**Comment by midwan** [comment]
> Ok thanks. And the kickstart Roms have not changed since 3.3 I assume?

Nope. There are newer ones supported, but those don't affect WHDLoad (and it doesn't matter if you don't have them). The ones that _do_ matter are documented in the wiki: https://github.com/BlitterStudio/amiberry/wiki/Kickstart-ROMs-(BIOS)

**Comment by solskogen** [comment]
Check the CRC of your kickstart rom files, perhaps @oooMaNiXooo ? One of them might be corrupt.

**Comment by oooMaNiXooo** [comment]
Yes I’ll double check all hashes thank you:)

**Comment by oooMaNiXooo** [comment]
hey guys, sorry for the delay been mad busy today but also taken me some time to run through the tests.  I will be honest I am at the point of giving up on this as it just will not work.  I have followed the steps above to the letter, but no WHDLoad games will start - just hangs on a black screen with a cursor in the corner.  I have not tried SDL2 this time as I have not had time, but I can if you think its worth it?  I am able to start amiberry then start the emulator without a game and i get to the kickstart screen for various different rooms, so they seem fine and pass CRC.  I have tried two different sets anyway.  Only think I have noticed is that all the games I have tried are attempting to launch with the A1200 kickstart.  That does not seem right for older games like buggy boy and IK+.  I had these back in the day and I am sure they were A500?  I could download an .adf game or two to test that out, but honestly I am out of ideas here.  I do feel this is am issue with the newer version of amiberry as v3.3 works fine, as soon as I goto anything newer it fails, leaving all other components in place.  I have not even installed the control black drivers this time, just amiberry and still no luck.  I can share the logs if it will help but they look the same as last time.  so frustrated with it as never had issues in the past.  Any help you can suggest guys?

**Comment by oooMaNiXooo** [comment]
i think it may be the fact its trying to use A1200 for everything that's the issue.  Just tested Stunt car racer ADF, selected A1200 and I get the same hang, change it to A500 and it works fine.  Does that help in any way?

**Comment by midwan** [comment]
Yeah, the error _is_ coming up because the A1200 ROM is used, instead of the A600 one.
But it still doesn't explain _why_ that is happening, considering we don't see this behavior elsewhere. 
A lot of things have changed since 3.3, so it's not really a good comparison there. 

There was a change in logic at some point (several versions ago), to use an A600HD (kick 2.05) config instead of A500 one, for non-AGA games, which seemed to work better. But besides that, there haven't been many changes in that area lately.

**Comment by oooMaNiXooo** [comment]
Interesting. I assumed each game had the settings stored within the LHA file and also the main WHDload database. Is there anything I have which may be over riding that co figuration? Just seems off that’s it’s trying A1200 for everything.

**Comment by midwan** [comment]
It certainly is strange, and I am guessing it's some rare scenario of which ROMs are available that triggers this.
From a comparison of the logs, I see that you don't have `kick39106.A1200` in your system, for example. It's not normally required, and it should work without also, but if you have that around can you try adding it, just to test?

**Comment by midwan** [comment]
@oooMaNiXooo 
Can you please test with the latest from `master`, after the commit I made above?

**Comment by oooMaNiXooo** [comment]
yes i will try and now.  I have copied the rom file in (found it online), however the md5 is different so it may not be correct

**Comment by midwan** [comment]
No need for that ROM, I tested without it here and I didn't run into the issue. But the above commit might help.

**Comment by oooMaNiXooo** [comment]
no better i am afraid :(  What i did notice is that if I delete all the BIOS files aside from KS1.2 and 1.3, it boots to a DOS screen and stops.  As soon as I put the A1200 BIOS file there is uses it and hangs.  Its as though its not selecting the correct BIOS file for some strange reason.  I have checked the MD5 for all my BIOS files and they are defo correct...this is SO strange :(

**Comment by oooMaNiXooo** [comment]
although now its selecting KS ROM v3.1 (A4000)

**Comment by giantclambake** [comment]
Not being familiar with the retropi setup, I had a quick look at this today (using amiberry-5.6.3)

@oooMaNiXooo  -- are you updating the whdload/* content? This would be /opt/retropie/configs/amiga/amiberry/whdboot/* on retropi

**Comment by oooMaNiXooo** [comment]
Hi:) I don’t believe I have made any changes in that folder. Just install, copy bios then copy roms and test. Are there required changes in there? I know there are kickstarts required but I think I read that’s covered by Amiberry but I could have imagined that lol:)

**Comment by midwan** [comment]
@oooMaNiXooo 
It's worth doing a cleanup there after the latest update, to allow Amiberry to regenerate the symlinks. Then do a Rescan from the GUI, then test again.

**Comment by oooMaNiXooo** [comment]
Hi Guys, So I "Think" we may have a solution here.  Checked everything again and went through the wiki on this page https://github.com/BlitterStudio/amiberry/wiki/WHDLoad-Auto-booting, where I spotted the line below.

The WHDLoad booter will use an A600HD (Kickstart 2.05) config for OCS/ECS titles, and an A1200 (Kickstart 3.x) config for AGA titles. These kickstarts are therefore essential for the booter to work.

It is also mentioned here https://github.com/BlitterStudio/amiberry/wiki/Kickstart-ROMs-(BIOS)

I have been using the reference table here for the required BIOS list, https://retropie.org.uk/docs/Amiga/.  It lists Kickstart v2.04 rev 37.175 but NOT 600HD (Kickstart 2.05).  Luckily I have this BIOS so I copied it over and have managed to run two games that were previously trying to launch using A1200 or A4000.

This is obviously my issue and somewhat embarrassing, however it seems there may be a gap in the documentation on the Retropie side?  This seems to tie in to some comments above around logic changes and as I had not realised that specific BIOS was required I had not copied it, and therefore nothing was working.  I can only apologise for missing this, but its maybe worth a doc review on the Retropie side to ensure it aligns with the good docs on this site.

Thanks to everyone for providing so much help, and despite my incompetence I do seem to have helped to identify a bug or two so hopefully its not been a total waste of time!.  I will test further but things are looking promising at this stage :)

**Comment by cmitu** [comment]
> [](https://github.com/BlitterStudio/amiberry/wiki/Kickstart-ROMs-(BIOS))
> 
> I have been using the reference table here for the required BIOS list, https://retropie.org.uk/docs/Amiga/. It lists Kickstart v2.04 rev 37.175 but NOT 600HD (Kickstart 2.05). Luckily I have this BIOS so I copied it over and have managed to run two games that were previously trying to launch using A1200 or A4000.

The RetroPie Amiga emulation page mentions the Kickstart ROMs only for the `libretro` PAUE core, for Amiberry we provide a direct link to the Amiberry [Wiki page](https://retropie.org.uk/docs/Amiga/#bios) for Kickstart ROMS.

**Comment by midwan** [comment]
@oooMaNiXooo 
Great news, thanks for confirming the solution.

This actually brought up an interesting scenario. Amiberry shouldn't fail in such cases, but rather fallback to the A1200 config properly. Even if that means reduced compatibility for some titles which required 68000 and slower speeds, at least they will still run. Perhaps there should also be some mention about these missing ROMs when you do a Rescan, to improve it further.

So in the end, it's all for the best! :)

**Comment by midwan** [comment]
The new commit above should help in such cases, by gracefully falling back to an A1200 config if the A600HD (2.05) Kickstart ROM is missing. Also, it will log that this happened in the logfile (if enabled), to help with troubleshooting.

**Comment by sittingduck77** [comment]
I'm having the exact same problem as the OP, so I'm now in the process of making sure I have the correct kickstarts - which of these are correct? (there's conflicting info about the 2.04 and 2.05 versions). Thanks.

https://github.com/BlitterStudio/amiberry/wiki/Kickstart-ROMs-(BIOS)
https://github.com/BlitterStudio/amiberry/wiki/Using-Amiberry-WHDBooter-with-RetroPie-(Step-2)

**Comment by midwan** [comment]
A600HD - Kickstart 2.05 is used for OCS/ECS titles, if found.
For AGA titles, the A1200 3.1 Kickstart is used (if found) instead.

**Comment by midwan** [comment]
2.04 is not used in this process.
Both 37.350 and 37.300 will be searched for, in that order. If either one exists, then we consider the A600HD (2.05) ROM to be available and proceed accordingly.
