### ISSUE TITLE
Pi5 64-bit video garbled but emulation running

### ISSUE THREAD

**Issue by pjft** [BlitterStudio/amiberry#1189]
**Describe the bug**
Video is garbled, even though the emulator is running in the background. On the Pi5, using the binaries, I just get static garbled video all over, even though the game is running. In fact, if I try to pause it and access the GUI, it briefly shows the actual frame it's supposed to be rendering (or the GUI) for a split second. 

**To Reproduce**
Simply run the aarch64 rpi5 binaries (on my device, which I know doesn't give a lot of details unfortunately). I have simply installed the Raspberry Pi OS 64-bit lite image from the official site, and updated all packages. Then installed RetroPie. This happens both when compiling from source as well as with the binaries downloaded from the Releases section.

**Expected behavior**
Well, the video should render as before.

**Screenshots**
Here's a short video showcasing what I'm seeing. The audio keeps running. The frame that shows up is when I enter and exit the GUI.

https://github.com/BlitterStudio/amiberry/assets/22025709/93b52e3c-b6cc-4465-a311-5041f19514b4

**Desktop (please complete the following information):**

- OS: Bookworm

```
Linux arcade5 6.1.0-rpi6-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux
```

/boot/config.txt file:

```
# For more options and information see
# http://rptl.io/configtxt
# Some settings may impact device functionality. See link above for details

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Additional overlays and parameters are documented
# /boot/firmware/overlays/README

# Automatically load overlays for detected cameras
#camera_auto_detect=1

# Automatically load overlays for detected DSI displays
#display_auto_detect=1

# Automatically load initramfs files, if found
auto_initramfs=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
#max_framebuffers=2

# Don't have the firmware create an initial video= setting in cmdline.txt.
# Use the kernel's default instead.
disable_fw_kms_setup=1

# Run in 64-bit mode
arm_64bit=1

# Disable compensation for displays with overscan
disable_overscan=1
overscan_left=0
overscan_right=0
overscan_top=-24
overscan_bottom=-24

hdmi_group=1
hdmi_mode=16

disable_splash=1

# Run as fast as firmware / board allows
arm_boost=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1
```

I tried it without the hdmi_ lines, as well as with the default max_framebuffer lines (that, in my setup, is commented out).

**Additional context**
Not a lot more. I'm just happy to help with whatever I can. It just seems weird, but I cannot really figure out what else to try out.

Thanks.

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by midwan** [comment]
Can you please attach your `amiberry.conf` file as well?

**Comment by pjft** [comment]
Of course, apologies!

```
Quickstart=1
read_config_descriptions=yes
write_logfile=no
scanlines_by_default=no
swap_win_alt_keys=no
gui_joystick_control=yes
use_sdl2_render_thread=no
default_open_gui_key=
default_quit_key=
rotation_angle=0
default_horizontal_centering=yes
default_vertical_centering=yes
default_scaling_method=-1
speedup_cycles_jit_pal=10000
speedup_cycles_jit_ntsc=6667
speedup_cycles_nonjit=256
speedup_timelimit_jit=-5000
speedup_timelimit_nonjit=-5000
speedup_timelimit_jit_turbo=0
speedup_timelimit_nonjit_turbo=0
path=/opt/retropie/emulators/amiberry
config_path=/opt/retropie/emulators/amiberry/conf/
controllers_path=/opt/retropie/emulators/amiberry/controllers/
retroarch_config=/opt/retropie/emulators/amiberry/conf/retroarch.cfg
rom_path=/opt/retropie/emulators/amiberry/kickstarts/
ROMs=9
ROMName=KS ROM v3.1 (A1200) rev 40.68 (512k) [391773-01/391774-01]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/Kickstart 3.1 (40.068) (A1200) (Commodore) (1993).rom
ROMType=256
ROMName=CD32 extended ROM rev 40.60 (512k)
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/cd32ext.rom
ROMType=1024
ROMName=CD32 KS ROM v3.1 rev 40.60 (512k)
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/cd32kick31.rom
ROMType=512
ROMName=KS ROM v1.3 (A500,A1000,A2000) rev 34.5 (256k) [315093-02]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick13.rom
ROMType=256
ROMName=KS ROM v2.04 (A500+) rev 37.175 (512k) [390979-01]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick20.rom
ROMType=256
ROMName=KS ROM v3.1 (A500,A600,A2000) rev 40.63 (512k)
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick31.rom
ROMType=256
ROMName=KS ROM v3.1 (A1200) rev 40.68 (512k) [391773-01/391774-01]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick40068.A1200
ROMType=256
ROMName=Freezer: HRTMon v2.37 (built-in)
ROMPath=:HRTMon
ROMType=524291
ROMName= AROS KS ROM (built-in) (1024k)
ROMPath=:AROS
ROMType=256
MRUDiskList=0
MRUCDList=0
```

For what it's worth, I tried changing:
- default_scaling_method
- default_horizontal_centering
- default_vertical_centering
- use_sdl2_render_thread

but it didn't seem to change anything.

Sorry for the trouble, and happy to test out other things here.

**Comment by cmitu** [comment]
Sounds _very_ similar to https://github.com/libsdl-org/SDL/issues/8579.

**Comment by solskogen** [comment]
RetroPie is not supported on bookworm and therefore not supported on the Pi5. IIRC RetroPie have their own SDL and even perhaps Mesa package which is not compatible with bookworm. 
On a standard Raspberry Pi OS amiberry works without any problem on a Pi5.

**Comment by midwan** [comment]
@pjft 
Did you try running Amiberry on a clean system (RPIOS before you install RetroPie)? Just make sure you install Amiberry's requirements first, of course (they are all mentioned in the Readme of this repo).

**Comment by pjft** [comment]
Hi @midwan . Thanks for the response and for encouraging the test. Actually, I have some updates from testing things from scratch.

It all works correctly when installed from scratch, and even after installing RetroPie - as I've come to test. It seems, however, that it doesn't work well when we launch it from within EmulationStation, which means we have to look into it on our end. 

I'll close the issue here for now, and go back to working on our side of things. Thanks for keeping up this great project, and for the prompt responses everyone! It is indeed very similar to what @cmitu reported above, but since it runs well when running from the terminal it might mean there's something different at play here.

Thank you.

**Comment by midwan** [comment]
@pjft 
Thanks for confirming! :)

**Comment by pjft** [comment]
Not at all - sorry for the false issue report.

**Comment by pjft** [comment]
Apologies, let me reopen this as there's a small nuance here you may be able to point me in the right direction for. I was slightly incorrect in my previous assessment, so let me add to it.

The issue actually happens when launching the game with --autoload or -G (i.e. directly to the game, not going through the GUI). 

When amiberry starts by showing the GUI first, either by removing -G or by just setting the disk to a file, it runs as expected.

Any thoughts on _what_ might be causing this, or what could I look into, in this case? Happy to tweak the code as needed and compile it on my end (which I probably will, but thought I'd ask it here first :) ).

**Comment by pjft** [comment]
Oh wow, spot on!

Now, what's really weird is that it shows as disabled by default. Enabling it doesn't make a difference.

But disabling it afterwards does result in the garbled video. Weird - maybe there's something on the vsync setting that makes the default not result in the same behavior as _explicitly disabling it_. 

Still, I'll check if, for the time being, adding the vsync flag explicitly makes a difference and serves as a workaround.

Thank you for the hint! I'll also look at the code later just in case something comes up.

**Comment by pjft** [comment]
Will do. To be clear, on the installation from scratch, running without vsync does cause the same issues, so this is a great find. I'll get back to you as I find things. For now, forcing vsync on is a suitable workaround.
