### ISSUE TITLE
[docs] Can wiki/GUI:-IOPorts be updated please?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1192]
Currently ;

>Sampler
>
>Select a recording device to use as an emulated Sampler. If you don't have any recording devices in your system, none will show up in >the dropdown here.

That's not really correct is it (?), and it's somewhat a misnomer wrt 'recording device', which here doesn't actually exist ...ie; we're not actually using the (default) 'capture' element of the underlying sound API/device (alsa, pa) --- AFAICT the 'recording device' is an sdl_audio tap, on the default system _output_ device, and also lists any other sound device (outputs) available that you can choose from  ...ie; to 'not have any recording devices', would infer you're playing on HW with no audio out?  =) 

On this system for example, my USB3 video capture box creates it's own alsa output (playback) device, and I could use it as my Amiga guest sampler input source..note, the evga box is audio source only, no mixer elements.

![x3](https://imgur.com/sNR5uQh.png)

Ergo... if you've got a system audio output device, you always have an emulated Amiga sound recording device in effect.

Thus, the above description of 'Sampler' could be more clearly explained..something like...

>Select the desired system audio device, to be used for the emulated Sampler input source. In most cases, the `Built-in Audio Analog >Stereo` device is available for this purpose ~ this means any audio you play on the host system, will be available at the emulated >Sampler inside the Amiga environment. If you have more than one audio device in your system, ie; USB capture box, headsets with >mic etc, they will be listed in the dropdown here as well.

...or such'n'similar?

TIA

**Comment by midwan** [comment]
@giantclambake 
The list there will be populated by whatever _recording_ devices SDL2 detects. Those can be microphones, Line-In devices or anything else that presets itself to the system as such.

**Comment by giantclambake** [comment]
...doh! ... copy that ....hitting the TO/GA button ....

**Comment by giantclambake** [comment]
...m'kay, this is somewhat of a mire ... but on the go around, I got a better sight of the runway...

...on the rpi4, you don't have any audio capture device period, so in this context, 'recording device' is IRL the (probably USB but could also be a HAT) the actual device, you plug into the rpi4...that enables audio capture... and for example, a USB headset (with mic) presents itself like this;

![a1](https://imgur.com/4EFyLmh.png)

![sound panel](https://imgur.com/QBtVgZO.png)

...on your typical x86-64 desktop machine, by default you will have audio capture devices ...on this box, I have front/rear mic, line in, plus the mix monitor capture. Of course, Amiberry doesn't allow for me to select the required input source (aka. recording device)...which could be a mic, some external device connected via line in ...or the 'virtual' device of the mix monitor capture ..ie; no physical 'recording device' required ;)

![a2](https://imgur.com/cfdoHnS.png)

![a3](https://imgur.com/a9rJDx2.png)

...same device is presented in both Sound & IO Ports panels. 

What should ideally happen here wrt x86-64 machines like this, is that the default device is selected in GUI ->Sound, and in the dropdown list for GUI -> IO Ports -> Sampler, would be the entries `default: Front Mic: 0`, `default: Rear Mic: 0`, `default: Line: 0 `...etc. In audacity for instance, it is these entries that are called 'Recording: Devices' .... =) However, I don't see that sdl2 can provide this? (probably comes from libasound2)

![a4](https://imgur.com/dAOWFl9.png)

In any event, wiki/GUI:-IOPorts -> Sampler: doesn't really spell this out ....I mean, sure, it's likely to be one of the most unused functions? I have to wonder....(if it were that, and nobody would miss it, stick 'protection dongle' in ROM, serial port in expansions, delete IO Ports altogether, which allows Virtual Keyboard to fit side-panel)...(yes, it still bugs me the side panel menu is obscured at the bottom.. lol.. =)....but clearly, there's disparity between ARM & x86-64 here.

Obviously I've been looking at improving GUI->IO Ports->helptext and here, stumbled into confusion. I actually wonder if anyone uses the serial port either, honestly I do. I think of it as an 'expansion' anyway, if only because all the other Amiga I/O is being emulated ; having to use a hardware uart in that case would be an expansion... anyhoo....

...I'll give it some more thought...

**Comment by giantclambake** [comment]
Ok.... lets see if we can collate some data -- https://eab.abime.net/showthread.php?t=116370

**Comment by midwan** [comment]
Closing this as it doesn't need to be an issue. We can have a discussion about it, and if something comes out from there, we'll create an issue for that.

**Comment by giantclambake** [comment]
Read my mind  ;)
