### ISSUE TITLE
No Floppy Drive sound MacOS Sonoma

### ISSUE THREAD

**Issue by PoisonAstro** [BlitterStudio/amiberry#1203]
**Describe the bug**
Can't enable Floppy Drive Sound Emulation

**To Reproduce**

1. Enable Floppy Drive Sound

2. Start Emulation

3. Press F12 and the setting is disabled

**Expected behavior**
Sometimes I need the Floppy Drive Sound for various reasons.

**Screenshots**

**D
<img width="1090" alt="Bildschirmfoto 2023-12-12 um 13 24 38" src="https://github.com/BlitterStudio/amiberry/assets/121714798/2c155c63-3444-4a4f-86f8-46ee20df5845">
esktop (please complete the following information):**

- OS: [e.g. Debian]
MacOS

- Version [e.g. 5.4]
- 14.2 Sonoma

**Additional context**
Amiberry 5.6.4 downloaded directly from GitHub (pre compiled package)

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by midwan** [comment]
@PoisonAstro 
Do you mean you cannot enable the Checkbox, or that the sound doesn't play when you do?
Can you post your whole config please? The checkbox can only be enabled if you have at least DF0: enabled in the Floppy drives.

**Comment by PoisonAstro** [comment]
I enable the Checkbox, start emulation (Quickstart) and there's no floppy sound.
I press F12 and the checkbox is disabled again.

[amiberry.txt](https://github.com/BlitterStudio/amiberry/files/13786621/amiberry.txt)

**Comment by PoisonAstro** [comment]
@midwan 

I've activated the log and I got this.
Path is correct but I wonder if it's case sensitive?

The .wav files are working when I click on them. 

<img width="809" alt="Bildschirmfoto 2023-12-28 um 20 26 35" src="https://github.com/BlitterStudio/amiberry/assets/121714798/06d52b5d-3f46-4eb0-af26-0fcdfecda13a">

**Comment by midwan** [comment]
I checked, and the paths are hardcoded - so it will fail under macOS, where those paths are different (and the filesystem is case-sensitive).

I'll get that fixed.

**Comment by midwan** [comment]
@PoisonAstro 
Please test after the latest updates today, and see if it works as expected now
