### ISSUE TITLE
Installing latest version of Amiberry (5.6.5) fails

### ISSUE THREAD

**Issue by Realinferno** [BlitterStudio/amiberry#1205]
**Describe the bug**
I currently emulate an Amiga on my Raspberry Pi 4B (4GB), running Raspberry Pi OS Lite (64-bit, Bullseye) and Amiberry 5.6.4. 

I wanted to install the newest version of Amiberry (5.6.5), but the installation fails after a few seconds. I did install libportmidi (by typing the following in the command line: sudo apt install libportmidi-dev). Perhaps this is not enough and I need to do something else to properly install libportmidi?

**To Reproduce*
Install libportmidi (by typing the following in the command line: sudo apt install libportmidi-dev).
After rebooting, install newest version of Amiberry (5.6.5) via HstWB Installer (in command line type "hstwb" to go into the HstWB installer menu, then select: 3 setup -> 2 Emulators -> 2 -> Amiberry -> 2 Install Amiberry -> 1 Raspberry Pi 4 / 400 -> 2 64-bit -> 1 SDL2 -> 1 Stable (master) -> 2 Specific version -> 1 v5.6.5).

I had no problems with installing previous versions of Amiberry via HstWB Installer (for 5.6.0 I did have to install libserialport by typing in the command line "sudo apt install libserialport-dev" -> then it went fine!)

**Screenshots**
The installation breaks of in a matter of seconds, but I was able to take the following (somewhat blurry) screenshot of the installation process: 
![image](https://github.com/BlitterStudio/amiberry/assets/143931784/c69d29d4-9e27-4089-985d-28347252f802)

**Desktop (please complete the following information):**

- OS: Raspberry Pi OS Lite 64-bit

- Version 11 (Bullseye)

**Comment by giantclambake** [comment]
I just had a look at this, manual compile from github master ~ it seems the v5.6.5 Makefile expects to find cmake

At a guess, that's likely missing? Try `sudo apt install cmake` and retry.

**Comment by midwan** [comment]
I forgot to mention it in the release notes: `cmake` is also required, as the bundled `munt` library needs it to compile.

I'll update the notes and the main Readme accordingly!

**Comment by midwan** [comment]
Release notes and Readme updated. Thanks for bringing this up, @Realinferno

**Comment by Realinferno** [comment]
Thanks for the swift replies! I just installed cmake, rebooted and then tried to install amiberry 5.6.5 again. Unfortunately, the installation still fails (apparently, a certain directory does not exist). See the following screenshot:
![IMG_0623](https://github.com/BlitterStudio/amiberry/assets/143931784/4de5fab7-2f8c-455d-a060-8c3b375f59dc)

Thanks for your help!

**Comment by midwan** [comment]
@Realinferno 
Can you try installing `ninja` (it might be named `ninja-build` in some distros) as well?

**Comment by solskogen** [comment]
That's a error coming from "make clean", no reason to worry about it. I've
fixed it in master.

**Comment by Realinferno** [comment]
I just installed ninja-build and (after reboot) tried to install Amiberry 5.6.5 again. I still got the same error. @solskogen you state it is an error from “make clean” that you will fix in the master. Has this already been done?

I appreciate the support!

**Comment by midwan** [comment]
It looks like your script is trying to do a `make clean` before it actually builds anything.
This fails because the cmake `build` directory doesn't exist yet, since you never did any build before (it will be created the first time to trigger a new build for `mt32emu`, part of Amiberry now).

I suggest you drop to the console, then follow the instructions from the readme to do a build for your platform.
After you do that once, it should work from that script also.

**Comment by Realinferno** [comment]
Hi midwan,

Thanks for the suggestion. Could you perhaps be a bit more specific? I’m not an expert in this field. Which readme are you referring to? Of cmake? How do I make a build for my platform?

Sorry for the noob questions.

**Comment by midwan** [comment]
@Realinferno 
The main readme on this repo: https://github.com/BlitterStudio/amiberry ;-)
Check near the bottom, where it says how to compile. After the clone part, of course.

**Comment by Realinferno** [comment]
Ah, I completely misunderstood. Sorry! I compiled Amiberry from console. This went without any problems. I then installed Amiberry 5.6.5 via HstWB installer. This time, everything went fine!

So, problem solved! I’m curious about the MIDI emulation. Will try that in the coming days.

Thanks for all your hard work on Amiberry and your support!

**Comment by midwan** [comment]
Great, nice to see you got it working!
