### ISSUE TITLE
You can’t use this version of the application “Amiberry” with this version of macOS

### ISSUE THREAD

**Issue by ckrokosh** [BlitterStudio/amiberry#1207]
Hello,

I am using a Mac Studio M2 Max running Ventura 13.6.3. When I download the M1 Version (5.6.5) of Amiberry the icon has a white circle over it. When I try to launch it i get the following pop up: "You can’t use this version of the application “Amiberry” with this version of macOS"

Is the M1 version Sonoma only? The intel build seems to work.

Thanks.

**Comment by solskogen** [comment]
Have you looked at the FAQ?

**Comment by ckrokosh** [comment]
Only thing I saw in the FAQ was "Q: Mac OS M1 App is broken. Why?"

I did run the xattr command but I believe this is a different issue. Normally the prompt would be "...app is broken move to trash"

The prompt I'm getting is telling me Amiberry won't work with this version of MacOS. The prompt has an ok button and an upgrade button. The app icon also has a faded white circle with a line through it which normally indicates an unsupported architecture. Ie: a 32 bit app.

**Comment by solskogen** [comment]
Can you try downloading it with wget instead?

**Comment by ckrokosh** [comment]
Not sure how to use wget.

I did manage to compile for M1 from source and it is working good.

**Comment by midwan** [comment]
@solskogen 
The intel version is built on Github runners, but they don't have any Apple Silicon runners available yet. Once they become available, this should be a non-issue.

Currently, the M1 binary is kindly built by @solskogen here, and uploaded after the release is prepared.
