### ISSUE TITLE
riscv64: Build fails with "collect2: fatal error: cannot find ‘ld’"

### ISSUE THREAD

**Issue by MichaIng** [BlitterStudio/amiberry#1213]
**Describe the bug**
I was excited seeing #1127 and want to test Amiberry on VisionFive 2 and Star64 RISC-V SBCs. However, I run into an error at the very final `amiberry` binary assembly:
```
g++ -o amiberry src/a2065.o src/a2091.o src/akiko.o src/amax.o src/ar.o src/arcadia.o src/audio.o src/autoconf.o src/blitfunc.o src/blittable.o src/blitter.o src/blkdev.o src/blkdev_cdimage.o src/bsdsocket.o src/calc.o src/casablanca.o src/cd32_fmv.o src/cd32_fmv_genlock.o src/cdrom.o src/cdtv.o src/cdtvcr.o src/cfgfile.o src/cia.o src/consolehook.o src/cpuboard.o src/crc32.o src/custom.o src/debug.o src/def_icons.o src/devices.o src/disk.o src/diskutil.o src/dlopen.o src/dongle.o src/drawing.o src/driveclick.o src/ethernet.o src/events.o src/expansion.o src/fdi2raw.o src/filesys.o src/flashrom.o src/fpp.o src/fsdb.o src/fsusage.o src/gayle.o src/gfxboard.o src/gfxutil.o src/hardfile.o src/hrtmon.rom.o src/ide.o src/idecontrollers.o src/identify.o src/ini.o src/inputdevice.o src/inputrecord.o src/isofs.o src/keybuf.o src/main.o src/memory.o src/midiemu.o src/native2amiga.o src/ncr9x_scsi.o src/ncr_scsi.o src/parser.o src/rommgr.o src/rtc.o src/sampler.o src/savestate.o src/scp.o src/scsi.o src/scsiemul.o src/scsitape.o src/statusline.o src/tabletlibrary.o src/tinyxml2.o src/traps.o src/uaeexe.o src/uaelib.o src/uaenative.o src/uaeresource.o src/uaeserial.o src/zfile.o src/zfile_archive.o src/archivers/chd/avhuff.o src/archivers/chd/bitmap.o src/archivers/chd/cdrom.o src/archivers/chd/chd.o src/archivers/chd/chdcd.o src/archivers/chd/chdcodec.o src/archivers/chd/corealloc.o src/archivers/chd/corefile.o src/archivers/chd/corestr.o src/archivers/chd/flac.o src/archivers/chd/harddisk.o src/archivers/chd/hashing.o src/archivers/chd/huffman.o src/archivers/chd/md5.o src/archivers/chd/osdcore.o src/archivers/chd/osdlib_unix.o src/archivers/chd/osdsync.o src/archivers/chd/palette.o src/archivers/chd/posixdir.o src/archivers/chd/posixfile.o src/archivers/chd/posixptty.o src/archivers/chd/posixsocket.o src/archivers/chd/strconv.o src/archivers/chd/strformat.o src/archivers/chd/unicode.o src/archivers/chd/vecstream.o src/archivers/dms/crc_csum.o src/archivers/dms/getbits.o src/archivers/dms/maketbl.o src/archivers/dms/pfile.o src/archivers/dms/tables.o src/archivers/dms/u_deep.o src/archivers/dms/u_heavy.o src/archivers/dms/u_init.o src/archivers/dms/u_medium.o src/archivers/dms/u_quick.o src/archivers/dms/u_rle.o src/archivers/lha/crcio.o src/archivers/lha/dhuf.o src/archivers/lha/header.o src/archivers/lha/huf.o src/archivers/lha/larc.o src/archivers/lha/lhamaketbl.o src/archivers/lha/lharc.o src/archivers/lha/shuf.o src/archivers/lha/slide.o src/archivers/lha/uae_lha.o src/archivers/lha/util.o src/archivers/lzx/unlzx.o src/archivers/mp2/kjmp2.o src/archivers/wrp/warp.o src/archivers/zip/unzip.o src/caps/caps_amiberry.o src/machdep/support.o src/floppybridge/ArduinoFloppyBridge.o src/floppybridge/ArduinoInterface.o src/floppybridge/CommonBridgeTemplate.o src/floppybridge/floppybridge_lib.o src/floppybridge/ftdi.o src/floppybridge/GreaseWeazleBridge.o src/floppybridge/GreaseWeazleInterface.o src/floppybridge/pll.o src/floppybridge/RotationExtractor.o src/floppybridge/SerialIO.o src/floppybridge/SuperCardProBridge.o src/floppybridge/SuperCardProInterface.o src/floppybridge/FloppyBridge.o src/osdep/ahi_v1.o src/osdep/bsdsocket_host.o src/osdep/cda_play.o src/osdep/charset.o src/osdep/fsdb_host.o src/osdep/clipboard.o src/osdep/amiberry_hardfile.o src/osdep/keyboard.o src/osdep/midi.o src/osdep/mp3decoder.o src/osdep/picasso96.o src/osdep/writelog.o src/osdep/amiberry.o src/osdep/ahi_v2.o src/osdep/amiberry_dbus.o src/osdep/amiberry_filesys.o src/osdep/amiberry_input.o src/osdep/amiberry_gfx.o src/osdep/amiberry_gui.o src/osdep/amiberry_mem.o src/osdep/amiberry_serial.o src/osdep/amiberry_uaenet.o src/osdep/amiberry_whdbooter.o src/osdep/ioport.o src/osdep/sigsegv_handler.o src/osdep/socket.o src/osdep/retroarch.o src/osdep/vpar.o src/sounddep/sound.o src/threaddep/threading.o src/osdep/gui/ControllerMap.o src/osdep/gui/SelectorEntry.o src/osdep/gui/ShowHelp.o src/osdep/gui/ShowMessage.o src/osdep/gui/ShowDiskInfo.o src/osdep/gui/SelectFolder.o src/osdep/gui/SelectFile.o src/osdep/gui/CreateFilesysHardfile.o src/osdep/gui/EditFilesysVirtual.o src/osdep/gui/EditFilesysHardfile.o src/osdep/gui/EditFilesysHardDrive.o src/osdep/gui/PanelAbout.o src/osdep/gui/PanelPaths.o src/osdep/gui/PanelQuickstart.o src/osdep/gui/PanelConfig.o src/osdep/gui/PanelCPU.o src/osdep/gui/PanelChipset.o src/osdep/gui/PanelCustom.o src/osdep/gui/PanelROM.o src/osdep/gui/PanelRAM.o src/osdep/gui/PanelFloppy.o src/osdep/gui/PanelExpansions.o src/osdep/gui/PanelHD.o src/osdep/gui/PanelRTG.o src/osdep/gui/PanelHWInfo.o src/osdep/gui/PanelInput.o src/osdep/gui/PanelIOPorts.o src/osdep/gui/PanelDisplay.o src/osdep/gui/PanelSound.o src/osdep/gui/PanelDiskSwapper.o src/osdep/gui/PanelMisc.o src/osdep/gui/PanelPrio.o src/osdep/gui/PanelSavestate.o src/osdep/gui/PanelVirtualKeyboard.o src/osdep/gui/main_window.o src/osdep/gui/Navigation.o src/osdep/vkbd/vkbd.o src/newcpu.o src/newcpu_common.o src/readcpu.o src/cpudefs.o src/cpustbl.o src/cpuemu_0.o src/cpuemu_4.o src/cpuemu_11.o src/cpuemu_13.o src/cpuemu_40.o src/cpuemu_44.o src/archivers/7z/7zAlloc.o src/archivers/7z/7zArcIn.o src/archivers/7z/7zBuf.o src/archivers/7z/7zBuf2.o src/archivers/7z/7zCrc.o src/archivers/7z/7zCrcOpt.o src/archivers/7z/7zDec.o src/archivers/7z/7zFile.o src/archivers/7z/7zStream.o src/archivers/7z/Aes.o src/archivers/7z/AesOpt.o src/archivers/7z/Alloc.o src/archivers/7z/Bcj2.o src/archivers/7z/Bra.o src/archivers/7z/Bra86.o src/archivers/7z/BraIA64.o src/archivers/7z/CpuArch.o src/archivers/7z/Delta.o src/archivers/7z/LzFind.o src/archivers/7z/Lzma2Dec.o src/archivers/7z/Lzma2Enc.o src/archivers/7z/Lzma86Dec.o src/archivers/7z/Lzma86Enc.o src/archivers/7z/LzmaDec.o src/archivers/7z/LzmaEnc.o src/archivers/7z/LzmaLib.o src/archivers/7z/Ppmd7.o src/archivers/7z/Ppmd7Dec.o src/archivers/7z/Ppmd7Enc.o src/archivers/7z/Sha256.o src/archivers/7z/Sort.o src/archivers/7z/Xz.o src/archivers/7z/XzCrc64.o src/archivers/7z/XzCrc64Opt.o src/archivers/7z/XzDec.o src/archivers/7z/XzEnc.o src/archivers/7z/XzIn.o src/archivers/chd/utf8proc.o -L/usr/local/lib -Wl,-rpath,/usr/local/lib -Wl,--enable-new-dtags -lSDL2 -lSDL2_image -lSDL2_ttf -lserialport -lportmidi -lguisan -Lexternal/libguisan/lib -lmt32emu -Lexternal/mt32emu -fuse-ld=gold -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lpthread -lz -lpng -lrt -lFLAC -lmpg123 -ldl -lmpeg2convert -lmpeg2 -lstdc++fs
collect2: fatal error: cannot find ‘ld’
compilation terminated.
```
Faced on a Debian Sid/unstable `riscv64` container emulated with QEMU.

**To Reproduce**
```sh
apt install autoconf make cmake g++ pkg-config libdrm-dev libgbm-dev libudev-dev libxml2-dev libpng-dev libfreetype6-dev libflac-dev libmpg123-dev libmpeg2-4-dev libasound2-dev libserialport-dev libportmidi-dev wget kbd
make -j4 PLATFORM=riscv64
```
Long form, with SDL2 builds all succeeding previously, we use this script: https://github.com/MichaIng/DietPi/blob/amiberry/.build/software/Amiberry/build.bash
Here the full log of the build workflow: https://github.com/MichaIng/DietPi/actions/runs/7415419310/job/20209333528

**Expected behavior**
The final `amiberry` binary should successfully be assembled after all other builds succeeded: SDL2 + image + ttf and capsimg, and all Amiberry objects

**Screenshots**

**Desktop (please complete the following information):**

- OS: Debian

- Version: Sid/unstable

**Additional context**
The error seems to appear in cases where `ld` is indeed not found: https://stackoverflow.com/questions/35970824/gcc-collect2-fatal-error-cannot-find-ld
But `ld` is of course present at the default path, which can be seen by `configure` outputs, like:
```
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
```
Without it, the whole build would have failed much earlier when SDL2 was configured. So I do not really have an idea how it can fail to find it at the last step. Also pinging @rtissera as you probably tested it on Debian or something similar like Ubuntu, and might have an idea what the issue might be.

Of course the very same script works well with all other targets on all Debian versions, up to including Trixie/testing. I also checked for another similar build we do for `riscv64`. [Shairport Sync](https://github.com/mikebrady/shairport-sync) compiles as well with `g++` and runs well, when doing this in the same container with a very similar build script.

I guess it is not an Amiberry bug, but more an issue with the build environment around this alpha-state architecture on Debian unstable. But probably someone else run into this as well and has an idea what the issue is.

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by solskogen** [comment]
Is ld.gold there?

**Comment by MichaIng** [comment]
Checking the file list, there is a `gold` binary at least: https://packages.debian.org/sid/riscv64/binutils-riscv64-linux-gnu/filelist
```
/usr/bin/riscv64-linux-gnu-gold
```
But it is not in PATH:
```console
root@Star64:~# which ld
/usr/bin/ld
root@Star64:~# which ld.gold
root@Star64:~# which gold
root@Star64:~#
root@Star64:~# ls -l /usr/bin/*ld*
-rwxr-xr-x 1 root root   35824 Jan  2 14:54 /usr/bin/fold
lrwxrwxrwx 1 root root      20 Dec 27 10:36 /usr/bin/ld -> riscv64-linux-gnu-ld
lrwxrwxrwx 1 root root      24 Dec 27 10:36 /usr/bin/ld.bfd -> riscv64-linux-gnu-ld.bfd
lrwxrwxrwx 1 root root      32 Dec  3 14:23 /usr/bin/ld.so -> /lib/ld-linux-riscv64-lp64d.so.1
-rwxr-xr-x 1 root root    5407 Dec  3 14:23 /usr/bin/ldd
-rwxr-xr-x 1 root root   14768 Dec  3 14:23 /usr/bin/pldd
lrwxrwxrwx 1 root root      24 Dec 27 10:36 /usr/bin/riscv64-linux-gnu-ld -> riscv64-linux-gnu-ld.bfd
-rwxr-xr-x 1 root root 2076792 Dec 27 10:36 /usr/bin/riscv64-linux-gnu-ld.bfd
```
Probably this would work?
```sh
ln -s riscv64-linux-gnu-gold /usr/bin/ld.gold
```
But it states that `ld` is missing, not `ld.gold` 🤔.

**Comment by solskogen** [comment]
Try with that symlink.

**Comment by MichaIng** [comment]
Sadly that did not help.

**Comment by solskogen** [comment]
Perhaps the gold-linker doesn't work on risc-v? I don't have access to a risc-v machine, so I can't be sure.

**Comment by MichaIng** [comment]
I guess so. Also this `riscv64-linux-gnu-gold` actually does not exist in the package. There is a strange bug with the online file list (linked above): It is doubled, with a different list appended at the end of the actual (first) list. There are two `/usr/bin` sections: The actual first one does not have that binary, only the repeated one below has. However, when you check the actual content of the package, only the first one is present:
```sh
root@Star64:~# ls -l /usr/bin/riscv64-linux-gnu-gold
ls: cannot access '/usr/bin/riscv64-linux-gnu-gold': No such file or directory
```
Hence makes sense that the symlink had no effect 😄.

I first thoughts the ones at the bottoms are symlinks (which are commonly sorted below real files), but vast parts of the paths are indeed doubled, and those which are additionally present at the bottom are completely missing in the package.

Is there a way to tell `g++` to use the actual `ld` command pointing to `/usr/bin/riscv64-linux-gnu-ld.bfd`, instead of `ld.gold`?

**Comment by solskogen** [comment]
There is. Compile with this additional flag: `USE_LD=ld`

**Comment by MichaIng** [comment]
Confusing:
```
g++: error: unrecognized command-line option ‘-fuse-ld=ld’; did you mean ‘-fuse-ld=lld’?
```
Now I start to think that actually `ld` is tried to be used already (somehow makes sense according to error message and it explicitly is the default linker), but is not possible to be used for some reason in this case with `g++`. `gold` might probably work, so I could try to define it explicitly as well, but went with the suggestion as I also read that the LLVM linker is quite a good replacement nowadays.

**Comment by solskogen** [comment]
Sorry, that should be `USE_LD=ld.bfd`

**Comment by MichaIng** [comment]
Right, `lld` is probably the default anyway, causing the same error as when not defining it.

**Comment by MichaIng** [comment]
`USE_LD=ld.bfd` worked 🎉 !

`ldd` of course could not work, as it is not included in `binutils` either, but a dedicated package `ldd`.

So this means that neither `gold` nor GNU `ld` works with RISC-V in this case? Is there any theory why? And does it probably make sense to internally define `USE_LD=ld.bfd` for this build target/the architecture, if it was not explicitly set differently, to prevent others from running into this error?

**Comment by MichaIng** [comment]
Okay, while it compiles fine now, it does not yet run on my PINE64 Star64 SBC.

I use a kernel based on StarFive's Linux 6.1 build for the VisionFive 2, but rebased onto latest mainline Linux 6.1, and pulled on top the changes for the Star64 from Fishwaldo's repo, the only one I currently know for this SBC (as long as upstreaming from StarFive has not finished): https://github.com/Fishwaldo/Star64_linux

It runs, it starts X11 desktops using DRI, but in case of Amiberry it first throws something like:
```
MESA-LOADER: failed to open starfive: /usr/lib/dri/starfive_dri.so: cannot open shared object file: No such file or directory
```
I looked around and found this library provided in StarFive's Debian userspace repo: https://github.com/starfive-tech/Debian/blob/20221225T084846Z/gpu/DDK1.19-binary-xorg/IMG_GPU-xorg.tar.gz
This archive contains a lot of GPU/DRM/GL(ES) related libraries, and the missing one as well. Copied it in place, and now get:
```
did not find extension DRI_Mesa version 1
failed to bind extensions
```

Now I remember that I asked about this already some time ago on a RISC-V/StarFive forum: https://forum.rvspace.org/t/failed-to-open-starfive-usr-lib-dri-starfive-dri-so/2325

This is definitely no Amiberry issue. But if someone was able to get it running on VisionFive 2 or Star64, I would be interested. Surely this affects other applications as well.

Final solution is of course using mainline Linux, after everything has been upstreamed. But some components I do not want to miss are still missing, including DRM 😉: https://rvspace.org/en/project/JH7110_Upstream_Plan

**Comment by solskogen** [comment]
ld comes with binutils, and it comes in to "flavors" ld.bfd and ld.gold.

**Comment by MichaIng** [comment]
Okay, and `ld.bfd` is the default `ld`:
```console
root@VM-Trixie:~# ls -l /usr/bin/*ld*
-rwxr-xr-x 1 root root   43920 Sep 20  2022 /usr/bin/fold
lrwxrwxrwx 1 root root      21 Dec 27 10:36 /usr/bin/gold -> x86_64-linux-gnu-gold
lrwxrwxrwx 1 root root      34 Oct  2 16:11 /usr/bin/grub-ntldr-img -> ../lib/grub/i386-pc/grub-ntldr-img
lrwxrwxrwx 1 root root      19 Dec 27 10:36 /usr/bin/ld -> x86_64-linux-gnu-ld
lrwxrwxrwx 1 root root      23 Dec 27 10:36 /usr/bin/ld.bfd -> x86_64-linux-gnu-ld.bfd
lrwxrwxrwx 1 root root      24 Dec 27 10:36 /usr/bin/ld.gold -> x86_64-linux-gnu-ld.gold
lrwxrwxrwx 1 root root      27 Dec  3 14:23 /usr/bin/ld.so -> /lib64/ld-linux-x86-64.so.2
-rwxr-xr-x 1 root root    5348 Dec  3 14:23 /usr/bin/ldd
-rwxr-xr-x 1 root root   23232 Dec  3 14:23 /usr/bin/pldd
lrwxrwxrwx 1 root root      24 Dec 27 10:36 /usr/bin/x86_64-linux-gnu-gold -> x86_64-linux-gnu-ld.gold
lrwxrwxrwx 1 root root      23 Dec 27 10:36 /usr/bin/x86_64-linux-gnu-ld -> x86_64-linux-gnu-ld.bfd
-rwxr-xr-x 1 root root 1422768 Dec 27 10:36 /usr/bin/x86_64-linux-gnu-ld.bfd
-rwxr-xr-x 1 root root 3265248 Dec 27 10:36 /usr/bin/x86_64-linux-gnu-ld.gold
```
So Amiberry internally chooses `ld.gold`? And that one is not available on `riscv64`, currently:
```console
root@Star64:~# ls -l /usr/bin/*ld*
-rwxr-xr-x 1 root root   35824 Jan  2 14:54 /usr/bin/fold
lrwxrwxrwx 1 root root      20 Dec 27 10:36 /usr/bin/ld -> riscv64-linux-gnu-ld
lrwxrwxrwx 1 root root      24 Dec 27 10:36 /usr/bin/ld.bfd -> riscv64-linux-gnu-ld.bfd
lrwxrwxrwx 1 root root      32 Dec  3 14:23 /usr/bin/ld.so -> /lib/ld-linux-riscv64-lp64d.so.1
-rwxr-xr-x 1 root root    5407 Dec  3 14:23 /usr/bin/ldd
-rwxr-xr-x 1 root root   14768 Dec  3 14:23 /usr/bin/pldd
lrwxrwxrwx 1 root root      24 Dec 27 10:36 /usr/bin/riscv64-linux-gnu-ld -> riscv64-linux-gnu-ld.bfd
-rwxr-xr-x 1 root root 2076792 Dec 27 10:36 /usr/bin/riscv64-linux-gnu-ld.bfd
```
Not sure if this is a Debian thing, or if `gold` generally has issues with RISC-V and is not available on other distros as well.

**Comment by giantclambake** [comment]
>So Amiberry internally chooses ld.gold?

In the Makefile..  `USE_LD ?= gold`  If ld.gold doesn't work on riscv64, that needs to be fixed (but I don't have riscv64 hardware)

**Comment by MichaIng** [comment]
It seems so, though I fail to find some official info about this, only what has been found on other projects:
- https://github.com/riscv-collab/riscv-gnu-toolchain/issues/787
- https://github.com/NixOS/nixpkgs/issues/207672
- https://ubuntuforums.org/showthread.php?t=2476019

So yes, sounds like it makes sense to change the default in the `Makefile` to `bfd` for the `riscv64` target/architecture.

**Comment by midwan** [comment]
Perhaps we should skip the whole idea of trying to "force" the LD selection. I understand that `gold` might be a little faster, but maybe it's not worth the trouble.

@solskogen what do you think about this?

**Comment by solskogen** [comment]
We can add USE_LD=ld.bfd on RISC-V exclusively.
