### ISSUE TITLE
Can't compile on arch

### ISSUE THREAD

**Issue by retrorepair** [BlitterStudio/amiberry#1214]
Trying to compile on arch and installed the listed dependancies but getting the error in the attached some time into compilation.

There's other errors I think before it but it's cut off as there were so many.

I'm obviously missing something but not sure what.
![20240108_173241](https://github.com/BlitterStudio/amiberry/assets/38870678/ad58ff14-35f3-442a-bd3e-a5e4ab386136)

**Comment by midwan** [comment]
On which architecture? X86_64?
What options did you use to compile?
Are you trying the Preview branch?

**Comment by giantclambake** [comment]
> It's a pull of the main git.

I take it you mean the `master` branch? You should probably try the `preview` branch instead with x86-64, but I doubt that's the problem...

> X86_64 and just make.

Is that literal...ie; just 'make'?  Did you read the instructions on the github page?

The command should be  `make PLATFORM=x86-64`

**Comment by retrorepair** [comment]
Your exactly right, I skimmed the instructions and didn't make note of the make line. Targeting x86_64 worked. Sorry to waste everyone's time
