### ISSUE TITLE
Query: feat enable hardware sprite emulation for RTG ~ always enabled by default?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1215]
Current git pull from preview branch.

This must be in error?

- start amiberry, no config loaded, this feature is enabled
- start amiberry, load non-P96 config.uae, this feature is enabled

-start amiberry, load P96 config.uae (created before this feature add), this feature is enabled but Input->Virtual mouse driver very much may not be --- if you proceed to start the emulation in such case, things wrt the mouse cursor become decidedly weird, from 2 mouse cursors (native) that is unaffacted by both/native/host options, to hitting F12 and ending up with an Amiga mouse cursor in the GUI, and host mouse cursor when you leave GUI window focus.. and Reset/Restart doesn't help any (I didn't check 'Set Configuration') -- quitting amiberry & restarting seemed to be only resolve.

Note, it's fine if you start the emulation with both sprite emulation & virtual mouse driver enabled already set in config.uae

Best I see it, 'Hardware sprite emulation' should by default be `false` unless user selects it.

Thoughts?

TIA

**Comment by midwan** [comment]
Yes, it should not be enabled by default, that's a bug.

**Comment by midwan** [comment]
Fixed with 87d15f408d6d8f5da491b1a1aefe5c00982bb4ea
