### ISSUE TITLE
Use SDL2 multi-threaded rendering broken wrt Debian 12 amd64 & nvidia-driver 525.147.05-4

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1216]
I am aware this is covered under the auspices of helptext ;

_Provides a performance benefit, however not all systems support it.
Disable this if you notice problems, like a black screen when starting emulation._

In the case of the proprietary nvidia-driver noted, the second line applies ~ you need disable this feature or else black screen.

It depends on how one connotes 'systems' ...ie; works on deb12 with nvidia GPU and nouveau drivers ~ doesn't work on same system with proprietary nvidia-drivers.....it's more GPU/drivers at this end, not so much system ;)

Tends to be an issue because you do give up some performance, and my gut feeling is most folks with nvidia GPU will indeed go for the nvidia-driver (for games/Steam etc).

If I understand it properly, this is likely a SDL2 shortcoming? If that's the case, this issue remarks to that, wrt proprietary nvidia drivers.

Else it's a bug in amiberry?

TIA

**Comment by midwan** [comment]
It's not a bug in Amiberry.
SDL2 doesn't guarantee that this will work, it happens to do so in some combinations but doesn't in others.
In the newer Debian bookworm, it fails for the same systems it used to work, and we tracked it down to an update to MESA.
I'm afraid there's nothing I can do from my side about this.
