### ISSUE TITLE
HighGFX Support for Amiberry

### ISSUE THREAD

**Issue by Mangerio** [BlitterStudio/amiberry#1221]
Lately i found new display drivers for the ECS/AGA chipset.

https://aminet.net/package/driver/moni/HighGFXnmore

HighGFX'n'more
a package with additional screenmodes for the classic AmigaOS (V3.0+)

800x600 SuperPlus 48Hz, 15,16kHz
1024x768 HighGFX 55Hz, 22,22kHz interlaced
1280x720 HD720 47Hz, 17,86kHz interlaced
1280x1024 XTREME 34Hz, 18,08kHz interlaced

I have tested the new screen modes in WINUAE and they work beautifully!

Would it be possibe to adapt Amiberry to handle these resolutions? That would be awsome for Lightwave 3D users!
Software packages like Lightwave 3D that don't work flawless on RTG would benefit greatly from HigRes planar screen modes!

**Comment by solskogen** [comment]
What happens in Amiberry?

**Comment by dimitris-norce** [comment]
You could test this in the Preview version, which is more up-to-date with the latest WinUAE.
Some things are still not implemented, like custom monitors and graphics cards, but the core emulation is 100% identical.
You can find pre-compiled binaries for the Preview version in the Releases (marked as RC), or compile it from source from the `preview` branch. Please note it's 64-bit only, and it has no JIT for ARM yet (but it has JIT for x86-64).

**Comment by midwan** [comment]
You could test this in the Preview version, which is more up-to-date with the latest WinUAE.
Some things are still not implemented, like custom monitors and graphics cards, but the core emulation is 100% identical.
You can find pre-compiled binaries for the Preview version in the Releases (marked as RC), or compile it from source from the preview branch. Please note it's 64-bit only, and it has no JIT for ARM yet (but it has JIT for x86-64).

**Comment by Mangerio** [comment]
Thank you for the clue!
Things look much better with the latest Preview.
I got the best results when i chose the same resolution in UAE in fullscreen mode.

The image is now captured almost right.
In color with flickerfixer working.
SuperPlus 800x600 is good! Usable!
The other three have still problems with the scaling but are otherwise okay!

Great! Hope the issues will be fixed with UAE 5.2!

![IMG_20240202_185209555](https://github.com/BlitterStudio/amiberry/assets/121621449/c0a371ce-1adb-4bd2-9dc6-d69b0f8690fb)
![IMG_20240202_184947802](https://github.com/BlitterStudio/amiberry/assets/121621449/285802a0-7759-4c1f-ab70-126b2fcf18dc)
![IMG_20240202_185242317](https://github.com/BlitterStudio/amiberry/assets/121621449/75ac2533-19ec-4458-a75d-452145ed6456)
![IMG_20240202_185445615](https://github.com/BlitterStudio/amiberry/assets/121621449/bec6cb5b-5bfb-4e25-a8ee-cb2ce1dacd6c)

**Comment by midwan** [comment]
@Mangerio 
I've done a lot of work on this in a separate branch, which includes a lot of refactoring of how the GFX code works. Among other things, there is a separate window for the GUI and the emulation screen, the screen size is determined by what's being emulated, and the manual Width/Heigth values now represent manual cropping (if enabled).

This seems to work with HighGFX modes properly as well, since they are no longer restricted to the PAL resolutions, as before.

Feel free to give it a shot and provide any feedback: `feature/gfx-rewrite` - The plan is to eventually merge that into `preview`, once we're sure no issues or new bugs have been introduced. :)

**Comment by Mangerio** [comment]
Sounds good! Awsome! Will test and feed back!
