### ISSUE TITLE
GUI -> Input -> Port 1: -> Remap --- selection overlay misaligned

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1228]
Previously v5.6.2 .... button A (south) green spot aligns with actual controller button position.

![v5.6.2](https://imgur.com/FFOr8Cf.png)

Now v6.2.0, the green spot is no longer aligned, being moved up the image and no longer indicating the  correct controller button. Likewise, all other green overlay widgets are moved up the image similarly.

![v6.2.0](https://imgur.com/9InGf8I.png)

I imagine this is some machination related to the GUI redesign/resize?

TIA

**Comment by midwan** [comment]
Yep, this was missed at some point. Thanks!
