### ISSUE TITLE
MacOS Catalina ?

### ISSUE THREAD

**Issue by bugjacobs** [BlitterStudio/amiberry#1229]
Is it impossible to compile Amiberry for Catalina 10.15.7 ?
I have an oldish iMac here that stops on that version ..

Cheers 
DagBug

**Comment by solskogen** [comment]
What do you mean stops? Have you tried?

**Comment by midwan** [comment]
The automated builds for macOS on Github use MacOS 12.x, while the newer M1 ones use MacOS 14.x

If the requirements can be installed with Homebrew, I assume it could run on older versions as well, but you'll have to try that yourself I'm afraid. :)
