### ISSUE TITLE
Virtual mouse driver -- vertical movement not scaled correctly when RTG enabled

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1230]
Same situation as was fixed for single line mode?  https://www.youtube.com/watch?v=Yyer-gWJUGY

TIA

**Comment by midwan** [comment]
Do you have Single Line mode when this happens?
Does it work correctly if you set it to Double Line mode?

**Comment by midwan** [comment]
I can recreate this here, and it's an easy fix.  :)
