### ISSUE TITLE
Scanline produces too dark picture. Improvement proposal.

### ISSUE THREAD

**Issue by boras-pl** [BlitterStudio/amiberry#1233]
For low resolution games the scanlines feature produces too dark picture:
![Amiberry_scanlines](https://github.com/BlitterStudio/amiberry/assets/59491904/ac4e8d85-10c5-4dca-b84d-c17365e5f190)

It is because every second line is black. From performance perspective it seems to be reasonable however, it would be nice to have a scanline functionality, where the second line could be not completely black, but somehow correlated with the previous one.

Looking at Vice C64 emulator, there is an excellent CRT filter that produces a bright picture with still visible scanlines:
![Vice_scanlines](https://github.com/BlitterStudio/amiberry/assets/59491904/75e91fb1-4806-47e8-b2f4-d8c8c6f83891)

The CRT filters often do more than simple scanlines callculations, they also emulate PAL color glitches, etc.
I am not so greedy, I understand that implementing such a sophisticated CRT emulation would require a lot of development and it would consume more CPU power. However, as I wrote above, the picture in Amiberry is too dark and any simple implementation like doubling the second line with 50% (or better configurable) of brightness it would be good enough.

Best Regards
MB

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by midwan** [comment]
This is already proposed in #425 :)

There is some work being done in using a CRT shader (which in turn requires OpenGL) in the `preview` branch, but it's not fully working yet.
