### ISSUE TITLE
Question wrt GUI -> Paths panel  + feature idea

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1234]
I notice since the GUI redesign, we now have this in the Paths panel;

![now](https://imgur.com/1xmEnY8.png)

Foremost, I question it's purpose (unless it's something to do with system/user files separation)... why would one use this?

Secondly, there's now space in that panel area, to define another path. To me, the best candidate would be "WHDLoad archives"

You could then follow on with GUI->Quickstart->WHDLoad auto-config: -> Select file button to open in the above defined dir.

Comment/thoughts?

TIA

**Comment by midwan** [comment]
@giantclambake 
This path is configurable and stored in `amiberry.conf`, so I thought it would be good to expose it.
It's referring to where the WHDBooter files (XML file, game saves, etc) reside, not your archives.
