### ISSUE TITLE
GUI->Paths panel  ... extraneous forwards slash in retroarch.cfg path

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1236]
![ex](https://imgur.com/7wByIHb.png)

TIA

**Comment by midwan** [comment]
That's not the default value, nor can I recreate that here. 
But I suspect the generation of that path can be improved :)

**Comment by midwan** [comment]
@giantclambake 
The `preview` version just got some extensive refactoring which also affected this area. Please check if that fixes the issue for you, when you get a chance.

**Comment by giantclambake** [comment]
Yeah, all good now in preview. thanks.
