### ISSUE TITLE
Doc.  GUI -> DiskSwapper -> helptext [update]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1238]
src/osdep/gui/PanelDiskSwapper.cpp 

@ line 409

```
    helptext.emplace_back("- Next slot in Disk Swapper");
    helptext.emplace_back("- Previous slot in Disk Swapper");
```

Now that we have specific events in these regards, helptext should read;

```
    helptext.emplace_back("- Insert next Disk Swapper slot in DF0:");
    helptext.emplace_back("- Insert previous Disk Swapper slot in DF0:");
```

TIA

**Comment by giantclambake** [comment]
Query: do you think it's better to remove altogether...

```
    helptext.emplace_back("- Next slot in Disk Swapper");
    helptext.emplace_back("- Previous slot in Disk Swapper");
```

?? .... it's just a rationale thing....ie; the intent of the helptext is to steer ppl towards 'single button press' custom actions for diskswapper control, whereas we know the above 2 custom commands require you map a further custom action to actually insert the disk image ~ I get the feeling this will cause user confusion (ask me how I know =)

**Comment by midwan** [comment]
The description there mentions what events are available to map, related to Disk Swapper. Therefore I think it's best that all of them are mentioned, not just some of them.

The two new ones should be added in the list, not replace the existing ones which are still available.

**Comment by midwan** [comment]
Fixed with latest commits
