### ISSUE TITLE
Missing aarch32 support in CMakelist and CMake does not detect ARM 32-bit architecture

### ISSUE THREAD

**Issue by Ntemis** [BlitterStudio/amiberry#1242]
We switched from make to cmake and we now have issue building arm32 and in extension riscv64 targets due to missing arguments:
![image](https://github.com/BlitterStudio/amiberry/assets/2123893/fd11a19a-4fce-4b1c-95ae-4faf59283524)
![image](https://github.com/BlitterStudio/amiberry/assets/2123893/1af331aa-7856-4331-af2f-1f833e0b8eed)

**Comment by midwan** [comment]
@rtissera 
I don't see that there are any special flags for Riscv64 in the Makefile, so shouldn't that work as it is with CMake also? (can't test, I don't have a device).

I'll check about the 32-bit targets.

**Comment by solskogen** [comment]
CMake should figure this all out by it self, but if certain optimizations is needed (like what we have for the Pi5) you might want to add that

**Comment by solskogen** [comment]
That looks almost ok. But you're removing the aarch64 support with that patch.

**Comment by solskogen** [comment]
Oh, I see. Yeah your patch looks fine :-)
