### ISSUE TITLE
Apple Silicon / OSX JIT

### ISSUE THREAD

**Issue by vaccinemedia** [BlitterStudio/amiberry#1245]
Just a quick question. I searched to see if this has already been asked but searching for Apple Silicon only had 2 non-jit related issues and searching for "jit" had too many results to wade through. I'm just wondering why there is no JIT option on Apple Silicon? Is it because it is yet to be implemented OR (and I'm assuming it's this) is it simply never going to be possible due to Apple doing what Apple does best and removing support for 32Bit apps or something along those lines?

**Comment by midwan** [comment]
It's a bit of both, plus one more factor:
I don't have the hardware to even test things here, so I am not able to even try that. We'll need someone else with more knowledge on the platform to assist, if this is to ever become a reality (if it's even possible, with the restrictions Apple has put in place).

**Comment by vaccinemedia** [comment]
Ahhh! Fair enough and thank you for the very speedy reply! :) Despite what Apple have done I'm still a bit of a fan boy at heart ;) If you ever get a second hand M1 Mac Mini / Macbook Pro (which is what I'm typing this on) they work as a great machine for dev work due to being Unix Based.
