### ISSUE TITLE
Amiberry does not start when the controller is connected wireless per ps3controller-driver

### ISSUE THREAD

**Issue by NoobieMaks** [BlitterStudio/amiberry#1246]
Hello, hopefully someone can help me.

I'm using a Raspberry Pi 3 B, the latest Retropie (4.8.6) and the latest Amiberry (5.6.6) in the Retropie-Setup-Source.
Using WHDLoad with the latest lha-files.

For years I try to set up my perfect retro pi image:
1. jessie + RePi 4.4.12 + Amiberry 2.25 + ps3-driver = my first try, good but no .lha-support
2. stretch + RePi 4.5.11 + Amiberry 3.0.11 + sixad-driver = really good but the sixad-driver leads to ghost-input in the Emulation Station-menu -> no more possible to change to the ps3controller -> error: "could not install package(s): libusb-dev"
3. buster + RePi 4.8.6 + Amiberry 5.6.6 = would have been my hope to get the ps3controller-driver to have no ghost input issue, I'm using only ps3-controller, so I have no need for the sixad-driver.

Nearly everything works fine in my 3rd project - I can install both drivers (ps3/ sixad), of course installed and used only alternatively.

And now I come to my problem:
Amiberry doesn't start when the controller is connected per ps3controller-driver. Every other section/emulator works fine with it.
If I'm connected per cable Amiberry starts fine, also when I'm connected wireless with the sixad-driver.

It seems that only my desired ps3controller-driver doesn't let me open my .lha-files:
When I start a game I can only see 2-3 flashes of the mouse arrow on the left upper edge and then I fall back to the Emulation Station screen. When I uninstall the ps3controller-driver and install the sixad then I can open the games and also play wireless properly.

I really hope someone could help me finishing my perfect setting.
Maybe someone can tell me how I can install the ps3controller driver to my 2nd project (strech -> error: "could not install package(s): libusb-dev").

**Comment by midwan** [comment]
It probably starts and shuts down right away, due to some error.
Try enabling logging in Amiberry, and check if you have any messages in there that might indicate what went wrong. If it crashes before it writes to the log, there won't be any of course. But it would still show how far it got.

Alternatively, try launching Amiberry from the console manually, to see if any errors are output on the console when it crashes.

**Comment by NoobieMaks** [comment]
Hello Dimitris,

many thanks for your assistance! I'm so glad to get your help.

Your hints:

  1.
Enabling logging -> check -> I found out how to do this: amiberry.conf
  2.
Launching amiberry from the console manually -> this shows me how poor my knowledge is, I really don't know what this means; do you mean to start it per +Start Amiberry.sh?

Logging:
I tried to log both ways: wireless with sixad (positive example) and wireless with ps3controller (negative example)

In both ways I get no log file. ?-Strange-?
I should get one at least when I can start and play the game with the sixad driver, shouldn't I?

My settings in amiberry.conf should be ok:

  *   write_logfile=yes
  *   logfile_path=/opt/retropie/emulators/amiberry/amiberry.log

I can only provide a log from ES:

WITH PS3CONTROLLER-DRIVER:
Mar 18 17:32:33 lvl2:    req sound [video.launch]
Mar 18 17:32:33 lvl2:      (missing)
Mar 18 17:32:34 lvl2:   Attempting to launch game...
Mar 18 17:32:34 lvl2:         /opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ amiga /home/pi/RetroPie/roms/amiga/Agony_v2.1_0960.lha
Mar 18 17:32:42 lvl2:   Creating window...
Mar 18 17:32:42 lvl2:   Created window successfully.
Mar 18 17:32:42 lvl2:   GL vendor:   Broadcom
Mar 18 17:32:42 lvl2:   GL renderer: VideoCore IV HW
Mar 18 17:32:42 lvl2:   GL version:  OpenGL ES-CM 1.1
Mar 18 17:32:42 lvl2:   Checking available OpenGL extensions...
Mar 18 17:32:42 lvl2:    ARB_texture_non_power_of_two: MISSING
Mar 18 17:32:42 lvl2:   Added known joystick 'PLAYSTATION(R)3 Controller' (instance ID: 1, device index: 0)
Mar 18 17:32:43 lvl2:   Added known joystick 'PLAYSTATION(R)3 Controller' (instance ID: 1, device index: 0)

WITH SIXAD-DRIVER:
Mar 18 19:12:46 lvl2:    req sound [video.launch]
Mar 18 19:12:46 lvl2:      (missing)
Mar 18 19:12:47 lvl2:   Attempting to launch game...
Mar 18 19:12:47 lvl2:         /opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ amiga /home/pi/RetroPie/roms/amiga/Agony_v2.1_0960.lha
Mar 18 19:13:52 lvl2:   Creating window...
Mar 18 19:13:52 lvl2:   Created window successfully.
Mar 18 19:13:52 lvl2:   GL vendor:   Broadcom
Mar 18 19:13:52 lvl2:   GL renderer: VideoCore IV HW
Mar 18 19:13:52 lvl2:   GL version:  OpenGL ES-CM 1.1
Mar 18 19:13:52 lvl2:   Checking available OpenGL extensions...
Mar 18 19:13:52 lvl2:    ARB_texture_non_power_of_two: MISSING
Mar 18 19:13:53 lvl2:   Added known joystick 'Sony PLAYSTATION(R)3 Controller' (instance ID: 10, device index: 0)
Mar 18 19:13:53 lvl2:   Added known joystick 'Sony PLAYSTATION(R)3 Controller' (instance ID: 10, device index: 0)

WITH CABLE CONNECTED:
Mar 18 19:31:08 lvl2:    req sound [video.launch]
Mar 18 19:31:08 lvl2:      (missing)
Mar 18 19:31:09 lvl2:   Attempting to launch game...
Mar 18 19:31:09 lvl2:         /opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ amiga /home/pi/RetroPie/roms/amiga/Agony_v2.1_0960.lha
Mar 18 19:32:57 lvl2:   Creating window...
Mar 18 19:32:57 lvl2:   Created window successfully.
Mar 18 19:32:57 lvl2:   GL vendor:   Broadcom
Mar 18 19:32:57 lvl2:   GL renderer: VideoCore IV HW
Mar 18 19:32:57 lvl2:   GL version:  OpenGL ES-CM 1.1
Mar 18 19:32:57 lvl2:   Checking available OpenGL extensions...
Mar 18 19:32:57 lvl2:    ARB_texture_non_power_of_two: MISSING
Mar 18 19:32:57 lvl2:   Added known joystick 'Sony PLAYSTATION(R)3 Controller' (instance ID: 18, device index: 0)
Mar 18 19:32:57 lvl2:   Added known joystick 'Sony PLAYSTATION(R)3 Controller' (instance ID: 18, device index: 0)

I can't see any difference, beside the running score of the instance IDs, which run up with every start of a game.


Console:
      If launching per +Start Amiberry.sh was meant so it is also not possible for me.
      I have the same flashing/fall-back issue.
      But, indead, one second more and a very short moment of the amiberry menu screen.
      But also no amiberry.log.


There's also no difference in the runcommand.log:

WITH PS3CONTROLLER-DRIVER:
Parameters:
Executing: bash "/home/pi/RetroPie/roms/amiga/+Start Amiberry.sh"
Launching ...
./amiberry
~

WITH SIXAD-DRIVER:
Parameters:
Executing: bash "/home/pi/RetroPie/roms/amiga/+Start Amiberry.sh"
Launching ...
./amiberry
~

I'm so sorry I can't deliver what you need to help me - especially I can't understand why there is no amiberry.log file existing, in any case?
Do you have more ideas for me? Would a video help you?

br
Maks

________________________________
Von: Dimitris Panokostas ***@***.***>
Gesendet: Montag, 18. März 2024 16:10
An: BlitterStudio/amiberry ***@***.***>
Cc: NoobieMaks ***@***.***>; Author ***@***.***>
Betreff: Re: [BlitterStudio/amiberry] Amiberry does not start when the controller is connected wireless per ps3controller-driver (Issue #1246)


It probably starts and shuts down right away, due to some error.
Try enabling logging in Amiberry, and check if you have any messages in there that might indicate what went wrong. If it crashes before it writes to the log, there won't be any of course. But it would still show how far it got.

Alternatively, try launching Amiberry from the console manually, to see if any errors are output on the console when it crashes.

**Comment by midwan** [comment]
You probably don't have permissions to write to the destination where the logfile is set to be created.
You can either change the path there to somewhere you _can_ write to, or change the permissions in that folder accordingly.

Starting from the console, means exit EmulationStation (with F4 from what I recall), and manually navigate to the location amiberry is installed, then launching it from there. If things haven't changed, something the following should do this (check if the paths are correct):

```
cd /opt/retropie/emulators/amiberry
./amiberry
```

**Comment by NoobieMaks** [comment]
Thanks for your support. Launching from the console had the same result as from ES: Just a short flash of the amibery menu. So hopefully you can find something in the attached log-files I made one with sixad-driver and one with the problematic ps3controller-driver.
[amiberry_sixad.log](https://github.com/BlitterStudio/amiberry/files/14641444/amiberry_sixad.log)
[amiberry_ps3.log](https://github.com/BlitterStudio/amiberry/files/14641445/amiberry_ps3.log)

**Comment by midwan** [comment]
From what I can see in the logs, it crashes right between setting up the controller mapping and writing out the Joystick name for the controller.

It's possible that the text it got for the Joystick name is either null or invalid, which could cause an issue when it tries to read from it later on, and write that to the log also. We never see that line written out in the ps3 log you posted.

I'm refactoring that area of the code today, so I'll add a fix for this kind of scenario as well, which hopefully will gracefully take care of such kind of situations. But you'll need to update Amiberry to the latest version (when this is released) to get the fix, of course.

**Comment by midwan** [comment]
This will be part of 5.6.9

**Comment by NoobieMaks** [comment]
Thank you so much! - I can't await 5.6.9 for next possible Retropie Amiberry Update.
You really brought back my good childhood days with Amiberry!
