### ISSUE TITLE
Meaningless/redundant line in src/osdep/amiberry_input.cpp ?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1247]
`write_log("No Retroarch controller cfg file found, checking for mapping in retroarch.cfg\n");`

...reminds me of the old line "No keyboard found - press any key to continue" =)

TIA

**Comment by midwan** [comment]
It's not redundant.
Retroarch can have controller configurations in separate files (named after the controller) but also included in the main `retroarch.cfg` file itself.

The log indicates that it didn't find a controller-specific one, and will attempt to look at the `retroarch.cfg` file itself, next.
