### ISSUE TITLE
(A) Button is not recognized in the Amiberry GUI of 5.6.8

### ISSUE THREAD

**Issue by NoobieMaks** [BlitterStudio/amiberry#1249]
I upgraded my 5.6.6 RetroPie-Amiberry-Update to the latest version 5.6.8 manually with these instructions:
https://github.com/BlitterStudio/amiberry/wiki/Upgrading-to-the-latest-version/e4b711ff20afe34f21268e72d7160045baf4ef23
Following things did I notice:
- VKbd: Now the Virtual Keyboard works - under 5.6.6 I found no way to bring it on the screen
- Display: The game-display was just a quarter of my computer-screen initially -> I turned it to "default_fullscreen_mode=1" in the amiberry.conf
- GUI: I have a problem with the Amiberry GUI - I can navigate with my joystick but can not choose or check anything, only per keyboard is it possible.
In the games the joysticks are working as they always did, also the new function of the virtual keyboard can be fully used per joystick.
Only the A-Button function in the GUI is missing. Seems weird to me?

**Comment by midwan** [comment]
@NoobieMaks 
for the display, you might also want to try `default_fullscreen_mode=2`, which will use Full-window mode. 

Regarding the controller input in the GUI, I can't say I can recreate this here. It seems to work normally for me.
What kind of controller do you have? Do you have another to test with?

**Comment by midwan** [comment]
@NoobieMaks 
Also, both Button A and Button B should activate widgets in the GUI, unless they are used in the mapping for other events (like for example, opening/closing the GUI, used as Hotkey, etc).

**Comment by NoobieMaks** [comment]
@midwan
Meanwhile I tried all my 3 different controller types: PS3, Shanwan, Dragonrise -> they all have the same behaviour:
I can navigate per digital and analog joy-moves, I can also jump up and down into the drop down menus with left and right shoulder - BUT I can't open/select any drop down menu with A/B as I always do/did. I'm at a loss.
Some questions:
- Was "amiberry-v5.6.8-debian-buster-armhf-rpi3" the right asset for my RasPi 3 B?
- Could the swapped A/B Buttons of the Emulation Station input configuration cause the problem? (RetroPie-Setup 210)
- Why is the amiberry-file of 5.6.6 (9.140 KB) bigger than the one of the newer 5.6.8 (8.000 KB)?
- Would an amiberry.log-file give you useful informations to my problem?
I'm so sorry to bother you with such a ... issue.

**Comment by midwan** [comment]
I managed to recreate this, so I'll get it fixed

**Comment by midwan** [comment]
Fixed with the latest commits above. This will be part of 5.6.9

**Comment by midwan** [comment]
@NoobieMaks 
Forgot to answer your previous questions above:

> * Was "amiberry-v5.6.8-debian-buster-armhf-rpi3" the right asset for my RasPi 3 B?

Yes

> * Could the swapped A/B Buttons of the Emulation Station input configuration cause the problem? (RetroPie-Setup 210)

Nope, this was a bug in the GUI library.

> * Why is the amiberry-file of 5.6.6 (9.140 KB) bigger than the one of the newer 5.6.8 (8.000 KB)?

Because the pre-compiled binaries are compiled using GCC12, which does a better job optimizing the results. Retropie uses Buster, which has GCC8.

> * Would an amiberry.log-file give you useful informations to my problem?

Not needed :)

>   I'm so sorry to bother you with such a ... issue.

Never be sorry about these things, it helps making Amiberry better.

**Comment by NoobieMaks** [comment]
Thanks a lot for the fix - The asset of 5.6.9 is getting more and more precious for me :)

**Comment by NoobieMaks** [comment]
May I ask you some more noobie questions?
I tried to install the latest version of Amiberry:
- at first I did it over the RetroPie-Setup -> this try lifted me to the, on this place, latest available 5.6.6 - OK
- the next try was per download of the latest official binary -> only changing the amberry-file and 5.6.8 was running - OK
- my last try was another manual way over the repo and creating amiberry-master - this try failed:
Starting from ES shows the runcommand an then it falls back to ES and starting from the console leads to this error: "malloc(): unsorted double liked list corrupted".
There  are no amiberry-log-files, because amiberry isn't going to start.

Generally: Which version would it be if it would run? Version under construction 5.6.9 or Preview 6.2.0?
I used for make: PLATFORM=rpi3-sdl2 - should be the right one for me

amiberry-master:
- Which files/folders are necessary to be copied from the amiberry master?

my running 5.6.8 has:
- folders: abr/ conf/ controllers/ data/ kickstarts/ nvram/ savestates/ screenshots/ whdboot/ **_whdboot-dist_**
- files: amiberry/ **_amiberry.sh/ capsimg.so/ retropie.pkg_**

amiberry-master has so much more and a few not:
- folders: abr/ **cmake**/ conf/ controllers/ data/ **docs/ external/ flatpak/ inputrecordings/** kickstarts/ nvram/ savestates/ screenshots/ **src**/ whdboot/ **whdboot-src**
- files: amiberry/ **Brewfile/ CMakeLists.txt/ CMakeSettings.json/ Entitlements.plist/ Info.plist.template/ LICENSE/ macos_init_amiberry.zsh/ make-bundle.sh/ Makefile/ PULL_REQUEST_TEMPLATE**

I tried 2-3 ways: Copied only the amiberry file and because of no reaction I also copied all the other files.
In a third try I deleted the whdboot-dist folder and the 3 files from 5.6.8 which are not part of amiberry-master.
All tries ended with no reaction after the runcommand window and falling back to ES and when starting from console I always got the mentioned error message.
And I always set the properties from root to pie and 0755.

I ignored the greyed out files: .git/ .github/ .gitattributes/ .gitignore/ .gitmodules

Maybe you can give me some advises generally to the amiberry master and especially to the error: "malloc(): unsorted double liked list corrupted".

**Comment by NoobieMaks** [comment]
I don't know why and how, but now I got an amiberry-log-file, which answers the question to which version it would lead.

But only 3 lines are in it, nothing more?:

"Amiberry v5.6.9 (2024-03-20) Logfile

Compiled against SDL2 **v2.0.10**, Linked against SDL2 v2.0.10
Allocated 16 MB for 24-bit area (0x20000000) and 640 MB for Z3 and RTG at fake address (0x30000000 - 0x58000020)"


When I compare it with a log from the working 5.6.8 then I see a difference in compiled against: v2.0.9. vs. v2.0.10.

Amiberry v5.6.8 (2024-02-29) Logfile

Compiled against SDL2 **v2.0.9,** Linked against SDL2 v2.0.10
Allocated 16 MB for 24-bit area (0x20000000) and 640 MB for Z3 and RTG at fake address (0x30000000 - 0x58000020)
Enumerating display devices.. 
Sorting devices and modes...
0: 1280x1024, 32-bit (60)
1 display modes.
...

**Comment by midwan** [comment]
@NoobieMaks 
The current version from `master` is undergoing some changes, so it's a bit unstable.
When ready, and tested, it will be published as 5.6.9 and pre-compiled binaries will be released at the same time. Except for Dispmanx versions, since those cannot be compiled in the agents I have running.

**Comment by kikendo** [comment]
I ran into this same problem trying to run Amiberry on my MuOS setup on an Anbernic portable.
I cannot select absolutely anything, the emulator cannot be used at all. None of the device's buttons register as a click.

Is there a way to fix this?

**Comment by midwan** [comment]
> I ran into this same problem trying to run Amiberry on my MuOS setup on an Anbernic portable. I cannot select absolutely anything, the emulator cannot be used at all. None of the device's buttons register as a click.
> 
> Is there a way to fix this?

Which version is it running?
This was fixed several versions ago, and the current Amiberry-Lite version that it should be using, is 5.8.6: https://github.com/BlitterStudio/amiberry-lite

**Comment by kikendo** [comment]
> Which version is it running?
It's running Amiberry 5.6.8 like said on this thread, I guess that is the issue.
It's weird because the OS's page says it includes 5.7.4 but it does not.

**Comment by midwan** [comment]
Yeah, in that case it needs an update. This was a bug that got fixed with 5.6.9 onwards (and nowadays, that is split to a separate edition, named Amiberry-Lite)

**Comment by kikendo** [comment]
I'm sorry I didn't realize that this was not the latest version. I will try to contact the maintainers and see if this can be fixed.

**Comment by kikendo** [comment]
I think a problem may be that they are currently working on a major next release of MuOS and teh currently available version (Banana) will not be updated at all.
But if the new version (Pixie) does not have the right one, they should also know. If you can poke them that would be great as I don't have Discord.
