### ISSUE TITLE
Emulator window not redrawn when GUI active?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1251]
Start emulation (normal or RTG) -> F12 ....move GUI window ~ it's fairly evident =)

TIA

**Comment by midwan** [comment]
I suppose you're referring to the `preview` branch, which has separate windows for GUI and emulation screen here?
That is by design, the emulation is paused when you open the GUI.

**Comment by giantclambake** [comment]
Yes, apologies... preview branch.  If this is expected, then so be it ~ I was expecting the paused emulation window to be redrawn....here, I've just raised focus on the emulation window after dragging GUI -> https://imgur.com/TQkFy7Y.png

I likely notice it more always being in desktop (windowed) environment ;)

**Comment by midwan** [comment]
Oh wait, it should be redrawn if you move stuff over it. The emulation is paused, so nothing new happens inside it, but the window contents should remain visible.

**Comment by midwan** [comment]
And it _does_ redraw itself correctly here, under RasperryPi OS and Debian

**Comment by giantclambake** [comment]
Had to check on a LFS-11.3 build (to eliminate nvidia drivers being at cause) ~ preview branch doing it there as well ... must be a x86-64 thing?  https://www.youtube.com/watch?v=iwEs5Zb4zg0

**Comment by midwan** [comment]
I cannot recreate this here so far, and I've tested both ARM and x86-64 builds.

**Comment by giantclambake** [comment]
Retested to make sure nothing erroneous had crept in ~ this procedure excludes any chance of my existing amiberry.conf & config.uae files being at fault (my usual runtime_dir is `~/Amiberry/` )

-fresh clone of preview git tree (`git clone -b preview https://github.com/BlitterStudio/amiberry`)
-compile as usual with PLATFORM=x86-64
-copy kickstart-1.3 rom (v34.5) into build_dir/kickstarts/
-launch amiberry from within build_dir ( `./amiberry` ) -> click Start (emulation boots to Amiga insert disk screen)
-press F12 to display GUI

https://www.youtube.com/watch?v=sEubIUkNydE

Undertook the same procedure on the LFS-11.3 x86-64 build (HP 800 G1 usff, i915 IGP) ~ same result, so doesn't seem Debian specific nor anything to do with proprietary nvidia drivers.

**Comment by solskogen** [comment]
x11 or wayland?

**Comment by giantclambake** [comment]
x11  ;)

**Comment by midwan** [comment]
I've tested it under Wayland (RPI5) and WSL2 on Win11. Will do some more tests in different configurations to see if I can recreate it there.

**Comment by midwan** [comment]
It seems to be related to the back-end used then, I managed to recreate it under Manjaro Linux x86.

**Comment by giantclambake** [comment]
Thanks for the fix, working as expected now ;)
