### ISSUE TITLE
LINUX -Issue when you want to save a configuration from the GUI with a custom path.

### ISSUE THREAD

**Issue by zognic** [BlitterStudio/amiberry#1252]
**Amiberry Linux 5-6-8**

The SAVE configuration button in the GUI saves the configuration file in the wrong location and not with the desired name.

In the section where paths are entered, I specified a custom path for my configuration files. (note that there is no / at the end of the path for the example)
If I save a configuration file, it will not write into the folder but just inside the parent folder with the name of the last "word" written in the path.

A video is more helpfull to understand :)

https://github.com/BlitterStudio/amiberry/assets/55721851/ad10d48d-ce50-45b1-a910-cf40aef6a144

**Comment by giantclambake** [comment]
Can't recreate this in linux ~ config path always includes trailing `/` whether you manually enter the path, or use the '...' widget to navigate to chosen location.

That said, the paths shown in the vid look like MacOS to me, and not linux...

@zognic  -- can you confirm? Is this linux or MacOS?

**Comment by zognic** [comment]
This is indeed Linux, specifically Batocera.Linux. We patched Amiberry to force the configuration path. After analysis, it appears that we unfortunately forgot the '/' at the end of the path, which causes this error.

**Comment by midwan** [comment]
This is handled better in the upcoming release anyway, by ensuring the path _always_ includes a trailing `/` when it's going to be used for such operations.

I assume we can close this Issue then?

**Comment by zognic** [comment]
Great thanks.
