### ISSUE TITLE
Input Port 2+3 Controllers are all moving Player 1 in 4-Player Games (Amiberry 5.6.8)

### ISSUE THREAD

**Issue by NoobieMaks** [BlitterStudio/amiberry#1253]
**More specific: The Controller D-PADS of Player 3 + 4 (Port 2 + 3) are all moving player 1!**

The analog sticks are working correct, all 4 Players can be moved by each controller separately.
Also the A button is working correct from each controller to each game character.

This is funny when you are playing Dynablaster and as player 3 or 4 you can move/influence player 1 with your D-Pad and your own character with the analog stick. Player 1 will not agree.

I really tried it over hours in many ways to be sure that it is really an issue of amiberry and not of the game or the controller.
Now I'm sure something is wrong in the controller translation of Input Port 2 and 3 in Amiberry.
3 different games had excatly the same problem:
- DynaBlaster_v1.6_0664.lha
(no custom-setting necessary - 3 player max. has no influence on this - just set 5 players in the game menu)
- DynaBlaster_v1.7_0664.lha
(no custom-setting necessary - 3 player max. has no influence on this - just set 5 players in the game menu)
- GreatCourts2_v1.5_0333.lha
(set 4 players in the game menu and all to "character" instead of "computer")

My Setup:
- Pi 3 B; latest Retropie buster (4.8.6) and the latest Amiberry release (5.6.8)
- 4 x PS3 sixaxxis controllers

I know the expected behaviour because in my older/other build every controller works separately correct with these games: stretch + RePi 4.5.11 + Amiberry 3.0.11

**Comment by midwan** [comment]
Fixed with 2cd36653472f2ec9fd11de6ff780a80045471306 - will be part of the next release
