### ISSUE TITLE
Doc: GUI -> Custom controls -> helptext [formatting, punctuation]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1255]
Just a quick fix-up after recent commit here;

![ex](https://imgur.com/DTwHJXn.png)

-quotation mark should be before the word button
-text strings exceeding width of display area

Some connective words added to better fit window presentation.

![ex2](https://imgur.com/PP8YGG1.png)

For ... src/osdep/gui/PanelCustom.cpp

```
        helptext.emplace_back(R"(You can use the "Save as default mapping" button, which will save the current mapping)");
        helptext.emplace_back("as the default for the current controller. It will be automatically applied on startup");
        helptext.emplace_back("for this controller. This option is only available in non-Retroarch environments.");
```

TIA

**Comment by midwan** [comment]
Thanks, fixed with b2d3ff2a8313e2b9f74ce9d4cbb3f31d7fbe2646
