### ISSUE TITLE
GUI->Configurations panel [cosmetic bug]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1256]
Only manifests itself when configuration files list exceeds height of panel display area.

Click on entry in list -> Load  ; the moment you move mouse cursor after clicking Load button, list 'jumps' to the bottom.

https://www.youtube.com/watch?v=qp14adQViZQ

TIA

**Comment by midwan** [comment]
This was an old piece of code, that would try to bring the selected item in view, if you loaded a config. The refresh happened after the redraw, and it would scroll too much as well.

I've changed it to apply immediately on loading, and scroll less than before.
