### ISSUE TITLE
Query: dropdown selector highlighting not dismissed after selection made [GUI theming]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1263]
This only becomes annoying/apparent if one chooses to have a 'light' font color.  Affects all dropdown selectors.

Not a problem with black and/or dark font colors -- 'default' GUI colors --> https://www.youtube.com/watch?v=ZEJTMKhL5pw

Same again with themed GUI (`gui_theme_font_color=250, 250, 250`) --> https://www.youtube.com/watch?v=3_MDKLax0Gs

At first blush, I think the easy fix would be to dismiss the pale-blue highlighting after selection is made.

However, if the user chooses something like  `gui_theme_font_color=171, 246, 248` , the text becomes 'invisible' during selection operations (near same color as pale-blue highlight).

That observation makes me think that a 'proper' fix, would be exposing that pale-blue highlight color to be configurable by the user (if at all possible), to better suit the font color they choose for their theme.

Thoughts?

TIA

**Comment by midwan** [comment]
Added new GUI theme option: selection color
