### ISSUE TITLE
WHD-booter process fails when applicable config.uae file found?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1265]
Easily recreate-able here;

-launch amiberry->GUI->Quickstart->Select whdload archive -> Start (game starts and runs fine parsing the XML)
-->F12->Configurations->Save (creates config.uae of appropriate name) -> Quit

..follow on with...

-launch amiberry->GUI->Quickstart->Select **same** whdload archive -> Start ...emulation boots to amigarom insert disk anim

note: one title popped amigados error 'no disk in drive'

I can only think the process fails to mount the virtual hard-drive paths, after whd-booter pivots from the XML to the config.uae file?

- config & failed startup logfile attached

TIA
[AceBall_v1.0_Pl_AGA.uae.gz](https://github.com/BlitterStudio/amiberry/files/14849519/AceBall_v1.0_Pl_AGA.uae.gz)
[amiberry.log.gz](https://github.com/BlitterStudio/amiberry/files/14849524/amiberry.log.gz)

**Comment by midwan** [comment]
Confirmed, this only happens when used from the GUI however - it works normally when used from the command line (`--autoload`).
