### ISSUE TITLE
GUI: 'gui_theme_selection_color' needs to apply  to popup selector window backgrounds as well? [GUI theming]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1267]
As always, a small vid is best way to example it -> https://www.youtube.com/watch?v=_egywwVKb_8

That is to say, I think that's the 'logical' fix...ie; I can't (personally) really see the need to expose selector window background as a customizable option ~ little doubt, some might argue that point and think the opposite is true, welcoming same.. hard to know.

@midwan ~ thanks for all quick fixups wrt gui customization, really appreciated, and I do believe this to be the last 'wrinkle' wrt to these changes afaict. Perhaps the only further place you might take this, is make certain elements 'skinable' ..ie; apply image data instead of solid color, or maybe tessellated patterns/textures a_la Amiga style (stick that on a wishlist if possible =), but right now you can make the amiberry GUI 'fit in', with most linux desktop themes out there... nice =)  

TIA

**Comment by midwan** [comment]
Can you post your theme values here, so I can test with those? It's hard to know if anything else might need an update, when it all looks OK for me :)

**Comment by giantclambake** [comment]
Although now fixed, FTR (and seeing as you asked =)

```
gui_theme_font_color=220, 210, 250
gui_theme_base_color=84, 8, 241
gui_theme_selector_inactive=153, 7, 87
gui_theme_selector_active=43, 88, 20
gui_theme_selection_color=45, 47, 154
gui_theme_textbox_background=4, 42, 243
```
