### ISSUE TITLE
GUI - Display - Amiga Screen: Width and Height are not shown as what they currently are (Amiberry 5.6.8)

### ISSUE THREAD

**Issue by NoobieMaks** [BlitterStudio/amiberry#1272]
Is it a wrong setting of mine or is it really an issue of amiberry?

When I've started a game (it does not matter which one) and I want to optimize the screen-size (for the .uae-file) and therefore I change the sliders for Width and Height I can see the changes when I go back to the game, but when I go back again to the GUI the values on the right side next to the sliders are again 1280 and 1024.
The sliders have stayed on the changed position.
Also the game has still the changed screen size.
So it seems that only these values are shown wrongly, in the background all settings are as they were done manually.

Example:
Fullscreen: 800x600
Screen mode: "Fullscreen" or "Full-window"
Width: Slider on the very right side - value 1280
Height: Slider on the very right side - value 1024
All other things don't matter.

Then make a change from the sliders to a middle position:
Let's  say W 704 and H 512
Slider change will also change the values beside.

Then go back to the game and back again to the GUI -> then I see the sliders are on the position I set them before but the shown values beside are no more  704 and 512, they are shown again as 1280 and 1024.

It does not really have effect for the game screen or the config-file but it is a little bit confusing.

**Comment by midwan** [comment]
This has already been changed in the upcoming version. It was changed a few versions ago to show the dimensions of the emulated window, but it ended up causing confusion so it has been changed back. :)
