### ISSUE TITLE
Virtual Keyboard is not shown in every Screen Mode (Amiberry 5.6.8)

### ISSUE THREAD

**Issue by NoobieMaks** [BlitterStudio/amiberry#1273]
I love the new "Auto Crop" function of Amiberry 5.6.8 and I use it for nearly every config-file because so I have the maximum game screen.
But the VKbd is not visible with this function, it opens but it is cut off of the picture because it is shown below the game screen, if you uncheck "Auto Crop" and go back to the game you will see the VKbd below the game screen.

**Comment by midwan** [comment]
That's a bug, the VKBD doesn't take into account the Auto-Crop results, and always opens up in the same location.
