### ISSUE TITLE
Magic Mouse Untrap 'capturing' mouse at moment it should untrap? [post #1277 commit]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1278]
v6.3.0-preview latest / x86-64 / Debian 12.5 (to eliminate nvidia drivers, also tested on LFS 11.3 x86-64 with same results) / X11 in both cases.

When moving mouse pointer towards edge of emulation window, instead of untrapping the mouse pointer (releasing it to host), the mouse pointer either 'disappears' and/or simply stops responding to mouse input (depends on which window edge you move mouse towards). No host (system) mouse pointer appears.

The only way to regain mouse input/pointer, is to hit F12 (GUI pops, host/system mouse pointer reappears), and hit F12 again to return to emulation window, where the 'native' mouse pointer in emulation starts working again (but you need remember to move the mouse away from the edge of the emulation window, to avoid it happening again). I deliberately not do that for the 2nd mouse 'freeze' in the vid below....that's kinda weird because the pointer locks up well after the moment it should've released (untrap) to host OS..

I note that when the mouse input/pointer is 'lost' by both emulation & host system, if you click the RMB, the Workbench top menubar responds in emulator, suggesting the mouse is still connected to the emulation process.  Indeed, using Alt-Tab in the host desktop environment doesn't respond in this situation, further suggesting emulation still has control.

I also note that using the MMB (manual untrap), LMB (retrap) as a toggle, the position of mouse pointer in emulation versus host desktop position is always off by some degree (not accurately tracking?).

As per my report in #1225, it's still the case that if you enable `Virtual mouse driver` in conjunction with `Magic Mouse untrap` it all works as expected ~ unfortunately speaking, `Virtual mouse driver` doesn't work with scalos desktop menus, and many  folks like the scalos suite (I imagine things like 'MagicMenus' will be similarly affected, but I should check)

As described above (sans last para) -> https://www.youtube.com/watch?v=ngAIYjycy44

TIA

**Comment by midwan** [comment]
There is a known issue with SDL2 and Wayland, regarding warping the cursor (which is not supported in Wayland): https://github.com/libsdl-org/SDL/issues/7937

This is used by Amiberry when Magic Mouse untrap is selected, in order to move the cursor slightly outside the window. So this part won't work, and it accounts for the difference in where the cursor is when it gets untrapped (it was supposed to be moved to the edge of the window).

I'll work on fixing the issue of "losing" the pointer, that was triggered after a certain WinUAE merge.

**Comment by giantclambake** [comment]
Understood wrt X11 versus Wayland.

This now actually works in X11 as you previously described ~ thanks for the quick fix ;)
