### ISSUE TITLE
Question: Can we handle retroarch.hdf files in GUI->Quickstart->WHDLoad auto-config?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1283]
The .hdf files in question -> https://archive.org/details/amigaromset  (scroll down to view last comments)

I am not sure if it's possible (or even desirable) to do so, however, it seems amiberry can handle pretty much all other formats of Amiga based media, and this would be another example of whdload based media.

Unsure how practical it is to do so, but it never hurts to pose a question ;)

TIA

**Comment by midwan** [comment]
I don't see much sense in this.
Amiberry already handles WHDLoad titles from `.lha` archives quite well, for several years now. And it continues to improve in that area, with updates in emulation accuracy and changes in the XML file it uses to auto-configure itself.

The HDF approach is relevant to P-UAE which doesn't have such a feature, and tries to solve the same issue: simplify launching of WHDLoad titles as much as possible.
