### ISSUE TITLE
WorldGames_v1.0_NTSC_0604.lha - Software Failure - Guru Meditation -  error after entering player name

### ISSUE THREAD

**Issue by NoobieMaks** [BlitterStudio/amiberry#1285]
The game start is still ok but after entering a player name the good old Amiga error in red appears - Guru Meditation, left mouse button and so on.

This happens in my current build (buster + RePi 4.8.6 + Amiberry 5.6.8), in my older build (stretch + RePi 4.5.11 + Amiberry 3.0.11) this does not happen.

I found out it helps to create a configuration file with some changes:
First I did it with only setting the cpu to 68020, this already solved the problem.
Later I turned it back to 68000 and it also worked when I additionally unchecked "More compatible".

Is this ok when I post such things here or should I post them next time in the amiberry xml channel of HoraceAndTheSpider?

**Comment by midwan** [comment]
Indeed, such reports are better done on Horace's XML repo instead.

**Comment by NoobieMaks** [comment]
@HoraceAndTheSpider
Do you recognize this issue from here or should I post it again in your repo?
