### ISSUE TITLE
Graphic issue with Zool2_AGA

### ISSUE THREAD

**Issue by NoobieMaks** [BlitterStudio/amiberry#1286]
Graphic issue with "Zool2_v1.0_AGA_0415.lha": When the level action starts the graphics turn to a kind of rushing.
I can also see this problem with the .adf files.

This happens in my current build (buster + RePi 4.8.6 + Amiberry 5.6.8), in my older build (stretch + RePi 4.5.11 + Amiberry 3.0.11) this does not happen.

**Comment by midwan** [comment]
This is a known issue with the version in `master`, which has been fixed in `preview` already.

**Comment by giantclambake** [comment]
Confirmed fixed in v6.3.0 preview /x86-64 (previously this title had other graphical issues which now seem fixed as well)
