### ISSUE TITLE
Query: Can you update wiki/miscellaneous page?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1308]
I'm looking to update the helptext for the Miscellaneous panel, which I note hasn't been revised in quite some time AFAICT.

As mentioned previously, I'm referencing the wiki content as the text guideline, however the following items are not covered by the wiki text (https://github.com/BlitterStudio/amiberry/wiki/GUI:-Misc) ;

`Always on top`
`GUI Always on top`
`Use RetroArch Reset button`

At your convenience, could you add these items to the wiki, along with the text description please?

Once that is done, I can edit the helptext in PanelMisc.cpp accordingly  ;)

TIA

**Comment by midwan** [comment]
Wiki updated
