### ISSUE TITLE
Query: amiberry cmdline -h/--help text should be updated?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1319]
Firstly, this grinds my gears a little bit (output of `./amiberry --help` );

```
 -f <file>                  Load a configuration file.
 --config <file>
```

I've never really questioned the `-f` switch, perhaps considering it was there for some 'legacy' support, however, in my mind I read that as  "-f <file>  load a configuration file into the GUI" & "--config <file>  load a configuration file into the emulator & GUI".

We also have a third option here now....` ./amiberry <file> `  ...ostensibly, all three are equivalent invocations.

There may be one corner case usage, where these observations matter ~ a config.uae file that has `use_gui=no` set. In that case, regardless of which cmdline option you use, it will result in the emulation starting immediately, using the specified config <file>.

To myself, the  `-f <file>` option should open/load the config.uae file, but ignore the `use_gui=no` setting if present (and the -G switch) -- this allows users to alter/edit the configuration, _before_ having to start the emulation and hit F12 to do that same thing (which is what we have now). It might save users time if they know they wish to change something first, perhaps saving them an emulator reboot (depends on what they want to change). A further option of ie; -d = dryrun, load but do not start the emulation, is the only other thing I can think of ... ;) 

Obviously, what's also missing from the --help output, is any reference to the `amiberry <file>` invocation, what '<file>' may be, and the fact this pretty much usurps the `--config / --autoload / --cdimage /  -0 <disk.adf>` cmdline options. Perhaps these capabilities where added, and didn't find themselves into the --help text?

TIA

**Comment by midwan** [comment]
Most of the options are the same as WinUAE, for compatibility and familiarity reasons. `-f` is an alias and does the same thing as `--config`, which is to load the selected config file when starting up. It's up to the contents of the config file then, if it will open the GUI or not - you can force it with the `-G` option if you wish.

I'll add the missing `amiberry <file>` feature, which is missing.

**Comment by giantclambake** [comment]
Thanks for the explanation & fix  =)
