### ISSUE TITLE
If GUI->Chipset->Cycle Exact (Full) is selected, this setting not saved to config.uae

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1320]
Example case -- http://aminet.net/demo/disk/Despair.dms

./amiberry floppies/Despair.dms  //goes off the rails after intro sequence

F12->Chipset panel -> enable Cycle Exact (Full) -> Reset  //demo now runs as it should, so create/save config.uae file

F12->Configurations->Save  to create/save the 'conf/Despair.uae' file -> Quit amiberry

Open the conf/Despair.uae file in textedit, to see  `cycle_exact=false`

TIA

**Comment by midwan** [comment]
Fixed with 8eade20c543c771efc9d3e3772a9f738ffacf2b2
