### ISSUE TITLE
Query: GUI -> Chipset -> Cycle Exact (Full) always shows enabled

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1323]
On the relevant wiki/GUI:-Chipset page it reads;

> Cycle Exact: These options allow you to enable Cycle Exact mode for the Chipset. This will increase compatibility, but also requires significantly more resources to emulate, so it's not enabled by default. Currently only available for A500 emulation.

Launch amiberry -> Chipset panel, this option shows as enabled. Further, changing the Amiga machine type...ie; A1200 ...this option still shows as enabled.

AFAICT, this might be due to the fact the default amiberry.conf file does not contain the param  `cycle_exact=false` ?

TIA

**Comment by midwan** [comment]
It's only enabled in the Preview v6.x versions, which is following WinUAE closely.

**Comment by midwan** [comment]
Wiki updated to reflect that difference. The screenshots and docs refer to the v5.x versions still, and there are differences in v6.x that are not in the Wiki at this point.

**Comment by giantclambake** [comment]
Understood, thanks for the clarification & wiki update ;)
