### ISSUE TITLE
Query: highlighting on CPU&FPU/Sound panels [cosmetic]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1326]
In the CPU and FPU panel, even though JIT is **not** enabled, the Direct/Indirect options' text still _appear_ active;

![ex](https://imgur.com/JRB80EO.png)

In the Sound panel, even though Floppy drive sound is **not** enabled, the Empty/Disk in drive text and % value still _appear_ active;

![ex2](https://imgur.com/v37uyzr.png)

Should these be 'ghosted' when the parent setting is not active? (the rest of the GUI follows that behavior ;)

TIA

**Comment by midwan** [comment]
Indeed, some widgets did not get greyed out when disabled. That's a minor bug in the `guisan` library, will get it fixed.
