### ISSUE TITLE
GUI -> Hard drives/CD --> Create Hard disk file -> Filename: textbox  [cosmetic]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1327]
This one was nestled away (I typically use directories)...

![ex](https://imgur.com/htFX2Rr.png)

Missing `textbox_background` ?

TIA

**Comment by midwan** [comment]
Fixed with 28e91e24382644cfff3f0e6ca8ac3f111c7afe98 (for `preview` only for now, will merge into `master` later)
