### ISSUE TITLE
Query: is it possible to extend configuation file auto-naming to include CD32/CDTV images? [feature]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1336]
Basically the same request as #1254 but for .cue/.bin/.iso image files.

Note: whilst this does work using the `./amiberry <file>`  invocation, you need enter the `Name:` field manually if building a config 'from scratch' using the GUI alone.

TIA

**Comment by midwan** [comment]
You mean when using the GUI then? In other words, you'd like to set a config name, as soon as you insert a disk image in a drive? Not sure that's a good idea.

**Comment by giantclambake** [comment]
> you'd like to set a config name, as soon as you insert a disk image in a drive?

No, that behavior would not be aligned  with how we treat other image types ;) Time to expound...

floppy images:  

GUI->Quickstart->Select file (load a floppy image into DF0:) ...follow on with Configuration panel, and note the `Name:` textbox has **not** been populated with the filename of the floppy image.  

Start --> emulation begins with defaults using the selected floppy image. If that title works fine and requires no further amiberry configuration, then ostensibly that title does not require an associated config.uae file. In this case, user can quit the emulation by using the `Quit key:`  assignment, or on the desktop just by closing the amiberry window.

OTOH, after starting the emulation, user may discover the floppy image loaded **does** require further configurata, ie; floppy title might be AGA only, or require tweaks to CPU/Display options, and in this case user would;

F12 to GUI -> make required changes -> Configurations panel --> the `Name:` and `Description:` textboxes are now filled accordingly/correctly, and user just needs to click on `Save` to create the associated config.uae file.

WHDLoad images:

GUI->Quickstart->WHDLoad auto-config: -> Select file (load a whdload.lha title into the 'slot')...follow on with Configuration panel, and note the `Name:` textbox has **not** been populated with the filename of the .lha archive.

Start --> emulation begins with defaults contained in the XML, for the selected whdload.lha image. If like above, that title works fine and requires no further amiberry configuration, then ostensibly that title does not require an associated config.uae file. In this case, user can quit the emulation by using the `Quit key:`  assignment, or on the desktop just by closing the amiberry window.

OTOH, after starting the emulation, user may discover the whdload image loaded **does** require further configurata, ie; require tweaks to CPU/Display options, and in this case user would;

F12 to GUI -> make required changes -> Configurations panel --> the `Name:` and `Description:` textboxes are now filled accordingly/correctly, and user just needs to click on `Save` to create the associated config.uae file.


On the desktop (or in console using **mc** and edited extensions .rc), the above is expedited by using the invocation `amiberry <file>`  ...(on the desktop that would be double-click or right-click on the Amiga title icon, to invoke 'Open with amiberry') In effect, this merely eliminates the need for the first step in both examples above, that is, starting the GUI, selecting/loading a file, and clicking Start. 

In practice, the same user experience pans out ~ if the Amiga title runs fine, and requires no further configuration, you can quit the emulation when finished...user might never see the amiberry GUI at all in this case ~ simply put, they didn't need it ;) OTOH, they can still use F12 to bring up the GUI, make any changes required, and easily save an associated config.uae for that title, so that next time that title is direct-launched with amiberry, no further configurata is required.

Now....I'm expecting the same process handling, wrt CD32/CDTV images, but what we've got is;

GUI->Quickstart->change Amiga model: to CD32 -> Select image (load image file into CD) ....follow on with Configuration panel, and note the `Name:` textbox has **not** been populated with the filename of the cdrom image.

Start -> As above, no config.uae required, quit amiberry when finished.

OTOH, after starting the emulation, user may discover the cdrom image loaded **does** require further configurata, ie; require tweaks to CD turbo/CPU/Display options, and in this case user would;

F12 to GUI -> make required changes -> Configurations panel --> the `Name:` and `Description:` textboxes are **NOT** populated with the filename nor description in this case, so users have to manually enter the Name: textbox that exactly matches the cdrom image(.extension) name, to save the associated config.uae file. I would expect these textbox fields to be auto-filled as per the examples above.

Note: Using the expedited route of `amiberry <file>`  or equivalent does work as expected, with the Name:/Description: fields already populated if you need to use F12->GUI to change anything, and save a config.uae file.

There is never the case wherein just loading an image file (of any type), sets the name of the config.uae file --- that only happens, _after_ the emulation is started, and you invoke the GUI using the F12 key. Only then is the config.uae name/description appear to be set.....except of course with CD32/CDTV images as described =)

Due to the fact this didn't really affect the cmdline/desktop usage case of direct launching an Amiga image with amiberry, was the moment I discount the possibility that there's amiberry users out there, who prefer to open the GUI, and play around, create/save configurations using the GUI (including CD32/CDTV titles) as desired, and that's fine, however they will be that little bit inconvenienced by the fact that when doing this with CD32/CDTV titles, the config.uae filename will have to be manually and accurately entered in every case.

Does that make it clearer?

OTOH, if there's a reason behind this current behavior, I'm all ears =)
