### ISSUE TITLE
GUI->Hard drives/CD->Add hardfile->'...' --> 'Select hard disk file' window should not have a 'Create folder' button... 

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1338]
`preview`/x86-64

....because creating a new folder serves no purpose here? (user can do that from the `Create Hardfile` button as required) 

TIA

**Comment by midwan** [comment]
The button is added to the generic dialogs of SelectFile/SelectFolder, so it will appear anywhere they show up.
I don't see that as an issue, however. ;)

**Comment by giantclambake** [comment]
Probably not an issue, unless you're into silly humor ... I can think of a great comedy sketch for EAB here, starts out something like....

_Amiberry ~ the only cross-platform Amiga emulator with 59 places you can create a folder!!_ 

_Are you sick and tired of not being able to easily create a folder in your Amiga emulator, even though you don't need to create a new folder? Well.. ...Amiberry has you covered!! Did you just want to select a floppy disk file?....no worries, create a folder instead!! It's not what you wanted, and it's not what you needed, but the Create folder button is there, so USE IT!! The power of creating a folder (that you don't need), gives you a rush like no other software!!_

We asked a few typical Amiberry users, about this new holistic 'Create folder' button...

'AJ' ~ "_I was blown away by the Disk Swapper panel. I only went there to add/select a few floppy images, but then I discovered there were 20 different buttons here I could use to create a new folder, and I was hooked!! I don't know how many new folders I created at the time, but it was at least 20!! It was so easy._"

'Suzy' ~ "_When I discovered you could create a folder from within the WDHLoad panel, I just had to try it! I was only there to load/select a whdload.lha file, but when I saw that create folder button, I went all weak at the knees, and started creating new folders with gay abandon...it was such a release!!_"

'CT' ~ "_I didn't think it was possible to create a new folder from within the ROM panel, because after all... you're just there to select an Amiga ROM file, but I quickly discovered you could create a new folder from this panel as well! I think I created around 10 new folders here....not that they serve any purpose, and I'll probably never use them, but it was such fun to create totally pointless, useless directories ~ I can't think of any other software that's even close to this_."

However, we discovered not all users were so positive about this new Amiberry feature....

'LM' ~ "_Being able to create a folder anywhere, regardless of whether that was your intention or not, and irrespective of the fact you didn't need to create a new folder to begin with, I think veils the fact that there should be a 'Delete folder' button, for every 'Create folder' button present...it just makes sense, no?_"

'SD' ~ "_I tried some of the new create folder buttons, but I make lots of typos and need a 'Rename folder' button!_"

------------------------------------------------------------------------------------------------------------------------------------------------------

If I posted something like that on EAB, embellished a little more to cover all panels, and adding images along the way, and then posed the dangling open question at the bottom --- "Does anyone see an issue/problem here?" .... what do you reckon the replies might be? I really have no idea, (I have a suspicion =), but I'm quite prepared to post same just to find out ...ie; perhaps I'm the only person on Earth who thinks this is all Monty Pythonesque type of 'silly'?

In Australian vernacular, this fits under the adage of "As useful as tits on a bull" ...(the create folder buttons everywhere =).

Perhaps it's just me? That is, English being my first language I tend to carry participle adverbs and nouns, across the context of the comprehension..... ie;

Add directory  / Create folder  --- add existing directory, or, create a new directory to be added.

Create image  / Create folder  --- create a file.image, or, create a new directory in which to create a file.image

Select file or image / Create folder --- non-sequitur ~ what is being created, **cannot be selected**.
|
When I referenced how winuae handles this specific situation, I used the words "it's not immediately obvious" (#1329)

What I'm referring to there, is winuae is using a 'folder selector' ... and the 'create folder' function is obfuscated 'behind' the Open button. That is to say, if a directory name entered into the textbox does not exist in currently displayed path, pressing the Open button firstly **creates** a directory of the specified name (2ndary function), and then **opens** that newly created directory (primary function). I can think of several programs that follow the same convention wrt the 'Open' button....ie; if specified directory does not exist, create it first and then open it.
|
|
Applying the above premise...ie; what is being created (a directory), must be immediately loadable/selectable by the file selector window currently being used, whittles it down to the following **3** panels wrt the amiberry GUI ;

`Paths panel` ~ it may be polemical as to how useful it might be, but the created folder(s) are/is selectable & usable here.

`Floppy drives panel` ~ again polemical, but the `Create 3.5" DD/HD disk` buttons can make immediate use of a newly created folder here, in which to create the new floppy disk images.

`Hard drives/CD panel` ~ create folder is immediately useful for `Add directory` & `Create hardfile` buttons, to create a directory to add, or,  in which to create the new .hdf image(s).
.
.
That's it... three panels... but personally speaking and in practical terms, I only see the four buttons mentioned really benefiting from, and being able to make direct use of, the Create Folder feature....2 panels/4 buttons ;)

If the `Create Folder` button cannot be limited to those places in the GUI wherein it's functionality serves a practical, real purpose...then for mine, what works best here is a `Create Folder` button, on the `Hard drives/CD` panel, directly under the `Add Directory` button (move the `Create Hardfile` button to the right so it's under the `Add Hardfile` button).

That may seem somewhat counter-intuitive at first glance, but it occurred to me that one could use that `Create Folder` button, not just to create a harddrive directory, but you can use it to create a directory in any other location that amiberry might use as well. Obviously it's not quite as good a solution as limiting `Create Folder` to the 3 panels/4 buttons identified above, but it does provide the means to create a directory anywhere for amiberry's purposes (including the polemical examples =) 

What I do know for sure however, is if one goes 'Select file', it makes no sense at all to be able to create a directory, that you cannot select, because it's not a file .. it's a directory.

//PS; happy day, just found out I'm going to be a great-grandfather before I'm 70yo ;)

**Comment by giantclambake** [comment]
Much better, thanks.....btw, nice avatar update =^)

**Comment by midwan** [comment]
Thanks 😊 
And congrats on the great grandfather status!
