### ISSUE TITLE
default_auto_crop in config isn’t respected?

### ISSUE THREAD

**Issue by limi** [BlitterStudio/amiberry#1340]
I am currently experimenting with a handheld emulator setup for [AmigaVision](https://github.com/amigavision/AmigaVision), and I am using Amiberry running under Batocera Linux — specifically, the build for the [Anbernic RG35XX H](https://github.com/rg35xx-cfw/rg35xx-cfw.github.io/releases/tag/rg35xx_plus_h_batocera_20240306) — a pretty common ARM-based handheld. I am having problems with some of the config settings, however.

To reproduce:

In `amiberry.conf`, I have the following lines (I have included the default values as comments for context):

```
default_correct_aspect_ratio=yes
;default_auto_crop=no
default_auto_crop=yes
;default_width=720
;default_height=568
default_width=640
default_height=480
```

…but when I load Amiberry, the Auto Crop function is off, and when I bring up the Amiberry UI, the Auto Crop checkbox is unchecked. If I check the box and Resume, the functionality works, but I can never get it to stick, neither through saving a custom setup, nor by manually adding it to `amiberry.conf`

Other values (e.g. the resolution) are respected, it’s only this function that doesn’t seem to get its value from the config file. Am I missing something obvious, or is this value not being picked up from the config file?

When using the same settings on my desktop OS install of Amiberry (macOS, M1), it seems to work fine.

Is there anywhere else this could be overridden that I am not aware of?

* Handheld version is Amiberry v5.6.1
* Desktop version is Amiberry v5.7.0

**Comment by limi** [comment]
Could this be the same as #1235? That would explain it.

**Comment by giantclambake** [comment]
Probably ... trying amiberry v5.7.1 on the Anbernic RG35XX H would be a good test.

**Comment by limi** [comment]
Is there a binary available that would run? Or do I need to look into cross-compiling?

**Comment by midwan** [comment]
The linked issue above was about the aspect ratio option not being respected (which got fixed). I'm not sure it's the same issue. 

Try leaving the default width/height values unchanged to see if it makes a difference? Normally, you can either use one or the other, so maybe something is being overridden there.

**Comment by midwan** [comment]
@limi I have binaries with every release, for the most common platforms (Raspberry Pi, x86_64, macOS x86_64 and macOS Apple Silicon). The Linux versions are compiled for Debian (Bullseye and Bookworm, now that Buster is reaching EOL). The RPI4 has a special version compiled for Manjaro Linux as well.

Not sure if any of these would work on your board under Batocera, you might end up having to compile it yourself for it.

For the record, I cannot recreate the problem in the latest version, so I'd recommend you upgrade to that one and try again.

**Comment by limi** [comment]
There’s no easy way for me to get the newer version on this device (long story), so we can probably close this. Seeing as you can’t reproduce + it works on my M1 Mac install that is running 5.7, it’s probably fixed.

**Comment by midwan** [comment]
@limi Alright, let me know if anything else comes up about it, and we'll take a closer look.
