### ISSUE TITLE
Capsimg.so is now built in the plugin directory.

### ISSUE THREAD

**Issue by Lex15** [BlitterStudio/amiberry#1341]
If you manually build capsimg.so its built in the plugins directory now. Amiberry still looks for it in the binary directory.

**Comment by midwan** [comment]
It should be opening it from the `plugins` directory, normally.
Are you on the latest version?

**Comment by midwan** [comment]
The code is designed to look for it in the defined `plugins directory`, which is user-defined, with the default value being `<binary path>/plugins`. Check what you have in your `amiberry.conf` file, or the Paths panel, for this specific path.

This is new with 5.7.x as it didn't exist before.

From my tests here, it seems to work as expected, opening the library from within the `plugins` directory by default.

**Comment by NoobieMaks** [comment]
@midwan:  Where should the file "retropie.pkg" be located at 5.7.x?

**Comment by midwan** [comment]
@NoobieMaks No idea, that file is not part of Amiberry.

**Comment by NoobieMaks** [comment]
OK Thanks

**Comment by Lex15** [comment]
Sorry the issue was at my end, I was using an old conf file.  I hadn't noticed the new plugins path.

**Comment by midwan** [comment]
@Lex15 no worries, happy to see it worked as expected :)
