### ISSUE TITLE
Query: GUI->Quickstart->Amiga model: CD32 ....should Input->Port 1: also change to 'CD32 pad'?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1346]
`preview`/x86-64

If you launch amiberry -> GUI -> Quickstart -> Amiga model:CD32->Config: CD32+8mb-> Select image (any CD32 image) --> Start

The emulation/title starts, but you'll soon discover there's no input from the gamepad axis controls.... ergo, F12 -> Input panel, and in my case the XInput Controller on Port 1: is set to `Default`  --> change to `CD32 pad` --> Resume, and now gamepad works in the emulation as it should....

I would have expected the 'default' controller device for the selection model=CD32, to actually be CD32 pad? Perhaps especially so, when using the Quickstart panel route? 

FTR, invoking `./amiberry cdroms/SomeAmigaCD32.iso` does work in that fashion, with the input device set to `CD32 pad` automatically ...I'd argue the same should be so for the Quickstart panel when Model=CD32 is selected.

To be complete, the same behavior should be evident for model=CDTV if selected (but I'm unsure what the default selection should be here...gamepad?) I didn't actually test the CDTV case..yet... ;)

TIA

**Comment by midwan** [comment]
The default is only changed with the autoloader currently, as we tried to make things easier (single "click" to get things running). 

The behavior from Quickstart on the other hand, is identical to that of WinUAE. It doesn't change controller types depending on the model selected, and leaves those to the `Default` option. I guess the logic there was that you don't know beforehand what the user has connected in the controller ports, and it's expected that they will make that choice themselves.

But I agree, it would make sense to automate this a bit more, for the sake of simplicity. I mean, the user can always go there and change it to something _else_, if that's needed.
