### ISSUE TITLE
Query: GUI->Input panel ~ Mouse/Joystick auto-switching always selected?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1349]
In the wiki this is described as;

_Mouse/Joystick autoswitching
This option enables a feature that will automatically switch which device is connected to a port (between a mouse and a joystick), depending on which button or direction was used on the device._

However the Input panel helptext describes;

_Auto-switching enables you to switch Port 0 between Mouse-Joystick based on which device is being used. Only works if type is left to Default._

If the latter is correct, should this option be greyed-out when the type is set to something other than Default?

Currently the option is always available (and selected) irrespective of the input type selection.

TIA

**Comment by midwan** [comment]
Hm, I'm not 100% if it _only_ works in the `Default` mode, I think I picked that up from WinUAE's (sparse) docs somewhere. I don't see anything in the code that checks for the specific mode of the port, when triggering this function, so perhaps that description is obsolete.

WinUAE does not disable that checkbox if you change mode either, so perhaps to be on the safe side, I'll remove that last sentence from the help text, instead. :)
