### ISSUE TITLE
Implement Integer scaling method

### ISSUE THREAD

**Issue by midwan** [BlitterStudio/amiberry#1352]
Implement Integer scaling mechanism in Amiberry.

It should be possible to select from the GUI, saved to the config file, and even set as the default from `amiberry.conf`.

Some background info: 

* https://amiga.vision/2021.03.13
* https://amiga.vision/2023.06.06

WinUAE already has integer scaling, but I think it's only for RTG modes there. We should implement this for all modes.

**Comment by limi** [comment]
Sounds great! Especially combined with Auto-Crop, this should make it possible to get something close to what we do on MiSTer on the scaling front. Count me in for testing.
