### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by StusBrainDump** [BlitterStudio/amiberry#1354]
Now that Apple have relaxed their stance on emulators appearing on the App Store, do you intend on releasing an iOS/iPasOS version?

Please 😬

**Comment by midwan** [comment]
I'd love to, but there are a few obstacles:
- I'd need a Apple developer account, which they charge for on a yearly basis (AFAIK)
- I'd need Apple device(s) to develop and test on, and I have none :)
