### ISSUE TITLE
SpaceQuestEnhanced_v1.3_MT32_2222.lha does not start (missing xpkmaster.library v4)

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1362]
//while checking through MT32 capable whdload titles

`preview`/x86-64

To recreate:

`./amiberry SpaceQuestEnhanced_v1.3_MT32_2222.lha`   //cmdline or GUI

I see an AmigaDOS warning about  xpkmaster.library v4 not found while whdload splash screen is shown.

Title continues to load, before bailing to CLI with the following;

![ex](https://imgur.com/QMuo6Vq.png)

It appears  xpkmaster.library is contained in the `whdboot/boot-data.zip` however I'm unsure of version.

Is this an amiberry issue, or something else?

TIA

**Comment by midwan** [comment]
I am not sure about this, but I _think_ someone mentioned something similar in the past. But I can't remember what the proposed solution (if any) was, either.

@HoraceAndTheSpider do you remember something about this?

**Comment by giantclambake** [comment]
Correct ~ I recall discussion about this as well in the past, but cannot recall exactly where that thread is.

**Comment by midwan** [comment]
We have 3 separate issues, related to XPK:
- https://github.com/BlitterStudio/amiberry/issues/250
- https://github.com/BlitterStudio/amiberry/issues/358
- https://github.com/BlitterStudio/amiberry/issues/455

@HoraceAndTheSpider has added the XPK libraries in the booter zip file, but as I recall, they are only used/activated if the `slave_libraries` option is enabled.

I can't check right now, but is that enabled, for this title? If not, it should get an update in the XML (something you could test by modifying the XML entry for this specific title manually).

**Comment by giantclambake** [comment]
//...dissection..... I sort of remember some of this....

I believe the problem is disclosed at the CLI...

![ex](https://imgur.com/3VIFalo.png)

On the Amiga side, Libs: is assigned to DH0: ...however, the libraries it's searching for are in DH3:Libs/

When the emulation stops at this point, on the host side, you can edit `/tmp/amiberry/s/startup-sequence` thusly, to add the 'missing' Libs: assignment...

```
FAILAT 999
IF NOT EXISTS WHDLoad
DH3:C/Assign C: DH3:C/ ADD
DH3:C/Assign Libs: DH3:Libs
ENDIF
CD "Games:SpaceQuestEnhancedMT32"
WHDLoad SLAVE="Games:SpaceQuestEnhancedMT32/SpaceQuestEnhancedMT32.slave" PRELOA
D NOREQ NOWRITECACHE SAVEPATH=Saves:Savegames/ SAVEDIR="SpaceQuestEnhancedMT32"
DATA="data"
```
...after saving the edit, F12 -> Reset  ...emulation restarts, and slowly chokes to death before throwing a guru ~ it's as though it found the required library, and then something went horribly wrong during decompression.

Yeah, I was wondering about the `Slave Libraries` checkbox ...did try, had no effect.

**Comment by midwan** [comment]
Try changing the entry in the XML, I think the GUI there is currently read-only for that checkbox

**Comment by giantclambake** [comment]
Edited the XML entry to  `<slave_libraries>True</slave_libraries>`  //was set to **False**

`./amiberry SpaceQuestEnhanced_v1.3_MT32_2222.lha`  ...same error, cannot find xpk libraries.

**Comment by midwan** [comment]
OK, thanks. I'll take a look when I get a chance then, unless @HoraceAndTheSpider has any ideas before that.

**Comment by giantclambake** [comment]
@midwan  --- not your problem, I accidentally edited the wrong snippet ... ;-/

I had a read thru #455 and tested 'Ivan ''Ironman'' Stewart's Super Off Road (NTSC)' ... it crashed and burned to a guru, in likewise fashion as the title mentioned here. I rechecked the XML and realized my error..

- when `<slave_libraries>True</slave_libraries>` is set, the SuS contains the added libs: assign ;

```
FAILAT 999
DH3:C/Assign LIBS: DH3:LIBS/ ADD
IF NOT EXISTS WHDLoad
DH3:C/Assign C: DH3:C/ ADD
ENDIF
CD "Games:SuperOffRoadNTSC"
WHDLoad SLAVE="Games:SuperOffRoadNTSC/SuperOffRoadNTSC.Slave" PRELOAD NOREQ NOWRITECACHE SAVEPATH=Saves:Savegames/ SAVEDIR="SuperOffRoadNTSC"
```

-- when dumbdumbs here retested with the correct edit in the XML, SpaceQuestEnhanced_v1.3_MT32_2222.lha was handled in the same way when `<slave_libraries>True</slave_libraries>` is set.

So the issue, is the emulation is gagging on XPK library handling ; both XML snippets are using 68000 profile...

-edit the XML snippets for these titles, to include CPU=68020 and retest --> both titles now start and run...albeit a bit brisk through menus and such, game music sounds fine...

Ergo... either the xpkmaster.library used is 68020 only, or, it's supposed to be 68000 compatible, then the CPU emulation is failing at some point?

HTH, and mia culpa for the error ;) 

--depending on the position of `DH3:C/Assign LIBS: DH3:LIBS/ ADD` in the SuS, determines whether or not the whdbooter menu screen appears.

**Comment by giantclambake** [comment]
Found it... my speculation above was correct.  

`wget ftp://de.aminet.net/pub/aminet/util/pack/xpk_User.lha`

In /whdboot/boot-data/Libs we have;

`-rwx------ 1 gcb gcb 16496 Jan  3  2016 xpkmaster.library`   //this is the 68020+ version

In xpk_User/Libs_1.3/ we have;

`-rwxr----- 1 gcb gcb 10860 Dec  9  2000 xpkmaster.library`  //this is the 68k version

I did a snoopdos to find out which compressor it's after --> `xpkSQSH.library`

The version in /whdboot/boot-data/Libs/compressors/  is the 68020 version.

So...the `<slave_libraries>True</slave_libraries>` has to be set for these titles, and the xpk*.libraries contained in /whdboot/boot-data/Libs have to be changed to their 68000 versions.

I have yet to find any whdload.lha file that requires 68020 versions of these libraries -- this doesn't mean they don't exist ;)

HTH

**Comment by giantclambake** [comment]
Of course they exist ~ DungeonMaster_v1.2_0833.lha ...

Initially, it had `<slave_libraries>False</slave_libraries>` set in the XML ~ after changing that and retesting, title decided to start and runs....poorly. This means it was happy with the 68020 XPK libs ; the reason for that, is the XML snippet for this title has `CHIPSET=AGA`  ...(which I think infers CPU=68020 ?)

According to HOL, this is/was an OCS/ECS title -> https://amiga.abime.net/games/view/dungeon-master

Unfortunately speaking, changing to the 68000 version of the XPK libraries, and changing the XML (removing AGA setting so 68k is used), results in the same crash as when not using CPU=68020 with those XPK libs...

It's starting to look like a rock and a tight place... changing the XML for these titles to CPU=68020 might be the only resolve...

**Comment by midwan** [comment]
I think it would be best to set them to use an 020 or perhaps a full A1200 config, unless there are issues with that. I expect most of them would work fine like that.

**Comment by midwan** [comment]
@HoraceAndTheSpider ping, this seems like an XML issue

**Comment by giantclambake** [comment]
Now that I have a handle on it, I'll retest just using CPU=68020 for these titles (instead of CHIPSET=AGA)...

I did a control of installing xpk_User into a A600/ks-2.1 hdd install, and the 68k version of xpkmaster.library flies off the rails there as well, so that's a rock...

**Comment by giantclambake** [comment]
Right...wrt `preview`/x86-64..

Both snippets for `SpaceQuestEnhanced_v1.3_MT32_2222.lha`  and  `SuperOffRoad_v1.3a_NTSC.lha` require;

```
<slave_libraries>True</slave_libraries>

<hardware>
CPU=68020  

```

CHIPSET=AGA also works in both these cases, so I'll leave that choice with you ;)

The Dungeon Master v3.6 title is being a pita for some reason, I'll need recheck with it's most recent slave...

**Comment by midwan** [comment]
XML snippet changes should be reported in Horace's repo, so assuming that is done, we'll close this issue here.

**Comment by giantclambake** [comment]
Done ~ I've pinged @HoraceAndTheSpider .... in his hands now ;)
