### ISSUE TITLE
Amiberry 4.7.1 does not run on RetroPie 4.8

### ISSUE THREAD

**Issue by Lukaszb11** [BlitterStudio/amiberry#1366]
Hello!

I have a problem with running Amiberry 5.7.1 under retropie 4.8. Fresh installation on RPI4B. Amiberry does not start. The contents of runcommand.log include:

`"$emulator" "${params[@]}"Parameters:`
`Executing: bash "/home/pi/RetroPie/roms/amiga/+Start Amiberry.sh"`
`Launching...`
`./amiberry`
`malloc(): unsorted double linked list corrupted`
`/opt/retropie/emulators/amiberry/amiberry.sh: line 107: 1870 Aborted "$emulator" "${params[@]}"`
`~`

**Comment by giantclambake** [comment]
Looks to be same issue as cited in discussion #1295

**Comment by midwan** [comment]
Make sure you update RetroPie itself to the latest version, then install it from their menu. Last time I tested it was a few days ago, and it seemed to work like that.

**Comment by jzakotnik** [comment]
Same issue here... Installed binary and from source, with a fresh install from yestefday.

**Comment by midwan** [comment]
@jzakotnik You can alternatively use the pre-compiled binary from the Releases page, which seems to work better under RetroPie: https://github.com/BlitterStudio/amiberry/releases/tag/v5.7.1

Pick [amiberry-v5.7.1-debian-buster-armhf-rpi3.zip](https://github.com/BlitterStudio/amiberry/releases/download/v5.7.1/amiberry-v5.7.1-debian-buster-armhf-rpi3.zip) or [amiberry-v5.7.1-debian-buster-armhf-rpi4.zip](https://github.com/BlitterStudio/amiberry/releases/download/v5.7.1/amiberry-v5.7.1-debian-buster-armhf-rpi4.zip) depending on your device.

**Comment by mtc-7** [comment]
> @jzakotnik You can alternatively use the pre-compiled binary from the Releases page, which seems to work better under RetroPie: https://github.com/BlitterStudio/amiberry/releases/tag/v5.7.1
> 
> Pick [amiberry-v5.7.1-debian-buster-armhf-rpi3.zip](https://github.com/BlitterStudio/amiberry/releases/download/v5.7.1/amiberry-v5.7.1-debian-buster-armhf-rpi3.zip) or [amiberry-v5.7.1-debian-buster-armhf-rpi4.zip](https://github.com/BlitterStudio/amiberry/releases/download/v5.7.1/amiberry-v5.7.1-debian-buster-armhf-rpi4.zip) depending on your device.

I had the same issue and error in the log. After wasting a lot of time trying to get it to work. I did this and it worked!

Thanks
