### ISSUE TITLE
Support for Raspberry Pi 1 dropped intentionally?

### ISSUE THREAD

**Issue by MichaIng** [BlitterStudio/amiberry#1371]
With https://github.com/BlitterStudio/amiberry/commit/618a834 support for RPi 1 was removed together with DispmanX. The latter makes sense, but why was RPi 1 support removed along with it? It works with KMS/SDL2 graphics backend as well.

**Comment by midwan** [comment]
Because it meant keeping some special code just for CPUs that don't support NEON instructions, and I believe not a lot of people use Amiberry on that platform anymore. 

Do you have information to the contrary?

**Comment by MichaIng** [comment]
I see. Let me check our user survey ...
```console
root@dietpi:/home/dietpi-survey/survey# for i in *; do grep -q '\[armv6l\]' "$i" && grep -q '\[108\]' "$i" && echo "$i"; done
02ac1578-a5eb-4099-9d45-MASKED.txt
3c24bbb7-f5cf-4713-b487-MASKED.txt
4e03d081-bcdd-42df-a957-MASKED.txt
55417f5f-91bd-41f5-9b3d-MASKED.txt
da00142e-6315-477c-a579-MASKED.txt
```
19536 of 136509 recognised systems share usage data: https://dietpi.com/survey/
Hence this could be extrapolated to 136509/19536\*5~=35 ARMv6 DietPi systems running Amiberry. One of them is my RPi Zero W test system, if I am not mistaken.

This is from 94 reported Amiberry installs, or extrapolated 136509/19536\*94~=657, or 5/94\*100~=5% of all Amiberry installs done on DietPi via `dietpi-software`.

So indeed not significant, but there are some. The question is how much efforts it is to add the NEON code conditionally. Maybe it makes sense to ignore it until someone else is complaining about this. We are currently doing v5.7.1 builds for ARMv6, which is fine as long as they do not differ too significantly build/implementation-wise. And secretly, I am hoping as well for ARMv6 RPi's to die, as they are causing tons of special case coding and maintenance, starting with the dedicated Raspbian (instead of Debian) APT repository etc. They are loosing support increasingly everywhere, it is just sad for those who are happily still using them, and of course want to keep running recent software 🙂.

**Comment by midwan** [comment]
@MichaIng 
If there is a demand, I could bring back the support for it. It was conditional anyway, like the Dispmanx stuff.
I haven't had a single user mentioning that platform for a few years now, and considering the requirements to run games at full speed, it's not an ideal platform for Amiberry anyway.

So, I think we'll go with this for now, and see what happens. :)
