### ISSUE TITLE
Add the ability to open CD media contained as a .zip file?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1381]
The majority of Amiga CD titles, come as .zip archives, containing the {.bin/.cue/.iso/.wav} files.

Currently, we have to unpack said zipfiles, into ie; cwd/cdroms/titlename-dir/* , and then start amiberry to select the appropriate file from within that directory.

It would expedite this process, if users could just copy the .zip into cwd/cdroms, and in amiberry, be able to select/load these .zip files, as if they were images. 

I did some further testing (CD32 only, ~20 titles), to cover off the target handling in the case wherein the .zip archive contains more than 1 'valid' launch target.

-- if the zip archive contains multiple .bin files, load the lowest numbered .bin file... //the other .bin files are actually .wav files
-- if the zip archive contains both .bin and a .iso file, load the .iso
--  if the zip archive contains a .cue file, use that regardless of what other files are present. This can be a special case ; loading the .cue first often involves an intro sequence anim ; loading the .bin or .iso loads straight to game, bypassing intro. This will happen with some titles anyway, that are Amiga/CD32 compatible ... ie; mount the cdrom in a WB-1.3 setup, and double click on the game icon, it loads straight to the game, as the A500 model type can't do the intro anim ...game plays fine =) As clicking a controller button anytime skips the intro, loading the .cue seems 'proper'...(else do it in a config.uae).

I believe as we're already sensitive to the CD32/CDTV word 'hints' in `<filename>` , and the .zip archives follow that convention wrt their naming..ie; jotd_arcade_cd32.zip (simplistic but real example ;), we can avoid any entanglement with ie; handling multiple floppy files in a .zip, very early on just by filename detection..(otherwise, open the zip and see what's inside, and decide what to do next..)...it probably has to be looked at holistically in this way anyhow, if the cmdline is  ./amiberry somename.zip  ;)

What do you think?

TIA

**Comment by midwan** [comment]
Seems like too much work for an edge case - I'd be happy to implement it if this is done on WinUAE, but otherwise I feel like my time should be spent elsewhere, for now...

**Comment by giantclambake** [comment]
Fair enough.... would be nice though  ;)
