### ISSUE TITLE
Query: GUI -> Paths panel  --> paths in textboxes are editable, but manual edits not saved?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1385]
Using the `'...'` select widget to specify a path, will have the path selection saved to `conf/amiberry.conf`

 Although you can manually edit the contents of the textbox containing the path, these changes are NOT saved to the `conf/amiberry.conf` file...

....really depends on how one connotes the textboxes...ie; are they _supposed_ to be editable, or merely meant to _display_ the current path selection?

TIA

**Comment by midwan** [comment]
Currently they are only for showing the paths, not editing.
I _could_ change them to allow editing also, but we'd need a trigger (or multiple valid triggers) to pick-up the changes and save them. E.g. when Enter is pressed?

**Comment by giantclambake** [comment]
I was unsure what would be consistent/proper here....ie; consider the Hard drives/CD & Disk swapper panels, wherein the paths are only displayed (not editable). The Paths panel differs in this respect.

One side of me says to make the Paths non-editable.... this removes the chance of typos. One can select a path, or create a new directory from the '...' widget, and in theory at least, manual edits here (or the need for same) would be far & few between in practice.....(even if a typo is made creating the dir, it would still be a valid path)

....however, as they present as editable, users might try to do that, but the manual edits will not be saved....which leads to this confusion. Hence my query...

Should these textboxes merely display the selected path(s)?

If not, then yes...you'd need a trigger, and the Enter key would be the logical choice ;)

**Comment by giantclambake** [comment]
Thanks ~ I believe this is the right choice, as IMHO it improves consistency/look of the GUI overall as well ;)
