### ISSUE TITLE
MT-32 ROMs not found if the file names are upper-case

### ISSUE THREAD

**Issue by lavadrop** [BlitterStudio/amiberry#1386]
I have my mt32-roms folder populated with my MT32_CONTROL.ROM and MT32_PCM.ROM files but the MIDI section of the IO Ports configuration displays "Munt MT-32 (Missing ROMs)".

- OS: openSUSE Tumbleweed

- Version 6.3.3 preview

**Additional context**
Flatpak version.

Are you checksumming the roms for a specific firmware version or do you use the new MAME dumps?

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by giantclambake** [comment]
Just now checking the MUNT code, valid roms are checked by sha1sum ;

```
gcb@gallah:~/Amiberry/kickstarts/mt32-roms$ sha1sum *.rom

a439fbb390da38cada95a7cbb1d6ca199cd66ef8  cm32l_control.rom
289cc298ad532b702461bfc738009d9ebe8025ea  cm32l_pcm.rom
b083518fffb7f66b03c23b7eb4f868e62dc5a987  mt32_control.rom
f6b1eebc4b2d200ec6d3d21d51325d5b48c60252  mt32_pcm.rom
```

The above is what my working romset looks like ;)

**Comment by lavadrop** [comment]
Yeah, one of my MT-32 roms was the wrong version. Apparently, amiberry's munt is case-sensitive, it only detects lower-case file names.

**Comment by giantclambake** [comment]
Indeed, thanks for pointing that out ~ it is only detecting lower-case filenames for the roms, I hadn't noticed that previously (I didn't test upper-case for these filenames ;) ... that should probably be improved.

@midwan 

Considering we verify the rom files here against the sha1 hash, perhaps we should parse both lower & upper case filenames for the Munt rom files .... if only to make it easier on users, and to avoid further situations like this?

TIA

**Comment by midwan** [comment]
Yes, the code in that area is pretty much identical to that of WinUAE, but of course on Windows you don't have case-sensitive file handling, so this was missed. :)
I'll get it fixed with the next release.

**Comment by giantclambake** [comment]
...other way around... "MT-32 ROMs not found if the file names are **upper**-case" ... =)

**Comment by midwan** [comment]
Fixed the description, thanks
