### ISSUE TITLE
Query: Can we expedite GUI->Configurations panel handling? [enhancement]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1391]
This has slowly been driving me nuts, primarily because it's at odds with the _demonstrated intent_ of the user.

Here, the _demonstrated intent_ is in the case where the user has unticked 'Start in Quickstart mode' (Quickstart=0) ~ I believe we should be deducing, this signifies the next user action is going to be select/load or double-click on a listed config.uae entry. We do not do this ... the game-controller case, is the most effected. Presuming Quickstart=0 is set....

Launch amiberry -> GUI -> lands on Configurations panel ...with game-controller...

dpad right -> no visible feedback to the user that focus has been shifted to list panel
dpad up/down -->now focus is on a list entry, at the end/beginning of the list respectively

I believe it would be better, when the Configurations panel is selected, the first config.uae entry in the list should already be in focus/highlighted (not loaded) ..so that game-controller users can immediately scroll up/down the list for the file they with to load. Likewise, desktop users would also benefit from this, as they can immediately use their mouse scroll-wheel to navigate the list for whatever config.uae they want to load.

The rest of the time, the currently loaded config.uae is displayed as selected and loaded here...that's working fine ;)

Thoughts?

TIA

**Comment by midwan** [comment]
@giantclambake 
I think I improved this now. If the configs list has any rows, the first one will be automatically selected (unless you have already loaded one, in which case that remains selected as before).

If this works as expected with the commit above in `preview`, I can merge it to `master` as well, before the new release.
