### ISSUE TITLE
Show FPS Adjustment field in GUI

### ISSUE THREAD

**Issue by midwan** [BlitterStudio/amiberry#1397]
@midwan According to Toni Wilen on this thread: https://eab.abime.net/showthread.php?t=118242
...There's a field on WinUAE where the user can type-in a static vertical refresh rate.
That field is locatted on the bottom-right area of "Display" on the WinUAE GUI.
That would somewhat solve the lack of "sync to host refresh", by being able to specify a known refresh rate matching the one used by the host computer.
Can you *please* display that field on Amiberry 6.x too?

_Originally posted by @vanfanel in https://github.com/BlitterStudio/amiberry/discussions/1390#discussioncomment-10236432_

**Comment by vanfanel** [comment]
@midwan As I said on our fruitful discussion (thanks a LOT for this!), this feature needs the number of audio samples adjusted according to the emulated framerate adjustment.
Shouldn't this function do precisely that? (ie: modify the number of samples generated per second to prevent generating too many or too few for the adjusted emulation framerate): 
https://github.com/BlitterStudio/amiberry/blob/daeb32732942e668b1c6f5bcf030ef250b3bd653/src/sounddep/sound.cpp#L104

**Comment by midwan** [comment]
Yes, but currently that function is not called from anywhere.

WinUAE would call that from a few different implementations (`finish_sound_buffer_al`, `finish_sound_buffer_xaudio2`, `finish_sound_buffer_wasapi_push`), but I couldn't really figure out how to use it from SDL2 when I wrote this, so I left it unused.

**Comment by midwan** [comment]
@vanfanel 
I've just added one attempt of doing this, with the Push mode only (the Pull mode uses the SDL2 callback, still not sure how I could do the resampling there). Give it a try and see if it helps.

**Comment by vanfanel** [comment]
@midwan I tried it, and it doesn't work correctly at all: When I enable audio push, there are very noticeable video hiccups and audio dropouts.
Sorry. I know you are trying you best on this. I'm also trying to help as you see: I think well synchronized Amiga emulation is perfectly possible with this.
