### ISSUE TITLE
xml database out of date

### ISSUE THREAD

**Issue by fommil** [BlitterStudio/amiberry#1402]
**Describe the bug**

In these docs

https://github.com/BlitterStudio/amiberry/wiki/Structure-of-the-whdload_db.xml-file

referring to the file last updated in https://github.com/BlitterStudio/amiberry/commit/c98fde6b8d27cd999efafda2937b397abfc2b7b3

> the XML is generated through regular scanning of the popular RetroPlay LHA Installed packages. The scanned packages are then validated against external information to determine whether additional settings should be included. This scanning occurs at-minimum weekly, with the updated XML uploaded via the scanner's own GitHub page.

But the file hasn't been updated for at least 6 months whereas the underlying data has moved on, for example all the SensibleWorldOfSoccer* titles have received a v2.2 and a v2.3 update since then.

Could you please update the database or explain how it can be updated by scanning? I think I can probably update the few titles I'm interested in by hand but that's not very scalable.

**To Reproduce**

Evident from the file itself.

**Comment by fommil** [comment]
I'm guessing you're parsing this file in some way: https://ftp2.grandis.nu/turran/FTP/Retroplay%20WHDLoad%20Packs/Commodore%20Amiga%20-%20WHDLoad%20-%20Games%20(07-08-2024).zip

since it contains the file names and checksums and so on, although there's a *lot* of places claiming to host the whdload files and they don't always agree with each other. e.g. I have absolutely no idea what this one is https://www.whdload.de/games/SWOS.html because these only seem to have the `.slave` files and so on and seem to be used to build the runnable lha files (apologies for my ignorance on all of this, I'm trying to piece it all together from what I find as I go).

**Comment by midwan** [comment]
@fommil 
The XML is maintained in another repo: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder by another person (@HoraceAndTheSpider).

Even though I update the copy I have in Amiberry's repo from time to time, you can always download the latest one available from the above repo, by using the related button in Amiberry's GUI itself (Paths -> Update XML). Needless to say, you'll need to be connected to the internet to do so.

**Comment by midwan** [comment]
Now updated in this repo as well with 70c9a1b5cef182d727541a44beff566fd91b74cf, with the latest version
