### ISSUE TITLE
Query: GUI -> WHDLoad panel --- textboxes should not appear editable?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1403]
This is similar to #1385 --- in the WHDLoad panel, these textboxes _present_ as editable...

![ex](https://imgur.com/OCJe7Zl.png)

AFAICT these fields are filled with the data from the whdload.lha file, and really should not be editable by the user?

TIA

**Comment by midwan** [comment]
The first three should be read-only, yes.
The rest are actually editable, except Salve Data Path.
