### ISSUE TITLE
Query: Can we add ability to rename hardfile Device name?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1410]
I was looking at setting up 'AmiKit' for use with amiberry ~ checking the config.uae for that install (uses WinUAE)...I see ;

```
hardfile2=rw,AK0:..\AmiKit\AmiKit.hdf,0,0,0,512,0,,uae
uaehf0=hdf,rw,AK0:..\\AmiKit\\AmiKit.hdf,0,0,0,512,0,,uae
filesystem2=rw,AK1:RabbitHole:..\AmiKit\RabbitHole,-128
uaehf1=dir,rw,AK1:RabbitHole:..\AmiKit\RabbitHole,-128
filesystem2=rw,AK2:Dropbox:..\AmiKit\Dropbox,-128
uaehf2=dir,rw,AK2:Dropbox:..\AmiKit\Dropbox,-128
```
In WinUAE GUI when adding a hardfile, the Device field is empty allowing you to name the Device whatever...ie; AK0: as above.

In amiberry, you cannot do this -- the first hardfile is always DH0: , the second DH1: etc...but there is no way to change this.

![ex](https://imgur.com/osCgD5x.png)

You **_can_** edit this field in the Add Hardfile dialog, however it reverts to DH0: when you click on OK to complete process.
 
![ex2](https://imgur.com/6dLw6za.png)

TIA

**Comment by midwan** [comment]
Of course you can change the device name, DH0 is only auto-generated there when you add a new item.
After you add your hardfile, try changing DH0 in that window to something else, before pressing OK.

**Comment by giantclambake** [comment]
That was sublime.... even though the Device field is likely the first entry one would edit, that's doesn't work. 

You must change everything else first (including adding the hardfile) in the Add Hardfile dialog, and changing the Device must be the last thing you do before hitting OK.

Seems 'upside down' but works (I don't believe order in which you change fields should matter ~ hitting OK should present all edits made, regardless of which order they were edited).
