### ISSUE TITLE
KMSDRM: Odd screen handling when toggling between GUI/emulation windows

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1411]
RPi4/bookworm/KMSDRM ~ evident in `Master` & `Preview`

To recreate;

At the console issue the cmd  ./amiberry AmigaTestKit.adf

-emulation boots showing the AmigaTestKit GUI fullscreen --> hit F12 to pop GUI, hit F12 again to return to emulation

-- AmigaTestKit GUI reappears, no longer fullscreen with H/V uncentered (looks to be in a different resolution)

 --> hit F12 to pop GUI -> Display -> **uncheck** Correct Aspect Ratio --> hit F12 to resume

-- AmigaTestKit GUI reappears, now fullscreen again -> F12, hit F12 again to return to emulation, AmigaTestKit GUI reappears, no longer fullscreen with H/V uncentered

 --> hit F12 to pop GUI -> Display -> **check** Correct Aspect Ratio --> hit F12 to resume

-- AmigaTestKit GUI reappears, now fullscreen again -> F12, hit F12 again to return to emulation, AmigaTestKit GUI reappears, no longer fullscreen with H/V uncentered

...wash, rinse, repeat ;)

TIA

**Comment by midwan** [comment]
I noticed that after the fix yesterday, but didn't have time to look into it further. It's a side-effect of using a single window, as I don't modify the window if it's already there (so it will use whatever last settings it had).

**Comment by giantclambake** [comment]
Ahh, ok...that explains it ~ it's not actually Correct Aspect Ratio perse, it's more the case that enabling/disabling that option, prompts the code to re-evaluate the desired window settings...or such'n'similar.

**Comment by midwan** [comment]
Should be fixed now, at least according to my tests :)
