### ISSUE TITLE
Window resize middle button MacOS

### ISSUE THREAD

**Issue by cwscws** [BlitterStudio/amiberry#1421]
As there is no middle button on MacOS how to resize the emulation window?
The system built in shortcut left command + left mouse button does not work.

Can this be set in the .uae config file?
Tried
gfx_width_windowed=1450
gfx_height_windowed=1050
but this also does not work.

What's the trick?

**Comment by midwan** [comment]
If you mean using Middle click to release the capture, you can also achieve that with Alt-Tab (if the option is enabled in the Misc panel)

**Comment by cwscws** [comment]
I would like to change window size for the windowed mode. As I wrote changing tha values in the config files does not do anything. What to do?

**Comment by midwan** [comment]
You can manually resize the window, but if you change resolutions it will be reset to the resolution size.
Custom window sizes that persist in the config, are not supported I'm afraid. Maybe in the future.

**Comment by cwscws** [comment]
Ah, ok. Thank you for the info. I was used to it in FSUAE.

**Comment by midwan** [comment]
The GUI itself has a scaling factor that can be used, if that seems too small (this is found in `amiberry.conf`). But that doesn't apply to the emulation screen.

**Comment by cwscws** [comment]
The emulation window is really tiny on my iMac, so this is not really suitable for me. At least a scaling factor 2x would be nice.

**Comment by midwan** [comment]
I can try using the same scaling factor option the GUI uses, for the Windowed emulation screen as well. It might be enough for now.

**Comment by midwan** [comment]
Added in both v5.x and v6.x sources, will be part of the next release
