### ISSUE TITLE
Add RTG emulation of PicassoII/PicassoII+ video boards? [Amix] 

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1423]
Now that I can install Amix using amiberry, it would be nice to get X11R5 up and running in that installation.

To do that, we need emulation of the video adapter hardware used, and it seems these boards are the best option (blitter support) in this regard. I understand this may take some time to implement, but the long term goal would be to emulate all aspects of hw required by Amix, and getting X11R5 working seems to me the next step (and beyond that, get network adapter hardware emulation running ;).

TIA

**Comment by midwan** [comment]
Should be fixed with 2bd584115c4be0823d285a3a04586298e6f8211b
