### ISSUE TITLE
Settings that are not read from the config file

### ISSUE THREAD

**Issue by limi** [BlitterStudio/amiberry#1450]
The following settings are not read from a given `.uae` config file:

* Amiberry forgets the Kickstart ROM file every time you restart Amiberry (even when loading a config). The correct value is written to the .uae file, so looks like it's a read issue.

* Checked RDB state for a hard file never gets loaded from the config file.

* When you initially add a Hardfile and want to use it in RDB mode, you have to add it first without RDB selected, then go back in and check the RDB box again before it works.

**Comment by giantclambake** [comment]
> Amiberry forgets the Kickstart ROM file every time you restart Amiberry (even when loading a config). The correct value is written to the .uae file, so looks like it's a read issue.

Can you give steps to reproduce please? The word 'restart' is a tad ambiguous.....ie; the Restart button, or quit amiberry and relaunch amiberry?

**Comment by solskogen** [comment]
If you choose a kickstart that's not in the kickstart/rom directory, but rather use the file selector, this happens. 
Just save config, and press the Restart button in Amiberry, and see the problem unfold.

**Comment by limi** [comment]
> Can you give steps to reproduce please? The word 'restart' is a tad ambiguous.....ie; the Restart button, or quit amiberry and relaunch amiberry?

Yes, quit the app and relaunch, then load the relevant config. (I assume the same issue exists with `default.uae` if that gets loaded on startup)

**Comment by midwan** [comment]
The RDB issue is already solved in the newer version (not yet released, but in the current repo).
The other one seems like a bug :)
