### ISSUE TITLE
If XDG_DATA_HOME is set, no ~/.local/share/amiberry directory is created. 

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1457]
Instead, it thinks HOME should be ~/.local/share/*  and sprays that location with amiberry specific dirs/files

Should be ~/.local/share/amiberry/*

See attached ~ resultant amiberry.conf after first time start (puppylinux example)

TIA

[amiberry.conf.gz](https://github.com/user-attachments/files/17253585/amiberry.conf.gz)

**Comment by midwan** [comment]
Added in the `preview` branch for testing, please confirm when you get a chance?

**Comment by giantclambake** [comment]
Yep, that behaves as expected now ~ the only outlier is the $libdir seems out of place  /usr/lib/x86_64-linux-gnu/amiberry
