### ISSUE TITLE
Update caches after manual install

### ISSUE THREAD

**Issue by midwan** [BlitterStudio/amiberry#1462]
This happens automatically with the DEB ...but in the TGZ, as a result of the `--install` flag, we should be doing something like...
```
if [ -x "which update-desktop-database 2>/dev/null" ]; then
    update-desktop-database
fi
if [ -x "which update-mime-database 2>/dev/null" ]; then
    update-mime-database "@CMAKE_INSTALL_PREFIX@/share/mime"
fi
if [ -x "which gtk-update-icon-cache 2>/dev/null" ]; then
    gtk-update-icon-cache -f -t "@CMAKE_INSTALL_PREFIX@/share/icons/hicolor"
fi
```
and likely mandb has to be run as well

**Comment by midwan** [comment]
I'm not sure if this is a good idea to have in the install steps, or if it should be mentioned in the Wiki instead

**Comment by giantclambake** [comment]
'Traditionally' as it were, as in that cusp period when these tools were created, many used a bash helper script to be called at the end of 'make install' (in the autoconf/automake days ~ indeed, I believe I got the snippet above, from such a script ;)

After my expedition through mime-types and friends, I see now there's lots of conditions (wrt distro layout) you'd need check for, to get a 'one size fits all' result ... so yeah, lets go with a mention in the Wiki....

...that'd be  wiki/Compile-from-source ... at the end of **Local installation** .... how about...

_As this installation method is considered 'custom' by nature, for maximum flexibility the usual update-desktop-database,
update-mime-database, gtk-update-icon-cache and mandb commands are **not** run. This allows for any custom/specific update commands to be run after installation, to best suit your system requirements._

 ?

**Comment by midwan** [comment]
Yeah, I think that's a safer bet as well.

**Comment by midwan** [comment]
Updated wiki: https://github.com/BlitterStudio/amiberry/wiki/Compile-from-source
