### ISSUE TITLE
Improve GUI textbox presentation? [cosmetic]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1478]
Best place to see this, is in the Configurations panel (select between Name: & Description: fields), but it also effects other textbox widgets in the GUI...

![ex](https://imgur.com/ablQJJ5.png)

* line width of highlighted textbox borders too thick  //can overlap font
* font color showing at left side of textbox     //really shouldn't be showing this
* visually looks incorrect compared to textbox name string

![ex2](https://imgur.com/ySoelEm.png)

All textbox widgets are affected -- as discussed, likely to do with libguisan update.

TIA

**Comment by midwan** [comment]
This should be looked into after #1477 is done, to avoid having to re-do it again...
