### ISSUE TITLE
Latest WinUAE sync point?

### ISSUE THREAD

**Issue by jacereda** [BlitterStudio/amiberry#1484]
Hi,

I'd like to attempt pulling some changes from WinUAE. Can you share which WinUAE commit is the last sync point for your master branch?

Thanks.

**Comment by midwan** [comment]
At the time of writing this, the latest WinUAE commit merged would be 0c0a444f02381647a751c4e30eae29fd9456cf3a

**Comment by jacereda** [comment]
Great, thanks.
