### ISSUE TITLE
Docs: improve wiki/Compile-from-source

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1489]
I noticed a couple of problems here ~ I'll cite this relative to a fresh debian Bookworm amd64 installation... we have ;

`sudo apt install cmake libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libflac-dev libmpg123-dev libpng-dev libmpeg2-4-dev libserialport-dev libportmidi-dev`

* the apt `cmake` target _recommends_ [gcc, make], however these will not be installed as they are not required dependencies.

On a freshly installed system (or an instance not used yet to build/compile software, and nothing has yet called for DKMS), the above will generate 2 failures trying to compile amiberry ...1. 'make' not found ...2 'cc' missing.  If you want this to work, you either have to add the apt targets `gcc`  and `make` , or include the apt target `build-essential` in the above command.

*the apt `git`  target is missing.

Again, on a freshly installed debian Bookworm system, the git package may not already be installed. If not, the command in the instructions... `git clone https://github.com/BlitterStudio/amiberry` ...will invariably fail. If you want this to work, you have to add the apt target `git` to the above command, to ensure it is installed.

There is no foul if any package is already installed, as apt will just skip over any targets already present in the system.

TIA

**Comment by solskogen** [comment]
Does it look better now? :)

**Comment by solskogen** [comment]
As long as you use homebrew, no. Not sure about macports. Perhaps even git is part of macOS now.
