### ISSUE TITLE
Running parallel (multiple) amiberry instances ~ possible?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1495]
After buying AmiKit12 and testing it, I was (fortunately) provided an AmiKet12 USB stick image to test....

...in AmiKit you call on the host web-browser (using hostrun) to get down and nasty with the outside world... now... fact is the HP 800G1 test mule has enough grunt to run multiple instances of amiberry.... certainly ample to run two instances + browser...
﻿
...the way AmiKit is staged, you're calling the amiberry binary from down in `$home/amikit/amiberry` and that's fine ... what it allows for, is a system-wide installation of amiberry to exist, alongside the existing AmiKit layout....in theory...

...in this scenario, with AmiKit running in emulation, when the throw to hostrun web-brower happens, the browser inherits the system-wide mime-type associations, provided by the amiberry deb.pkg...

....this means, if you're using said browser to peruse for whdload.lha archive packs, after downloading they can be launched automatically in another instance of amiberry....call it 'preview mode' if you like ; after trying you can decide whether or not you want to unpack and keep it handy, for use >inside< the AmiKit environment itself... which is still running of course...

...current problem with this, is it won't work, as amiberry ...or amiberries ...8) ...will default to ~/.config/amiberry/ for the primary amiberry.conf file (and wrt AmiKit, this in turn sets the Configurations path, which then encompasses a default.uae file, which throws a spanner in the works for auto-loading whdload.lha files)...

...the only way I can think of to manage that situation, would be to have a ***runtime*** env_var, such as... ie; AMIBERRY_ROOT_DIR ... which points to somewhere else other than ~/.config/amiberry/ ...this would allow for something like '`mv /usr/bin/amiberry /usr/bin/amiberry.real`' and you could create a /usr/bin/amiberry bash script that called '`AMIBERRY_ROOT_DIR=$HOME/Amiberry /usr/bin/amiberry.real`' and obtain the result required... I *think*.... (you need to avoid using any -option_flag, for ease of use when it comes to `amiberry <file>` ..)

...my understanding is, this is possible wrt WinUAE, involving the use of 'winuae.ini' files ~ it then occurred to me that whilst everything else wrt paths is more or less configurable, the *one* thing there's no control over, is the location of the amiberry.conf file to be loaded... and although I'm thinking about AmiKit here, it's not too hard for me to imagine the usefulness of being able to run two (or more) amiberry instances, each one with it's own dedicated amiberry.conf file (and with that, all the directives it contains).... read: custom implementations

What do you think...is something like this possible?

TIA

**Comment by midwan** [comment]
It's certainly possible to run multiple instances of Amiberry.
I think the main issue here, is the existence of the `default.uae` config, which is a special type of file, as it gets auto-loaded if found (I believe WinUAE does the same).

If that doesn't exist, I think things would work as you'd expect. Launching a separate instance will still respect your configured defaults, and run alongside the previous one.

I've run such an example with multiple instances during my Lightwave renderfarm project. :)

**Comment by giantclambake** [comment]
Hmm... ok, so just confirming ~ the use of a `default.uae` config file, `effectively` means any other instance of amiberry will follow those directives (even if you'd prefer it not to)....ie; if default.uae specifies a A1200 machine type, all instances of amiberry will also boot by default to A1200 ....you're basically 'locking' every amiberry instance into that formal?

**Comment by giantclambake** [comment]
> I think the main issue here, is the existence of the default.uae config

Correct ~ upon further investigation of the guest OS (along with host setup), I found the use of default.uae to be more than less superflous in effect ; with some scripting changes, the use of default.uae can be eliminated, and I can achieve the results described above without touching amiberry logic at all...in fact, it's a bit more flexible than first imagined..  ;)

Closing as a curio 8)
