### ISSUE TITLE
v5.7.4 MacOS Sequoia 15.1 on Silicon - crashes after clicking 'Start'

### ISSUE THREAD

**Issue by ryanfantus** [BlitterStudio/amiberry#1506]
**Describe the bug**
When launching 5.7.4 and selecting a valid configuration, I then click 'Start' and expect UAE to launch. However, it just crashes and gives the "Reopen/Report/Ignore" MacOS selection box.

**To Reproduce**
Try to launch any valid config on 5.7.4 using MacOS Sequoia 15.1

**Expected behavior**
Emulation environment launches

**Desktop (please complete the following information):**

- OS: MacOS

- Version 15.1 Sequoia

**Additional context**
[preview-v6.3.4](https://github.com/BlitterStudio/amiberry/releases/tag/preview-v6.3.4) works as expected

**Comment by giantclambake** [comment]
@ryanfantus  ...Hi, thanks for the report ~  just friendly FYI as it were ... by rights, this should have been reported in the amiberry-lite repo (as we've talking about amiberry v5.x ;) ... https://github.com/BlitterStudio/amiberry-lite/issues

The [change](https://github.com/BlitterStudio/amiberry/wiki/First-Installation) is somewhat recent, and it's understandable you didn't know you were using 'amiberry-lite' ... (unfortunately I don't own that hardware, and can't check for you).

**Comment by midwan** [comment]
@ryanfantus 
As @giantclambake wrote above, this belongs in the Amiberry-Lite repo after the split.
However, you should really be using the "full" Amiberry version on anything more powerful than a Raspberry Pi 5, there's no real benefit for you running the v5.x version.
