### ISSUE TITLE
GUI -> Expansion panel ...[sub] expansion rom field displaying full path

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1507]
When setting up A2386SX expansion options, specifically here the VGA adapter part, I *believe* the rom file has been auto-detected and selected, however I cannot see/verify _exactly_ which rom file has been selected, because the full path to that rom file is included in the textbox ...ie; it should just display the rom filename ~ we already know it was found in $rompath  ;)

![ex](https://imgur.com/eWBPaG0.png)

Note: in this case, there a 4 possible rom files which can be used

TIA

**Comment by midwan** [comment]
I don't think I have that rom file to test with here.
It doesn't seem to be part of WinUAE's expansion roms package, usually found in the Zone either.
Maybe you could send the file to me, so I can try to recreate this? I'd like to see the behavior in WinUAE specifically, since maybe the same thing happens there (in which case, it should be fixed there as well).

**Comment by giantclambake** [comment]
Sure, see attached. After some reading, I figured out these were the rom files ppl have used for this.

I am unsure if the *,vbi rom files are detected/used (they weren't selectable in the GUI).

I believe it's the `vgabios-0.7a.cirrus.bin` rom file being detected ....(I'm not sure VGA mode is yet working as expected)

[vgarom.tar.gz](https://github.com/user-attachments/files/17740325/vgarom.tar.gz)

**Comment by midwan** [comment]
Thanks for the files. I already had the A2386SX ones, just not the VGA ones.

WinUAE does not seem to auto-detect it at all:

![image](https://github.com/user-attachments/assets/41778ae6-7ce7-407c-b6cd-b58fb121a497)

I can select it manually of course, but then it shows the full path to the file, like your screenshot above.

**Comment by giantclambake** [comment]
Yeah, seems a bit non-consistent... seeing as I can't get VGA mode to boot (always CGA boot), I suspect there's something wrong here ;)

**Comment by giantclambake** [comment]
Also note, I *believe* the correct rom file, for the (auto-selected) video card entity `CL-GD5426`, would be the rom file named `5426.vbi` ....however, you cannot select this file, as I think the `.vbi` extension doesn't qualify in the selector as a 'valid' rom file, and therefore not included in the selectable list.

**Comment by giantclambake** [comment]
Further to this ~ if the required rom files are copied into $rom_path, the results are tallied in `amiberry.ini` ~ see attached for my example file....

...start amiberry, GUI -> Quickstart -> A4000 model --> Expansions -> select MacroSystem ...

![ex](https://imgur.com/IOCBuHB.png)

....I'd have every expectation to interpret that as board model unavailable, no ROM selected, and I can't alter the RAM size -- the actuality is, the board is emulated internally, no ROM is required..and.... ---> Start --- emulation boots ks-rom --> F12

![ex2](https://imgur.com/XBpnT6i.png)

.....*now* it looks active, with ram quantity adjustable --- this is all sort of 'upside-side'... I should be presented with these widgets at the time of configuring the machine --> once the emulation is started, you shouldn't be able to change these fields....

....that's just one example, there's many others obviously....particularly things like video/RTG cards, with the GUI not updating in response to choices (or not being able to change things until after emulation has started)....

**Comment by giantclambake** [comment]
...back to this again, I configured another setup, this time glimpsing as I go... turns out I was correct...

```
x86vga_rom_file=/home/gcb/Amiberry/roms/A2386SX 1.00 391168-01.bin
x86vga_rom_file_id=37003E0C,A2386SX BIOS 1.00
a2386_rom_file=/home/gcb/Amiberry/roms/A2386SX 1.00 391168-01.bin
a2386_rom_file_id=37003E0C,A2386SX BIOS 1.00
```
....unless that's a combined rom image, I get the impression it's wrong ~ looking at the first couple of images above (including WinUAE), it's indication is CL-GD5426 will be emulated.

Most of this stuff is in `src/pcem/vid_cl5429.cpp` but it's difficult for me to unravel ~ the one line that piques my interest;

`return cl_init(CL_TYPE_AVGA2, "cbm_sl386sx25/c000.rom", -1, 0);`

I believe it's looking for `return rom_present("5429.vbi")` .....however, you cannot select *.vbi files in the GUI (and although those *.vbi files are present, there's no indication in the logfile that such is being loaded.

**Comment by midwan** [comment]
> Further to this ~ if the required rom files are copied into $rom_path, the results are tallied in `amiberry.ini` ~ see attached for my example file....
> 
> ...start amiberry, GUI -> Quickstart -> A4000 model --> Expansions -> select MacroSystem ...
> 
> ![ex](https://camo.githubusercontent.com/a7066dd918e1ddeb58e5e5bc4e941a1620a5e9fb5bf9bd87b455edcbe210f178/68747470733a2f2f696d6775722e636f6d2f494f43427548422e706e67)
> 
> ....I'd have every expectation to interpret that as board model unavailable, no ROM selected, and I can't alter the RAM size -- the actuality is, the board is emulated internally, no ROM is required..and.... ---> Start --- emulation boots ks-rom --> F12
> 
> ![ex2](https://camo.githubusercontent.com/2006e34a38d4a2b0fdd0d89ec4694bda087028000e3b0d4cb70f41492d3f5dba/68747470733a2f2f696d6775722e636f6d2f5842706e5436692e706e67)
> 
> ....._now_ it looks active, with ram quantity adjustable --- this is all sort of 'upside-side'... I should be presented with these widgets at the time of configuring the machine --> once the emulation is started, you shouldn't be able to change these fields....
> 
> ....that's just one example, there's many others obviously....particularly things like video/RTG cards, with the GUI not updating in response to choices (or not being able to change things until after emulation has started)....
> 
> [amiberry.ini.gz](https://github.com/user-attachments/files/17799382/amiberry.ini.gz)

This part should be fixed now

**Comment by midwan** [comment]
I think this is an upstream bug as well, as WinUAE also filters the filenames based on the `.rom` and `.bin` extensions. In any case, I've added `.vdi` to that list, so you should be able to select those files now
