### ISSUE TITLE
GUI -> Paths panel ...fix alignment of vertical scrollbar [cosmetic]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1508]
...some of this goes back to #1409 --- with the latest guisan updates, that has largely been addressed, however I noticed it also revealed another goofy in the Paths panel....

![ex](https://imgur.com/mrvr4KZ.png)

...that purple vertical line should not be present at the left edge of the scrollbar...

... .theme file attached ...

TIA

[pastel.theme.gz](https://github.com/user-attachments/files/17700126/pastel.theme.gz)

**Comment by midwan** [comment]
@giantclambake 
See if the above commit makes things better :)

**Comment by giantclambake** [comment]
@midwan  ...much better now with that commit, kudos  ;)

![ex](https://imgur.com/XhnMFX2.png)

Closing - fixed by  [e865c9b](https://github.com/BlitterStudio/amiberry/commit/e865c9bf461e45d16a55e127e0def5b99d852206)
