### ISSUE TITLE
[Docs]  wiki/GUI:-Paths ....needs updating.

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1510]
In no particular order;

The "kickstarts" directory has been replaced by the "roms" directory.... in that result;

*the depicted image is old, and doesn't reflect this change

*the wording there-under, makes reference to the "kickstarts" directory, which has been replaced with "roms"

Further to all this.... and I think this is a corollary of the addition of the `amiberry.ini` creation step... I noticed in logfile, it's actually scanning the `roms`  directory in a descending, recursive fashion... ie;

```
ROM scan directory '/home/gcb/Amiberry/roms'
ROM scan directory '/home/gcb/Amiberry/roms/A2630'
ROM scan directory '/home/gcb/Amiberry/roms/A2630-07'
ROM scan directory '/home/gcb/Amiberry/roms/mt32-roms'
```

We make no mention of this fact ~ consider the case of the WinUAE expansions.zip archive...

![ex](https://imgur.com/4BDDmv4.png)

Without this information, users could construe that they need to pick individual rom files from within those directories, and copy said files into the `roms` directory Path in amiberry (making that directory very messy and a pita to navigate through), when in actuality they can just extract the .zip archive directly into their roms path ...ie;

```
$path_to/roms
$path_to/roms/accelerator
$path_to/roms/cartridge
$path_to/roms/harddrive
$path_to/roms//misc
$path_to/roms/x86

```
....yes, I did this, before noticing the scan directory lines  =)

TIA

**Comment by midwan** [comment]
I've updated the Wiki, the screenshots will be recreated once we're ready for the next release.

**Comment by giantclambake** [comment]
Thanks .... I'll leave this open as gentle reminder to update the screenshots  ;)

**Comment by midwan** [comment]
Screenshot updated
