### ISSUE TITLE
[Docs] ~ add debug build info to wiki/Compile-from-source ?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1512]
...'just because' I had to go looking for this myself, I figure it'd be useful to explain how to create a debug build.... for a number of reasons (least of which being having to explain it repeatedly in tickets, when that introspection of process is required)...

....of course, it's as simple as  `-DCMAKE_BUILD_TYPE=Debug`  ...added to the configure stage...

cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug && cmake --build build

...worth it?

TIA

**Comment by solskogen** [comment]
Fixed.
