### ISSUE TITLE
Excessive calls to SDL_QueueAudio when using AHI

### ISSUE THREAD

**Issue by spectrumero** [BlitterStudio/amiberry#1513]
When using AHI with the Amiga's AHI preferences set to use UAE, memory usage very rapidly grows (about 2MB/second) while the audio device is playing (perhaps when the audio device is open).

**To Reproduce**
AHI must be installed.
uae.audio must be present.
AHI preferences must be set to use UAE (UAE 16 bit HiFi stereo)

Run a program that uses AHI, e.g. AmigaAmp, and start playing sound.

After a while, the OOM killer will kill Amiberry (depending on how much RAM is present on the host system) as memory usage inexorably increases at roughly 2MB/second while sound is playing through the UAE AHI driver.

Counting calls to SDL_QueueAudio in `src/osdep/ahi_v1.cpp` (line159) shows around 2MB worth of queueing happening every second (the expected rate for 16 bit stereo at 44.1kHz would be ~170k per second).

This has been observed both on amd64 (Debian), built from source  (on tag v5.7.4) and on 32-bit ARM.

It is also seen on the binary build of Amiberry for MacOS aarch64 version 5.7.4.

**Comment by giantclambake** [comment]
Hi, thanks for the report! Firstly, just a bit of friendly FYI...

*Ideally this should have been reported in the Amiberry-Lite repo (as we've talking about amiberry v5.7.4 ;) ... https://github.com/BlitterStudio/amiberry-lite/issues

*You should be using Amiberry (v6.x or current github `master`) on amd64/macOS

That said, I tested the scenario on this Ryzen-5600/16GB rig, running debian Bookworm and using amiberry `master`.

The description "_start playing sound_" is a little vague to me ~ I chose a [48minute .mp3](https://mega.nz/file/WFYwkBTY#7AVMnfFvRUOkuUuWt-NWDalXvCMvMSDZl7rWwFYiUK4) file for the test. I figured if anything was going to exhaust the host system ram resources, a big long .mp3 decrunch/replay is likely a good place to start ;)

The Amiga environment used, was a ClassicWB-P96 install (wb3.1 glue) ~ it has AHI & AmigaAmp installed & configured by default -- I double checked the criteria mentioned was set ...ie; AHI preferences set to use UAE (UAE 16 bit HiFi stereo).

At first start of the emulation, the process slices off ~200mb RES with total ram utilization of roughly 1.5% -- starting AmigaAmp and looking at the footprint...

![x](https://imgur.com/ID0nu0G.png)

...load the test .mp3 file, and start play in AmigaAmp ~ the ram utilization grows ; at the 34minute mark during replay...

![ex](https://imgur.com/JwwD3aW.png)

...at about the 42nd minute, the stack stops growing, and plateaus at the level below (I'm not sure why...mpeg decode finished?)....and the test .mp3 file plays out to it's completion...

![ex2](https://imgur.com/SYvDigP.png)

Note: quitting AmigaAmp at this point, does **_not_** release the ram stack ; you need to `Reset` the emulation to achieve that (suggests to me it's not AmigaAmp's doing?)...

Although it doesn't look entirely sane, I couldn't recreate any crash or out of memory cries... perhaps 16GB on amd64 is too much 'comfy chair' to recreate this .... or .... this is something intrinsic to Amiberry-Lite?...

@spectrumero  -- how much ram, in the amd64 case, did the host machine have that hoisted the OOM error? Also, do you experience the same problem/s on amd64 (Debian) and/or macOS using Amiberry preview-v6.3.5? (which is what you should be using for those platforms 8)  There's obviously something wrong here....I'm merely trying to recreate what you describe ... (or are you referring to the guest Amiga side throwing an OOM error?)...

**Comment by spectrumero** [comment]
Note: I can stop the audio queue growing without bound when using AHI and the UAE driver by adding: 

`if(queuedAudioSize > 65536) return;`

to line 119 of `src/osdep/ahi_v1.cpp`, but I don't have the knowledge of Amiberry/UAE internals or Amiga device driver internals to know if this is the correct way of going about fixing this.

**Comment by midwan** [comment]
@spectrumero 
Thanks for reporting the details on this.
Generally, I think the AHI implementation is currently broken on Amiberry using SDL2. I've tried to make it as close as possible to the original (WinUAE), but due to the differences in the back-ends (SDL2 in Amiberry vs Windows-specific options in WinUAE), there are inevitably differences.

It's of course possible I've done something wrong in the implementation as well.

I'll flag this as a bug case, and keep it for working on this further.

**Comment by giantclambake** [comment]
Just tested this, and it seems fine --- coincidentally, it also fixed the playback progress bar in AmigaAmp itself (previously not working correctly, and not reflecting the full playtime of the loaded .mp3 file)....so that's a win - win  ;)
