### ISSUE TITLE
Capitalization of 'amiberry' wrt linux build ~ not applicable

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1514]
I imagine this is spawn of changes in https://github.com/BlitterStudio/amiberry/commit/97a7021c7b272446bde66503b83b6e016cc7a96a

*resultant binary is named **Amiberry**  (not **_a_**miberry)

*as linux is case sensitive, this can/may result in   /usr/bin/amiberry & /usr/bin/Amiberry co-existing

*in that case, launcher links & mime-type call the old (lower case) binary, or else fails because the new binary has a capital 'A'

This breaks stuff ...the linux binary should be named **amiberry**  (lower case ;^) 

TIA

**Comment by midwan** [comment]
Thanks for finding this - I missed it during the macOS tests.
Definitely unintended. :)
