### ISSUE TITLE
preview-v7.0.0-RC1 does not run ~ debian Bookworm / amd64

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1518]
After downloading and installing amiberry_7.0.0_amd64.deb, amiberry does not launch ;

```
gcb@gallah:~$ amiberry
amiberry: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by amiberry)
amiberry: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by amiberry)
```

...obviously something needs tuning  ;)

TIA

**Comment by solskogen** [comment]
On what OS and version?

**Comment by giantclambake** [comment]
gcb@gallah:$ cat /etc/debian_version
12.8

amd64

**Comment by midwan** [comment]
Please disregard the RC pre-release created earlier. The artifacts are incorrect there. Working on fixing that.
