### ISSUE TITLE
Picasso II(+) wrong colors and missing/garbage mouse pointer

### ISSUE THREAD

**Issue by MASHtm** [BlitterStudio/amiberry#1519]
**Describe the bug**
I use original copies of A2000 discs from an A2000 with GVP 68030/882 and Picasso II board which I successfully use on FS-UAE.
I configured amiberry to use full ECS, same CPU with or without JIT and Picasso II(+) with 2 or 4MB VMem. I used a kickstart 3.1 ROM for A2000 and WB 3.1.
The workbench uses 1024x768/256 colors (8bit chunky) and 2 of the 8 workbench colors are wrong. color 4 and 8 to be precise (counting from 1 up).

The behaviour didn't change if I used a AGA A4000 with kickstart 3.1/A4000 and 68040/iFPU for emulation.

I tried to take screenshots with all colors visible on both EMUs. At least colors 5 and 12 are wrong as well used by the module player which allocates and sets custom colors for 5-12. The full palette window is from "Iconian".

Screenshot of FS-UAE (looking as original A2000)
![FSUAE](https://github.com/user-attachments/assets/6385b985-cbfa-4b1f-8a64-a9c5bed2eeab)
Screenshot of amiberry
![amiberry](https://github.com/user-attachments/assets/f86190aa-1adb-4661-8e71-a015428ce734)

The amiberry screenshot also shows the mouse pointer in wrong colors. This is the state if I used 2MB VMem. If I use 4MB the mouse pointer gets either garbage or invisible at all.

**To Reproduce**
Hard to predict. Most likely using a "close to A2000" config with 68030/882 and Picasso II.

**Expected behavior**
Correct colors and mouse pointer

**Desktop (please complete the following information):**

- OS:  Fedora 41 Mate on AMD 5600/Nvidia 4060 Ti

- Version 7.0.0-RC1 (git master of today, locally built from source to RPM)

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by midwan** [comment]
I think this is an issue in Amiberry due to the difference in the color space used. Amiberry uses RGBA, but WinUAE (and FS-UAE) use BGRA.

The reason for the change in Amiberry was increased performance, according to the benchmarks I used. Mostly noticeable on slower platforms of course.

Flagging this as a bug to be fixed, in any case. Thanks for reporting it!
