### ISSUE TITLE
Aspect Ratio's other than 16:9 / 4:3

### ISSUE THREAD

**Issue by DisasterIncarnate** [BlitterStudio/amiberry#1523]
Version used: Current V7 AmiBerry.
System Used: Arch Linux based LCD and OLED Steam Decks which have a native 16:10 1280x800 display.

**Describe the Bug / Feature?**

When selecting a FullScreen resolution in display settings only 16:9 and 4:3 aspect ratios seem to be available to me to use on a system such as a Steam Deck which can use those but prefers its native 16:10 resolutions so as to use every bit of screen real-estate on its internal display.

Can 16:10 resolutions be added as a useable option to match WinUAE?, i notice that even if i use the Full-Window option then AmiBerry will still Full-Window to a 16:9 aspect ratio/resolution of 1280x720 instead of the Steam Decks full 1280x800.

In the emulated environment we can pick 16:10 aspect ratio screenmodes for RTG using Picasso96 / UAEGFX modes but they size/scale to the 16:9 size/resolution that AmiBerry is enforcing so vertical screen space is still missing/wasted.

The F12/GUI does scale/fill a 16:10 display, just not the emulated environment, that always defaults to 16:9 for fullscreen, window & full-window modes.

**Comment by DisasterIncarnate** [comment]
Extra note: Using Full-Window PAL/NTSC native modes seem to be using the full 16:10 but RTG screens are defaulting to 16:9.

**Comment by midwan** [comment]
Amiberry will retain the original aspect ratio of the requested resolution, by default. This can be overridden if you disable the relevant option, found in the Display panel.

There is no hardcoded aspect ratio otherwise.
Also, it's usually preferable to use Full-window mode, instead of Fullscreen (which will force a change of resolution to the one selected).

**Comment by DisasterIncarnate** [comment]
yeah i'm using Full-Window now and native pal/ntsc screens are filling screen height but once an RTG/P96 screen appears the vertical height isnt all being used, no idea why.

**Comment by DisasterIncarnate** [comment]
if you look at this: https://www.youtube.com/watch?v=u65TyWYuZIM you will see native screens are using full vertical height while the workbench rtg screen is not using it all, it seems to have a 16:9 aspect ratio enforced and wont use 16:10, when i check the RTG Board option / UAE Zorro III, it has an aspect ratio option but the selection is greyed out, i now assume this is my issue?

Here is a snap of my RTG Board options: https://i.imgur.com/bPb8lqh.jpeg this i assume is why native screens are using 16:10 in full-window as i can disable "correct aspect ratio" on Display options but i cant seem to do the same for RTG GFX, this is likely why i see the jump back and forth in vertical height when i see my workbench screen and run a game or program that uses native screens.

**Comment by midwan** [comment]
Currently, the `Correct Aspect Ratio` option only affects native modes, not RTG ones (which will always keep the aspect ratio). This can be changed in a future update, of course.

What resolution are you using on RTG? It should list all the detected available resolutions there, so you should be able to pick one with a 16:10 aspect ratio, which should then fill the screen.

**Comment by DisasterIncarnate** [comment]
I have tried that, it doesnt matter what RTG screen mode i end up using they all seem to get squashed/resized into a 16:9 resolution.

**Comment by DisasterIncarnate** [comment]
no 16:10 screenmodes are listed as choices in the workbench screenmode list, only 16:9 and 4:3.

**Comment by DisasterIncarnate** [comment]
This is the script i currently use to give me a smaller, more readable Workbench Display that is easier to read on the Steam Deck 16:10 internal display and a near matching resolution for my 16:9 TV.

```
#!/bin/bash
cd /home/deck/Downloads/AmiBerry/

# Smaller 16:10 Resolution for Internal Display, Better Visibility/Readability
# Steam Deck uses a rotated 800x1280 display, AmiBerry cant seem to see or use
# a custom 1024x640 on the Deck unless a matching rotated 640x1024 display exists.

xrandr --newmode "640x1024"   54.00  640 680 744 848  1024 1027 1037 1063 -hsync +vsync
xrandr --addmode eDP 640x1024
xrandr --newmode "1024x640"   52.25  1024 1072 1168 1312  640 643 649 665 -hsync +vsync
xrandr --addmode eDP 1024x640

# Smaller 16:9 Resolution for TV, Better Visibility/Readability.
xrandr --newmode "1024x576_60.00"   46.50  1024 1064 1160 1296  576 579 584 599 -hsync +vsync
xrandr --addmode DisplayPort-0 1024x576_60.00

LD_LIBRARY_PATH=./lib ./amiberry /home/deck/Amiberry/conf/OS32-Default.uae
```

**Comment by DisasterIncarnate** [comment]
found suitable fix.

**Comment by midwan** [comment]
Re-opening, because I would like to get to the bottom of this.
I'll be testing it on a SteamDeck to see if I can recreate what you described.

**Comment by midwan** [comment]
I can set the Workbench resolution to 1280x800, and it fills the screen entirely on the SteamDeck's display. I don't see any scaling issues at all there.

Still using the previous flatpak version for this test, as it's the one I had installed already. But besides the integer scaling options, nothing in this area changed in v7 I believe.

**Comment by DisasterIncarnate** [comment]
very strange then, without what i did above i could only see/use up to 1280x720 on workbench, this is from my OLED deck, the SSD i transplanted from my LCD as i got a 2tb device early on, i might try and wipe my LCD deck from fresh and see if a clean/new system behaves the same way, it might just be some rando issue on my OLED deck i havent noticed till now.

A quick check i did earlier btw shows that i do see the 1280x800 screenmode available IF i run AmiBerry from the steam deck's desktop mode, when i have it added as a non-steam game and launch in game-mode, this seems to be where 1280x800 vanishes and i can only see/use 1280x720, again i think i will try wiping my LCD deck, start from fresh and see if it works properly in desktop mode and game-mode.

It could just be some random leftover issue/problem from my 2TB SSD, its a clone of my LCD's original 512GB SSD, which i cloned to a 1TB drive in early 2023 and later i cloned that to a 2TB drive in late 2023, it hasnt been wiped/started from fresh, no idea, i will see what happens to a fresh LCD setup first.

**Comment by midwan** [comment]
@DisasterIncarnate 
Oh, maybe the difference is running it under Desktop mode then. I also run it from there, didn't test it under the Steam launcher.

Generally, Amiberry will show you the resolutions that SDL2 gets as available from the system, in the list of RTG modes. If Steam does something and only reports 720p instead of 1280x800, that would explain the behavior.

**Comment by DisasterIncarnate** [comment]
the custom screenmodes i made to test i also made under desktop mode, again when launched through game-mode my custom resolutions do not appear in gamemode but do in desktop mode, i am guessing the fact that gamemode does not run the desktop x/window/wayland system and instead uses valves gamescope system might have something to do with that.

Cant remember right now but i do remember a command line launch argument where you can run something as if it was launched via desktop/x/wayland, i need to remember / find the discord post that explained how to do that and see if that works.
