### ISSUE TITLE
Direct-loading of savestate (*.uss) files not working as expected.

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1525]
Best I can figure it, we're just missing the `-G` switch (when you think about it, loading to GUI makes no sense here ;)

Example;

`amiberry /home/gcb/.local/share/amiberry/savestates/dpaint-2.uss`  //pops GUI, does not `Start`

`amiberry /home/gcb/.local/share/amiberry/savestates/dpaint-2.uss -G` //loads .uss file and boots emulation to saved state

TIA

**Comment by midwan** [comment]
Ah, correct - I didn't think about that part.
Should be an easy fix, will get on it.

**Comment by midwan** [comment]
Should be fixed in the latest commit
