### ISSUE TITLE
Portable Mode - Dummy File (amiberry.portable) to indicate defaulting to local folder structure/relative paths 

### ISSUE THREAD

**Issue by RodimusFVC** [BlitterStudio/amiberry#1527]
Per our discussion in Discord -

Having a flag file to cause a defaulting of behavior to a full portable mode without the need for environment variables, creation of additional paths/confs in the home folder, etc.

If this means moving the amiberry.conf file out of the /data folder and under the binary, that's fine too.  As long as I can drop the folder anywhere and click and go - this is a satisfied requirement.

**Comment by giantclambake** [comment]
I actually touched on this in an [EAB post](https://eab.abime.net/showpost.php?p=1717904&postcount=18)  ; I saw it as a compile time aspect .... I'm unsure as to what the 'proper' resolution is here  ;)

**Comment by midwan** [comment]
@RodimusFVC 
I've created a new branch with a possible fix, along the lines of what we discussed.
Can you give it a try and see if that works as expected for you?

**Comment by RodimusFVC** [comment]
> @RodimusFVC I've created a new branch with a possible fix, along the lines of what we discussed. Can you give it a try and see if that works as expected for you?

Sure, I'll give it a quick compile and test on my main machine today.

**Comment by midwan** [comment]
I've updated the branch, with logic to create the `conf` dir if it doesn't exist. This should only apply in portable mode, as in other cases we make sure that it exists anyway.

Regarding relative paths: not such a simple change, as much of the code related to that comes from WinUAE, and I'm trying to keep things in-sync between the two projects, so merges can be easier. I think we'll leave that for later.

**Comment by RodimusFVC** [comment]
> I've updated the branch, with logic to create the `conf` dir if it doesn't exist. This should only apply in portable mode, as in other cases we make sure that it exists anyway.
> 
> Regarding relative paths: not such a simple change, as much of the code related to that comes from WinUAE, and I'm trying to keep things in-sync between the two projects, so merges can be easier. I think we'll leave that for later.

Fair enough.  I've always wondered why WinUAE did that, considering it also supports portable installations.  I had to manually edit the configs every time... so I'm used to doing it.  I'll close this out!  :)  Thanks midwan!

**Comment by midwan** [comment]
Wiki updated accordingly also: https://github.com/BlitterStudio/amiberry/wiki/Amiberry-directories
