### ISSUE TITLE
[Doc] Update amiberry manpage

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1530]
Just updating this manpage, to keep it aligned with amiberry changes/enhancements, on the incline to the v7.0 release.

*added env_variable descriptions
*added a couple of examples
*added reference to cmdline invocation enhancements
*added reference to `amberry.portable` file

As always, please read/review ;)

TIA

[amiberry.1.gz](https://github.com/user-attachments/files/18107009/amiberry.1.gz)

**Comment by midwan** [comment]
Thanks.
There were a few minor typos which I fixed, otherwise looks good.
