### ISSUE TITLE
GUI not refreshing correctly ~ Quickstart <-> CPU & FPU panels

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1535]
Pursuant of discussion #1534 it was made known to me that _JIT is not related to PPC in any way_, and as such I had to backtrack the reason this (erroneous) notion had entered my head... now I see why.. ;) 

To recreate:

Launch amiberry, 

GUI -> Quickstart -> Amiga model: A4000, config: CyberStormPPC --> CPU & FPU  //take note of CPU & JIT widgets// ---> Quit

....and everything appears as expected. However....

Launch amiberry,

GUI -> Quickstart ->  "_by mistake_" select Amiga model: A3000 --> "_realize mistake and change to_"  Amiga model: A4000, config: CyberStormPPC ---> goto CPU & FPU panel ---->> **JIT is enabled and checkbox 'locked'** 

AFAICT, only selecting Amiga model: A3000 and then changing to A4000 will manifest this error.

Expected: JIT checkbox should always be available to disable/enable when A4000/CyberStormPPC is selected.

TIA

**Comment by midwan** [comment]
This is an upstream bug, as WinUAE does exactly the same thing. :)
I can fix it in Amiberry in any case.
