### ISSUE TITLE
[Doc] Query: GUI -> Sound panel --> Automatic switching ...not described in helptext?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1537]
Likewise is so for wiki/GUI:-Sound ...the `Automatic switching` option is undocumented...

...not even I know what it does....nor have I tested it, as the expected behavior/function/purpose is unknown to me...

Can you fill in the blanks please? 8)

TIA

**Comment by midwan** [comment]
WinUAE "documents" this as:
`Automatic switching allows switching between sound modes automatically.`

I haven't looked into the details of what exactly it does. :)

**Comment by giantclambake** [comment]
You found more than I did ;) .....hmm, the key will be understanding the participle noun... "sound modes" ....what exactly is a `sound mode` in the UAE context?... bigbox Amiga switching between Paula audio and CDDA or something?... I'll remained confused at this point  =)

**Comment by midwan** [comment]
My understanding is, that it's referring to the modes available in the radio buttons there:
- Sound Disabled
- Disabled but emulated
- Enabled

From what I can see in the code, it enables the audio if there are samples to be played, then disables it when the buffer is empty.
