### ISSUE TITLE
From where to get the qemu.plugin for macOS ARM

### ISSUE THREAD

**Issue by nexusle** [BlitterStudio/amiberry#1538]
Hey,

from where I can get the qemu plugin to use AmiBerry with PPC support under macOS ARM?

I tried yesterday with the FS-UAE plugin package, but without success.

**Comment by giantclambake** [comment]
Hi,

See https://github.com/BlitterStudio/amiberry/discussions/1534

**Comment by midwan** [comment]
Plugins currently don't work on MacOS, I'm hoping to find a fix for that soon.
