### ISSUE TITLE
Query: config.uae handling wrt whdload.lha loading ... is this sane?

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1539]
...doing some doc updates, and checking as I go, I stumbled across this curio ...which sort of makes sense to me, however, I question the interaction here....ie; it seems entirely possible to accidentally/innocently 'break' a good/working config.uae file, that's associated with a whdload.lha file, under the following conditions...

...I believe it holds true for any whdload.lha file, but for reference the test file used is -->  http://ftp2.grandis.nu/turran/FTP/Retroplay%20WHDLoad%20Packs/Commodore_Amiga_-_WHDLoad_-_Games/A/AceBall_v1.0_Pl_AGA.lha

To recreate;

`amiberry AceBall_v1.0_Pl_AGA.lha`   //direct-loads the whdload.lha file, uses the XML, wait for game to load...

F12 -> Display panel --> change to Manual crop, set H_offset to +30 (I need to do this here to center display for this title)
Goto Configurations panel --> Save (the file `AceBall_v1.0_Pl_AGA.uae` is created) ---> Quit amiberry

Test if `AceBall_v1.0_Pl_AGA.uae` applies;

`amiberry AceBall_v1.0_Pl_AGA.lha`   //direct-loads the whdload.lha file, uses the associated config.uae file as expected
F12 ---> Quit amiberry

User decides they would rather have this title start in Full-window mode, rather than Windowed mode - they do the following;

Launch amiberry, GUI -> Configurations panel --> Select & Load `AceBall_v1.0_Pl_AGA.uae`
Goto Display panel -> change Screen mode: to Full-window --> Configurations panel --> Save ---> Quit amiberry

Retest if `AceBall_v1.0_Pl_AGA.uae` applies;

`amiberry AceBall_v1.0_Pl_AGA.lha`   //direct-loads the whdload.lha file, but title now fails to start ;(

Note: What the user should have done here, is start the emulation with `amiberry AceBall_v1.0_Pl_AGA.lha`, at which time the original `AceBall_v1.0_Pl_AGA.uae` file would've been used, and then do the F12 -> Display panel -> change Screen mode: to Full-window --> Configurations panel --> Save sequence, _while the loaded emulation is started and running_.

All things considered, I'm not sure if this is a bug, or an undocumented caveat wrt working with config.uae files associated with whdload.lha archives.... what say you?

TIA

**Comment by midwan** [comment]
This seems like a bug.
The `whdload_slave` option does not get saved, when you follow the approach you mentioned.

**Comment by giantclambake** [comment]
I didn't check the actual failure, but that tallies with the results here...

**Comment by midwan** [comment]
This is fixed, by saving more of the whdload_prefs to the config file, including the actual `.lha` filename.
You don't get some of the info contained in the XML, which is read only when using the WHDBooter mechanism (not when loading a config file), but most of it will show there now, and it will work as expected.

**Comment by giantclambake** [comment]
I just tested this, and I believe the rationale is sound...ie; if you load/edit a (pre-existing) config.uae file, in effect you're editing the emulator setup .... not the handling of the whdload.lha file itself perse (which ideally should be done first, at the time the associated config.uae file is created). I've got a place-holder in the docs I'm redoing, where I can include some additional information regarding these operations...

...thanks, all good =)
