### ISSUE TITLE
Bigger fonts bug

### ISSUE THREAD

**Issue by OSH1980** [BlitterStudio/amiberry#1542]
**Describe the bug**
Setting bigger font for Default theme causes, some textes (for example font size number) disappears. Resizing the window helps not. 

**To Reproduce**

Set font size for theme on 25.

**Expected behavior**

Normal text showing. 

**Screenshots**
![Bildschirmfoto vom 2024-12-20 11-21-07](https://github.com/user-attachments/assets/eae1b9e9-2aa8-49fe-b41e-cea2b31b24b7)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version  22.04

**Additional context**

**Comment by midwan** [comment]
That's a known issue, I'm afraid.
And it's not possible to fix, with the current GUI library (guisan). It doesn't support dynamic GUI sizes, everything has to be calculated beforehand. Resizing the window will not change the GUI, only the surface it's drawn on.

This could only be improved with replacing the GUI library with something more modern, like Qt. However, that will make it much heavier as well, and add an extra dependency. Not sure how well that works in console-only situations either.
