### ISSUE TITLE
GUI -> WHDLoad panel --> Custom fields .... alignment/width of dropdown item selectors wrong [cosmetic]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1543]
Very much depends on the makeup of the whdload.lha file that is loaded.

Example file: http://ftp2.grandis.nu/turran/FTP/Retroplay%20WHDLoad%20Packs/Commodore_Amiga_-_WHDLoad_-_Games/G/GhostsNGoblins_v1.4.lha

This would be an oddball case, where not all of the whdload splash-screen is visible, and the `Custom fields` window in the amiberry WHDLoad makes that obvious...

...having said that, and as can be seen below, the width (read: left justification) of the dropdown menu items, obscures some of the descriptive text, that the setting is related to... 

![ex](https://imgur.com/tJuVxCP.png)

I am not sure if this is the worse case scenario, but either way the dropdown selectors are, in practice, perhaps too wide, and should be better justified towards the right, to help avoid the above happening.

Note: I can see other possible strife here, wrt to the checkbox widgets as well...ie;

![ex2](https://imgur.com/0GztlIO.png)

...apart from the fact I feel the checkboxes look a bit 'goofy' being so far away from the **Custom1:** text anyhow, that particular line was right on the limit of char_space ... I can't help but feel, the checkbox widgets should be justified further to the left here, to help avoid the possibility of long option descriptions being a problem... 

Can this be improved?

TIA

**Comment by midwan** [comment]
This should be better:

<img width="602" alt="Screenshot 2024-12-20 at 14 43 23" src="https://github.com/user-attachments/assets/ad30b21a-d568-4219-8b0a-95d74a189424" />

The question is: are dropdowns _always_ like this, meaning the appear before the label, in WHDLoad? I haven't checked.

**Comment by giantclambake** [comment]
Good question .... if you grep the XML for` L:`  you gets some idea.... the answer is likely no, but at the same time, in many cases it doesn't matter either.... rock&a tight spot...

**Comment by HoraceAndTheSpider** [comment]
When defining a set of splash-options, the programmer cannot choose to make it "before" or "after"

The choice to make it first, must come from WHDLoad itself, so if that is how it is displayed in the native environment, that's the way it always is.
