### ISSUE TITLE
GUI refresh issues after PR #1547 [cosmetic only]

### ISSUE THREAD

**Issue by giantclambake** [BlitterStudio/amiberry#1549]
Just checking through the latest changes wrt savestates, and noticed the following..

To recreate;

Examine current savestate path  (here, this is `savestate_dir=/home/gcb/Desktop` )

```
gcb@gallah:~$ ls ~/Desktop/*.uss
 '/home/gcb/Desktop/Stunt Car Racer (1989)(Micro Style).uss'
```

The savestate file is associated with "Stunt Car Racer (1989)(Micro Style).adf" (floppy image)

Test:

Launch amiberry, GUI -> Quickstart --> load "Stunt Car Racer (1989)(Micro Style).adf" into DF0:
Goto Savestates panel... and see the associated .uss file is **not** displayed....

![ex](https://imgur.com/wbF2MgY.png)

Click on Slot 1 .....

![ex1](https://imgur.com/YkNvDMT.png)

Now click back to Slot 0 ....

![ex2](https://imgur.com/4HfmPvX.png)

The panel has refreshed, and correctly displays the savestate entry.

Expected: the associated .uss file should be displayed in the savestates panel immediately after loading the associated file.

Quit amiberry....

I'm guessing some folks will use savestate files in this fashion, via the GUI ...and in that case, I almost wonder if the Savestates panel itself, should have a 'Resume State' button to launch the .uss file from there?

In any event, I believe it should behave as Expected:   ;)

TIA

**Comment by midwan** [comment]
It wasn't refreshing the Savestate panel, so it didn't get updated with the inserted floppy name.
It should be fixed now, both from Quickstart and the Floppy panel.
