### ISSUE TITLE
Fullscreen always opens a 800x600 screen

### ISSUE THREAD

**Issue by AndyFx12** [BlitterStudio/amiberry#1556]
Fullscreen-mode opens 800x600 screen on my system - even if different resolutions are selected.

**To Reproduce**

1. select Fullscreen at display-settings

2. select 1920x1080 resolution

3. start a game

4. screen resolution is only 800x600

**Expected behavior**
Resolution should respect settings ...

**Desktop (please complete the following information):**

- OS: Linux Mint 
- Version 22
- nvidia driver 535
- lenovo screen, which is Full-HD and supports 50/60 Hz.

Tested with amiberry 7.0.0rc2

regards, Andy

**Comment by midwan** [comment]
The full-screen option always uses the resolution you specify in the dropdown next to it.
Perhaps it's best to use Full-window instead, which will use your current resolution, and scale everything accordingly to that?

Full-screen has caused many issues in the past, and I'm seriously considering removing that option altogether, as it's not very useful in the current state.

**Comment by AndyFx12** [comment]
Hi midwan,

I've tried fullscreen-mode because of some (rare) micro-judder at 50 Hz on some games (e. g. Turrican II, which has perfect smooth scrolling on native machines). It looks like a missing frame. 
Maybe V-Sync-native setting on full-window-mode could help?

**Comment by AndyFx12** [comment]
Thanks for your support!

**Comment by midwan** [comment]
Yes, the VSync options should help with that, as you discovered. The Lagless options are not yet implemented :)
