### ISSUE TITLE
Kickstart ROM OS3.1 won't be recognized

### ISSUE THREAD

**Issue by AndyFx12** [BlitterStudio/amiberry#1561]
**Describe the bug**
KS OS3.1, 40.10 (15.7.93) won't be recognized in drop-down-list after path-scanning.
Manually selected, it works fine, though.
MD5-Hash: 7bd3bdf82dfe0028c2a9aa177d48f8d0
SHA1-Hash: 6071d0b21edbafd14c890698e8a47abaab5e33d1

KS1.3 and KS2.0 work fine, though.

**Desktop (please complete the following information):**

- OS: Linux Mint 22 Cinnamon

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by giantclambake** [comment]
The kickstart files are identified by crc32 (not md5 / sha1 hashes)

I say that, because I wonder what kickstart rom you're referring to here?.... ie; the earliest (beta) KS3.1 image I know of, was version 40.30 ....and the earliest release version was 40.55

To be included in the rommgr code, it should be a certified _release_ Amiga rom ~ I cannot verify KS OS3.1, 40.10 (15.7.93) ever existed?

**Comment by AndyFx12** [comment]
My Hexeditor shows 
AMIGA ROM Operating System and Libraries.Copyright © 1985-1993 .Commodore-Amiga, Inc. .All Rights Reserved..3.1 ROM .exec.library.exec 40.10 (15.7.93).
A friend said, he had "transromed" them from an AMIGA 1200 - so I'll transrom my original machine myself ...
CRC32 = ef557783

**Comment by giantclambake** [comment]
Thanks ~ `ef557783` is not tabled in the rommgr code, nor is it listed as a [supported kickstart](https://github.com/BlitterStudio/amiberry/wiki/Kickstart-ROMs-(BIOS)) in the amiberry wiki.

I'm not sure what happened during said "transrom" process, but obviously it changed something...ie; I don't know of any A1200 released with 40.10

You could still use that rom image (supposing it works), but it won't be auto-detected - you'd have to save the selection to a config.uae file.

As always, wait to see what midwan has to say about this  ;)

**Comment by midwan** [comment]
That's normal behavior. 
Only a predefined list of "known" ROM files will be shown in the dropdown if detected. Anything else can be selected manually.

**Comment by AndyFx12** [comment]
After some "retro-time" with old floppies and a fully working A1200 (!), I have a ROM which CRC32-.hash is listed at your good-known-list. 
Now it is listed at amiberry drop-down-list, too.

But *strange* - header shows same "40.10" at .rom-file ... (Workbench shows Kickstart 40.68, though).
