### ISSUE TITLE
MegaBall AGA WHDLoad hangs just after starting

### ISSUE THREAD

**Issue by DLehenbauer** [BlitterStudio/amiberry#639]
When launching 'MegaBall_v1.02_AGA.lha' via RetroPi on an RPi3B+, I hear about half a second of the intro sound, then get silence and a black screen.  The emulated Amiga seems frozen, but AmiBerry is responsive (I can use F12 to open settings.)

I verified that the same .lha works on a WB3.1 installation an a PC with WinUAE.

The non-AGA version 'MegaBall_v1.02_1MB.lha' has no problems on AmiBerry. 

Let me know if there's any additional info you'd like me to collect.  Thanks!

**Comment by Retro1968** [comment]
Raspberry Pi 4 with RetroPie 4.6.

I can confirm that problem. Running the lha-file directly from the RetroPie Menue results in black screen. Do i start Mega Ball AGA decrompressed on AmigaOS 3.1.4.1 it works fine.

**Comment by midwan** [comment]
This seems to work in the latest version from `master`
