### ISSUE TITLE
Loading a Savestate crashes amiberry

### ISSUE THREAD

**Issue by Retro1968** [BlitterStudio/amiberry#915]
Raspberry Pi 4 with Manjaro Linux. Running AmigaOS 3.2.1 and WHDLoad Programs.

I have the following problem in amiberry 4.16 and amiberry 5.0.
I start the AmigaOS 3.2.1 workbench. Load a WHDLoad Game from there. Go to the menu with F12 and successfully save a savestate.

If I want to load this save state again, amiberry crashes completely and I'm back on the Manjaro desktop. 

Cheers
Retro1968

**Comment by midwan** [comment]
What config did you have when you saved the savestate?
Some things like JIT are not guaranteed to work with Savestates (in fact, they are not officially supported), so it depends a lot on the emulator settings you had enabled.

Savestates normally are meant for floppy images only, but I've extended that to allow limited support for HDDs also, so we can use them with the whdbooter feature of Amiberry. But on a full-blown WB with JIT, RTG and so on, there may be problems.

One workaround for that would be to dynamically disable JIT when launching a game, and re-enabling it when it quits. You could use the WinUAE-bundled Amiga tool `uae-configuration` for something like that, by triggering it from WHDLoad's startup and shutdown scripts...

**Comment by Retro1968** [comment]
I save a savestate after AmigaOS 3.2.1 has been loaded from a HDD file and I run from here a WHDLoad game. In the game I now switch to the menu and save a save state. I was then shown a decent screenshot of the game after the save process was successful.

If I now load this savestate, amiberry crashes. This also happens when I load the savestate after a reboot.

JIT is enabled when I load AmigaOS 3.2.1. It is automatically deactivated when I start a WHDLoad game and is reactivated after the game is closed.

**Comment by midwan** [comment]
When you're trying to load the Savestate, is JIT enabled?
Can you try disabling it and see if that makes a difference?

**Comment by Retro1968** [comment]
Raspberry Pi 4 running RetroPie 4.8 with amiberry (2022-04-15)(sdl2)

JIT has been disabled. AmigaOS 3.2.1 was loaded from HDF image. After that I started the game Waterloo (not via WHDLoad). After that I successfully saved a savestate, then did a reset. Amiberry crashed immediately after I tried to load the savestate.

**Comment by midwan** [comment]
@Retro1968 
So you had JIT enabled when you tried to load the savestate again, after the reset?
Did you try disabling JIT first?

**Comment by Retro1968** [comment]
I have now deactivated JIT in my default.uae profile. I also removed JIT settings in WHDLoad.pref.

Then I loaded my AmigaOS 3.2.1 Worbench, started the game "Waterloo" (no WHDLoad-Game), successfully saved a savestate and then left amiberry completely. After a reboot with Workbench 3.2.1 loaded, I loaded the savestate (a screenshot of Waterloo was shown on slot 0). Amiberry crashed immediately afterwards.

[default.zip](https://github.com/midwan/amiberry/files/8694842/default.zip)

**Comment by midwan** [comment]
@Retro1968 
Ok, then I guess the culprit wasn't JIT in this case.
How about RTG? Was that enabled during the process? Perhaps you can test without it, to see if it makes a difference?

**Comment by Retro1968** [comment]
> @Retro1968 Ok, then I guess the culprit wasn't JIT in this case. How about RTG? Was that enabled during the process? Perhaps you can test without it, to see if it makes a difference?

After I deactivated JIT as described above and also uninstalled the P96 v.3.3.0 driver, I repeated the above test with the NON-WHDLoad game "Waterloo". Here, too, amiberry crashes immediately after the save state has been loaded.

**Comment by midwan** [comment]
Closing this as its' been stale for many months now
