### ISSUE TITLE
[SDL2 2.0.10] Custom Panel cannot be navigated entirely from Controller/Pad 

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [BlitterStudio/amiberry#980]
**Describe the bug**

**To Reproduce**
Navigate around the panel with a controller.

Left X / Left Y (analogue stick axis?) is navigated onto with a controller in the wrong order, and some controls cannot be reached at all

**Expected behavior**
Logical navigation order.

This is likely a result of the dynamic creation of the menu.

**Comment by midwan** [comment]
This must be an issue with older SDL2 versions only, as the navigation works fine with newer ones (those that have more buttons / axes available).
