### ISSUE TITLE
Mega Typhoon - Guru error warning after amiberry update

### ISSUE THREAD

**Issue by Retro1968** [BlitterStudio/amiberry#985]
Raspberry Pi 4 with RetroPie 4.8 using Amiberry 5.2 with AmigaOS 3.2.1

After installing amiberry 5.2 (2022-06-11) i get a guru message after i started the WHDLoad Game "Mega Typhoon" from my workbench 3.2.1. However, the game is playable after clicking away the guru message with the left mouse button.

I compiled with this command:
make -j4 PLATFORM=rpi4-sdl2

After I installed the precompiled binaries via the RetroPie setup, the guru message disappeared.

Cheers
Retro1968

P.S.: This error only occurs when I start Mega Typhoon from the workbench. If I start the lha file via the RetroPie menu, no error message appears.

**Comment by Retro1968** [comment]
"Cruise for a corpse" has the same problem.

**Comment by Retro1968** [comment]
Both tested with amiberry 5.3 [2022-06-22].

**Comment by midwan** [comment]
This issue is also occurring on the latest WinUAE, so it's something to do with the recent changes there, which were also merged in Amiberry.

Perhaps something with the CIA rewrite, I'm not sure. But it will be fixed as soon as Toni fixes it there also.

**Comment by Retro1968** [comment]
Have you already informed Toni about this or do you want that I do it?

**Comment by midwan** [comment]
Not yet - I wanted to test which exact commit of WinUAE started causing this, and I didn't have the time to go through all of them. On Amiberry's side, several of those were merged in one commit, so they are not the same historically.

**Comment by Retro1968** [comment]
> Not yet - I wanted to test which exact commit of WinUAE started causing this, and I didn't have the time to go through all of them. On Amiberry's side, several of those were merged in one commit, so they are not the same historically.

I want to give you a math hint on how to find the right WinUAE commit number with little effort:

Let's say there are 100 commit numbers that you need to check. 1 is the oldest and 100 is the newest number. The commit number we're looking for is 87... but we don't know that yet. ;-)

We always divide by 2. 100/2 = 50.
So we look at first the commit number 50. Here the error is not yet present. So we have to search in the remaining 50.
50/2 = 25.

We are now looking in commit number 75 (50+25).
The error is still not there. There are 25 commits left to examine.

25/2 = 12.5

We now examine commit number 87 (75+12)... hit.
Now let's check if commit number 86 already had an error, just to be sure. Since this is error-free, it must be 87.

So it only took me 4 attempts.

I hope to be able to explain the search principle clearly enough to you.

Cheers
Retro1968

**Comment by midwan** [comment]
@Retro1968 
Thanks, that's how `git bisect` works anyway (https://git-scm.com/docs/git-bisect) ;)

**Comment by Retro1968** [comment]
Wow... may I ask how you managed to fix the bug so quickly? Very good work, Dimitris!

 Thanks for the release of amiberry 5.3. :-)

**Comment by Retro1968** [comment]
Hello Dimitris,
thanks for the new amiberry version 5.4. :-)
With version 5.4 (2022-10-01) this guru error is back.

I compile on RetroPie with this option: make -j4 PLATFORM=rpi4-sdl2

Cheers
Retro1968

**Comment by midwan** [comment]
@Retro1968 
That's unfortunate, it means that probably even with the latest CIA rewrite fixes from WinUAE, there's still a bug there.
I think it's best we report this upstream to Toni as well, since he'll have to fix it in WinUAE also.

**Comment by Retro1968** [comment]
> Actually, after testing this on the latest WinUAE it doesn't happen there. So it must be a difference between Amiberry and the latest WinUAE, but it might be easier to roll-back the CIA rewrite instead of trying to find that.

At least in the short term this seems to be the best solution. In the long term, the bug in amiberry, which is still unknown, would always be continued. I don't think that's a good idea.

**Comment by midwan** [comment]
@Retro1968 
Just reverted the CIA rewrite on `master`, so this issue (among others) should be fixed now.

**Comment by Retro1968** [comment]
Thank you, the error is gone. I just tested it in amiberry v 5.5. May I ask for what solution you decided at least?
Did you roll-back the CIA rewrite or did you found the error?
