### ISSUE TITLE
Invertebrates by AttentionWhore

### ISSUE THREAD

**Issue by DesertBlizzard** [BlitterStudio/amiberry#993]
This demo: [Invertebrates by AttentionWhore](https://www.pouet.net/prod.php?which=75793) when ran in Amiberry 5.1 configured for an OCS 1Mb exact cycle A500 with Kickstart 1.3 will end up with a corrupted screen at the time when the demo tries to cut to the 4th scene.  While there are other problems with WinUAE (4.9.2) running this ADF demo, it does get through it without breaking badly like Amiberry does.
![Screenshot_2022-06-28_22-47-58](https://user-images.githubusercontent.com/45675403/176361112-38094c75-18e3-4cd5-a655-da24648296ef.png)

**Comment by midwan** [comment]
I cannot recreate this with the current version (5.3) or the latest `dev` (2022-08-15), when using a default A500 config (512KB Chip + 512KB Fast).
There are some minor gfx glitches in some objects during the course of the demo, but other than that it worked normally all the way to the end.
