### ISSUE TITLE
Latest dev will not compile

### ISSUE THREAD

**Issue by Lex15** [BlitterStudio/amiberry#994]
Latest dev will not build amiberry executable. Using up to date RpiOS(32bit).

**Comment by solskogen** [comment]
`src/custom.cpp: In function ‘void hsync_handler_post(bool)’:
src/custom.cpp:12586:45: error: ‘delayed_framestart’ was not declared in this scope
12586 |   event2_newevent_xx(-1, 2 * CYCLE_UNIT, 0, delayed_framestart);
      |                                             ^~~~~~~~~~~~~~~~~~
src/custom.cpp:12590:45: error: ‘delayed_copjmp’ was not declared in this scope
12590 |   event2_newevent_xx(-1, 2 * CYCLE_UNIT, 0, delayed_copjmp);
      |                                             ^~~~~~~~~~~~~~
distcc[3119] ERROR: compile src/custom.cpp on localhost failed
make: *** [<builtin>: src/custom.o] Error 1
`

This happens on aarch64 as well
