### ISSUE TITLE
CD drive not mounted after switching config

### ISSUE THREAD

**Issue by DJP75** [BlitterStudio/amiberry#996]
**Describe the bug**
After upgrading to 5.x i can't load .iso image into the emulator. Tried also a clean CD32 config but with no result.

**To Reproduce**
Mount any .iso image via the GUI and access it via workbench or boot via CD32 (if bootable)

**Expected behavior**
Access .iso CD images via workbench or boot on CD32 (if bootable)

- OS: dietpi 8.5 / 8.6

**Comment by solskogen** [comment]
Are you sure you have read access to the iso file? I've got no problems booting AmigaOS 3.2 from CD here.

**Comment by solskogen** [comment]
Hang on.. is this WSL?

**Comment by DJP75** [comment]
what is wsl? :) i use amiberry on dietpi and copy files in windows using paragona linux filesystem. adf and hardfiles works, isos not.

**Comment by DJP75** [comment]
Permissions are ok. They are identical to adf files and directories. I also tried opening them in ubuntu and they open fine. Tried to put a couple on an usb fat32 stick but no luck. At this point i will try a fresh install on another sd and report the results

**Comment by DJP75** [comment]
Tried a fresh installation of dietpi 8.6.1 (arm7) with amiberry 5.3 and cd32 quickstart. No iso detected

**Comment by midwan** [comment]
this specific behavior is the same in v4.x as well. It seems that a reset is not enough to fully update the hardware config in some scenarios

**Comment by midwan** [comment]
@DJP75 This is hopefully fixed with the commit above - but please test and let me know if anything misbehaves! :)

**Comment by DJP75** [comment]
I'll try,thanks!!!!

**Comment by DJP75** [comment]
It's working!! Thanks and sorry for the delay

**Comment by midwan** [comment]
Thanks for the confirmation!
