### ISSUE TITLE
Amiberry on Raspberry OS

### ISSUE THREAD

**Issue by KostasDaskalos** [BlitterStudio/amiberry#997]
Amiberry is treated as a shared library not an executable. Can not be started by double clicking.

**To Reproduce**
1) Install latest Raspberry Pi OS ( 2022-04-04-raspios-bullseye-armhf.img ) on Raspberry Pi 400 4GB
2) Install all dependencies as described in this repo.
3) Extract latest release ( 5.3 )
4) Double click on amiberry in the extraction folder.

![amiberry](https://user-images.githubusercontent.com/7622007/178809437-4afa5f39-cd08-4b5a-8aaa-4afa8a26f46e.png)

I am new to raspberry and amiga emulation. What am I doing wrong?

**Comment by solskogen** [comment]
`cd ~/amiberry
./amiberry`

**Comment by KostasDaskalos** [comment]
> `cd ~/amiberry && ./amiberry`

Yes this is working fine! Thank you very much for helping me!
